public class __M$Data_Comparison {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Comparison"); }
    };


public static final Object Comparison = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object semigroupComparison = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.semigroupFn)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.semigroupFn)).apply(__M$Data_Ordering.semigroupOrdering))).get("append"))).apply(v_0_i0))).apply(v1_1_i1); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object newtypeComparison = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidComparison = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return __M$Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Comparison.semigroupComparison; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get();
public static final Object defaultComparison = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(dictOrd_0_i0); };
public static final Object contravariantComparison = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1_i1)).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(y_3_i3)); }; }; }; }; return new __Record$63_6d_61_70_O(new String[]{"cmap"}, __field0); } }).get();
}
