public class __M$Control_Monad_Cont_Trans {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Monad.Cont.Trans"); }
    };


public static final Object ContT = __init$ContT();
    private static Object __init$ContT() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object withContT = __init$withContT();
    private static Object __init$withContT() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (k_2$r2) -> { return ((java.util.function.Function<Object, Object>) (v_1$r1)).apply(((java.util.function.Function<Object, Object>) (f_0$r0)).apply(k_2$r2)); }; }; }; }
public static final Object runContT = __init$runContT();
    private static Object __init$runContT() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (k_1$r1) -> { return ((java.util.function.Function<Object, Object>) (v_0$r0)).apply(k_1$r1); }; }; }
public static final Object newtypeContT = __init$newtypeContT();
    private static Object __init$newtypeContT() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object monadTransContT = __init$monadTransContT();
    private static Object __init$monadTransContT() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictMonad_0$r0) -> { Object Bind1_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0$r0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (m_2$r2) -> { return (java.util.function.Function<Object, Object>) (k_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_1$r1).get("bind"))).apply(m_2$r2))).apply(k_3$r3); }; }; }; return new __Record$6c_69_66_74_O(new String[]{"lift"}, __field0); } }).get(); }
public static final Object mapContT = __init$mapContT();
    private static Object __init$mapContT() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (k_2$r2) -> { return ((java.util.function.Function<Object, Object>) (f_0$r0)).apply(((java.util.function.Function<Object, Object>) (v_1$r1)).apply(k_2$r2)); }; }; }; }
public static final Object functorContT = __init$functorContT();
    private static Object __init$functorContT() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (k_3$r3) -> { return ((java.util.function.Function<Object, Object>) (v_2$r2)).apply((java.util.function.Function<Object, Object>) (a_4$r4) -> { return ((java.util.function.Function<Object, Object>) (k_3$r3)).apply(((java.util.function.Function<Object, Object>) (f_1$r1)).apply(a_4$r4)); }); }; }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }; }
public static final Object applyContT = __init$applyContT();
    private static Object __init$applyContT() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object functorContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.functorContT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (v1_3$r3) -> { return (java.util.function.Function<Object, Object>) (k_4$r4) -> { return ((java.util.function.Function<Object, Object>) (v_2$r2)).apply((java.util.function.Function<Object, Object>) (g_5$r5) -> { return ((java.util.function.Function<Object, Object>) (v1_3$r3)).apply((java.util.function.Function<Object, Object>) (a_6$r6) -> { return ((java.util.function.Function<Object, Object>) (k_4$r4)).apply(((java.util.function.Function<Object, Object>) (g_5$r5)).apply(a_6$r6)); }); }); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r7) -> { return functorContT1_1$r1; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }; }
public static final Object bindContT = __init$bindContT();
    private static Object __init$bindContT() { return (java.util.function.Function<Object, Object>) (dictBind_0$r0) -> { Object applyContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.applyContT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0$r0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (k_3$r3) -> { return (java.util.function.Function<Object, Object>) (k_prime__4$r4) -> { return ((java.util.function.Function<Object, Object>) (v_2$r2)).apply((java.util.function.Function<Object, Object>) (a_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (k_3$r3)).apply(a_5$r5))).apply(k_prime__4$r4); }); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r6) -> { return applyContT1_1$r1; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get(); }; }
public static final Object semigroupContT = __init$semigroupContT();
    private static Object __init$semigroupContT() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object applyContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.applyContT)).apply(dictApply_0$r0); return (java.util.function.Function<Object, Object>) (dictSemigroup_2$r2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (new java.util.function.Supplier<Object>() { public Object get() { Object Functor0_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) applyContT1_1$r1).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object __local_var_4$r4 = ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.append)).apply(dictSemigroup_2$r2); return (java.util.function.Function<Object, Object>) (a_5$r5) -> { return (java.util.function.Function<Object, Object>) (b_6$r6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) applyContT1_1$r1).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_3$r3).get("map"))).apply(__local_var_4$r4))).apply(a_5$r5)))).apply(b_6$r6); }; }; } }).get(); return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }; }; }
public static final Object applicativeContT = __init$applicativeContT();
    private static Object __init$applicativeContT() { return (java.util.function.Function<Object, Object>) (dictApplicative_0$r0) -> { Object applyContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.applyContT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0$r0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_2$r2) -> { return (java.util.function.Function<Object, Object>) (k_3$r3) -> { return ((java.util.function.Function<Object, Object>) (k_3$r3)).apply(a_2$r2); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r4) -> { return applyContT1_1$r1; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); }; }
public static final Object monadContT = __init$monadContT();
    private static Object __init$monadContT() { return (java.util.function.Function<Object, Object>) (dictMonad_0$r0) -> { Object applicativeContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.applicativeContT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0$r0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)); Object bindContT1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.bindContT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0$r0).get("Bind1"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r3) -> { return applicativeContT1_1$r1; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r4) -> { return bindContT1_2$r2; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get(); }; }
public static final Object monadAskContT = __init$monadAskContT();
    private static Object __init$monadAskContT() { return (java.util.function.Function<Object, Object>) (dictMonadAsk_0$r0) -> { Object monadContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.monadContT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadAsk_0$r0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (new java.util.function.Supplier<Object>() { public Object get() { Object Bind1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadAsk_0$r0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object __local_var_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Reader_Class.ask)).apply(dictMonadAsk_0$r0); return (java.util.function.Function<Object, Object>) (k_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_2$r2).get("bind"))).apply(__local_var_3$r3))).apply(k_4$r4); }; } }).get(); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r5) -> { return monadContT1_1$r1; }; return new __Record$4d_6f_6e_61_64_30_O$61_73_6b_O(new String[]{"ask", "Monad0"}, __field1, __field0); } }).get(); }; }
public static final Object monadReaderContT = __init$monadReaderContT();
    private static Object __init$monadReaderContT() { return (java.util.function.Function<Object, Object>) (dictMonadReader_0$r0) -> { Object MonadAsk0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadReader_0$r0).get("MonadAsk0"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) MonadAsk0_1$r1).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object ask_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Reader_Class.ask)).apply(MonadAsk0_1$r1); Object monadAskContT1_4$r4 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.monadAskContT)).apply(MonadAsk0_1$r1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_5$r5) -> { return (java.util.function.Function<Object, Object>) (v_6$r6) -> { return (java.util.function.Function<Object, Object>) (k_7$r7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_2$r2).get("bind"))).apply(ask_3$r3))).apply((java.util.function.Function<Object, Object>) (r_8$r8) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadReader_0$r0).get("local"))).apply(f_5$r5))).apply(((java.util.function.Function<Object, Object>) (v_6$r6)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadReader_0$r0).get("local"))).apply((java.util.function.Function<Object, Object>) (v_9$r9) -> { return r_8$r8; })))).apply(k_7$r7))); }); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_5$r10) -> { return monadAskContT1_4$r4; }; return new __Record$4d_6f_6e_61_64_41_73_6b_30_O$6c_6f_63_61_6c_O(new String[]{"local", "MonadAsk0"}, __field1, __field0); } }).get(); }; }
public static final Object monadContContT = __init$monadContContT();
    private static Object __init$monadContContT() { return (java.util.function.Function<Object, Object>) (dictMonad_0$r0) -> { Object monadContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.monadContT)).apply(dictMonad_0$r0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (k_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_2$r2)).apply((java.util.function.Function<Object, Object>) (a_4$r4) -> { return (java.util.function.Function<Object, Object>) (v1_5$r5) -> { return ((java.util.function.Function<Object, Object>) (k_3$r3)).apply(a_4$r4); }; }))).apply(k_3$r3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r6) -> { return monadContT1_1$r1; }; return new __Record$4d_6f_6e_61_64_30_O$63_61_6c_6c_43_43_O(new String[]{"callCC", "Monad0"}, __field1, __field0); } }).get(); }; }
public static final Object monadEffectContT = __init$monadEffectContT();
    private static Object __init$monadEffectContT() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { Object Monad0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0$r0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); Object monadContT1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.monadContT)).apply(Monad0_1$r1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object Bind1_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1$r1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (m_4$r4) -> { return (java.util.function.Function<Object, Object>) (k_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_3$r3).get("bind"))).apply(m_4$r4))).apply(k_5$r5); }; }; } }).get()))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r6) -> { return monadContT1_2$r2; }; return new __Record$4d_6f_6e_61_64_30_O$6c_69_66_74_45_66_66_65_63_74_O(new String[]{"liftEffect", "Monad0"}, __field1, __field0); } }).get(); }; }
public static final Object monadStateContT = __init$monadStateContT();
    private static Object __init$monadStateContT() { return (java.util.function.Function<Object, Object>) (dictMonadState_0$r0) -> { Object Monad0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadState_0$r0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); Object monadContT1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.monadContT)).apply(Monad0_1$r1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object Bind1_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1$r1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (m_4$r4) -> { return (java.util.function.Function<Object, Object>) (k_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_3$r3).get("bind"))).apply(m_4$r4))).apply(k_5$r5); }; }; } }).get()))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Monad_State_Class.state)).apply(dictMonadState_0$r0)); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r6) -> { return monadContT1_2$r2; }; return new __Record$4d_6f_6e_61_64_30_O$73_74_61_74_65_O(new String[]{"state", "Monad0"}, __field1, __field0); } }).get(); }; }
public static final Object monadSTContT = __init$monadSTContT();
    private static Object __init$monadSTContT() { return (java.util.function.Function<Object, Object>) (dictMonadST_0$r0) -> { Object Monad0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadST_0$r0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); Object monadContT1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.monadContT)).apply(Monad0_1$r1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object Bind1_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1$r1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (m_4$r4) -> { return (java.util.function.Function<Object, Object>) (k_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_3$r3).get("bind"))).apply(m_4$r4))).apply(k_5$r5); }; }; } }).get()))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Monad_ST_Class.liftST)).apply(dictMonadST_0$r0)); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r6) -> { return monadContT1_2$r2; }; return new __Record$4d_6f_6e_61_64_30_O$6c_69_66_74_53_54_O(new String[]{"liftST", "Monad0"}, __field1, __field0); } }).get(); }; }
public static final Object monoidContT = __init$monoidContT();
    private static Object __init$monoidContT() { return (java.util.function.Function<Object, Object>) (dictApplicative_0$r0) -> { Object applicativeContT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.applicativeContT)).apply(dictApplicative_0$r0); Object semigroupContT1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Cont_Trans.semigroupContT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0$r0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictMonoid_3$r3) -> { Object semigroupContT2_4$r4 = ((java.util.function.Function<Object, Object>) (semigroupContT1_2$r2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_3$r3).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) applicativeContT1_1$r1).get("pure"))).apply(((java.util.Map<String, Object>) dictMonoid_3$r3).get("mempty")); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_5$r5) -> { return semigroupContT2_4$r4; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }; }; }
}
