public class __M$Control_Monad_RWS {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Monad.RWS"); }
    };


public static final Object withRWS = __M$Control_Monad_RWS_Trans.withRWST;
public static final Object rws = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (r_1_i1) -> { return (java.util.function.Function<Object, Object>) (s_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Applicative.pure)).apply(__M$Data_Identity.applicativeIdentity))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0_i0)).apply(r_1_i1))).apply(s_2_i2)); }; }; };
public static final Object runRWS = (java.util.function.Function<Object, Object>) (m_0_i0) -> { return (java.util.function.Function<Object, Object>) (r_1_i1) -> { return (java.util.function.Function<Object, Object>) (s_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0_i0)).apply(r_1_i1))).apply(s_2_i2); }; }; };
public static final Object mapRWS = (java.util.function.Function<Object, Object>) (f_0_i0) -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0_i0))).apply(__M$Data_Identity.Identity)); return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (r_3_i3) -> { return (java.util.function.Function<Object, Object>) (s_4_i4) -> { return ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_2_i2)).apply(r_3_i3))).apply(s_4_i4)); }; }; }; };
public static final Object execRWS = (java.util.function.Function<Object, Object>) (m_0_i0) -> { return (java.util.function.Function<Object, Object>) (r_1_i1) -> { return (java.util.function.Function<Object, Object>) (s_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0_i0)).apply(r_1_i1))).apply(s_2_i2); return new __M$Data_Tuple.Tuple(((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3_i3)).value0, ((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3_i3)).value2); } }).get()); }; }; };
public static final Object evalRWS = (java.util.function.Function<Object, Object>) (m_0_i0) -> { return (java.util.function.Function<Object, Object>) (r_1_i1) -> { return (java.util.function.Function<Object, Object>) (s_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0_i0)).apply(r_1_i1))).apply(s_2_i2); return new __M$Data_Tuple.Tuple(((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3_i3)).value1, ((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3_i3)).value2); } }).get()); }; }; };
}
