public class __M$Control_Comonad_Traced_Class {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Comonad.Traced.Class"); }
    };


public static final Object track = __init$track();
    private static Object __init$track() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("track"); }; }
public static final Object tracks = __init$tracks();
    private static Object __init$tracks() { return (java.util.function.Function<Object, Object>) (dictComonadTraced_0$r0) -> { Object Comonad0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadTraced_0$r0).get("Comonad0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (w_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadTraced_0$r0).get("track"))).apply(((java.util.function.Function<Object, Object>) (f_2$r2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Comonad0_1$r1).get("extract"))).apply(w_3$r3))))).apply(w_3$r3); }; }; }; }
public static final Object lowerTrack = __init$lowerTrack();
    private static Object __init$lowerTrack() { return (java.util.function.Function<Object, Object>) (dictComonadTrans_0$r0) -> { Object lower_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Trans_Class.lower)).apply(dictComonadTrans_0$r0); return (java.util.function.Function<Object, Object>) (dictComonadTraced_2$r2) -> { Object lower1_3$r3 = ((java.util.function.Function<Object, Object>) (lower_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadTraced_2$r2).get("Comonad0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (m_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadTraced_2$r2).get("track"))).apply(m_4$r4)))).apply(lower1_3$r3); }; }; }; }
public static final Object listens = __init$listens();
    private static Object __init$listens() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply((java.util.function.Function<Object, Object>) (g_3$r3) -> { return (java.util.function.Function<Object, Object>) (t_4$r4) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (g_3$r3)).apply(t_4$r4), ((java.util.function.Function<Object, Object>) (f_1$r1)).apply(t_4$r4)); }; }))).apply(v_2$r2); }; }; }; }
public static final Object listen = __init$listen();
    private static Object __init$listen() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply((java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (t_3$r3) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_2$r2)).apply(t_3$r3), t_3$r3); }; }))).apply(v_1$r1); }; }; }
public static final Object comonadTracedTracedT = __init$comonadTracedTracedT();
    private static Object __init$comonadTracedTracedT() { return (java.util.function.Function<Object, Object>) (dictComonad_0$r0) -> { Object comonadTracedT_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Trans.comonadTracedT)).apply(dictComonad_0$r0); return (java.util.function.Function<Object, Object>) (dictMonoid_2$r2) -> { Object comonadTracedT1_3$r3 = ((java.util.function.Function<Object, Object>) (comonadTracedT_1$r1)).apply(dictMonoid_2$r2); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (t_4$r4) -> { return (java.util.function.Function<Object, Object>) (v_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_0$r0).get("extract"))).apply(v_5$r5))).apply(t_4$r4); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4$r6) -> { return comonadTracedT1_3$r3; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$74_72_61_63_6b_O(new String[]{"track", "Comonad0"}, __field1, __field0); } }).get(); }; }; }
public static final Object comonadTracedStoreT = __init$comonadTracedStoreT();
    private static Object __init$comonadTracedStoreT() { return (java.util.function.Function<Object, Object>) (dictComonadTraced_0$r0) -> { Object comonadStoreT_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Store_Trans.comonadStoreT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadTraced_0$r0).get("Comonad0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Class.lowerTrack)).apply(__M$Control_Comonad_Store_Trans.comonadTransStoreT))).apply(dictComonadTraced_0$r0); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return comonadStoreT_1$r1; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$74_72_61_63_6b_O(new String[]{"track", "Comonad0"}, __field1, __field0); } }).get(); }; }
public static final Object comonadTracedIdentityT = __init$comonadTracedIdentityT();
    private static Object __init$comonadTracedIdentityT() { return (java.util.function.Function<Object, Object>) (dictComonadTraced_0$r0) -> { Object comonadIdentityT_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Monad_Identity_Trans.comonadIdentityT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadTraced_0$r0).get("Comonad0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Class.lowerTrack)).apply(__M$Control_Comonad_Trans_Class.comonadTransIdentityT))).apply(dictComonadTraced_0$r0); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return comonadIdentityT_1$r1; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$74_72_61_63_6b_O(new String[]{"track", "Comonad0"}, __field1, __field0); } }).get(); }; }
public static final Object comonadTracedEnvT = __init$comonadTracedEnvT();
    private static Object __init$comonadTracedEnvT() { return (java.util.function.Function<Object, Object>) (dictComonadTraced_0$r0) -> { Object comonadEnvT_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Env_Trans.comonadEnvT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadTraced_0$r0).get("Comonad0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Class.lowerTrack)).apply(__M$Control_Comonad_Env_Trans.comonadTransEnvT))).apply(dictComonadTraced_0$r0); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return comonadEnvT_1$r1; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$74_72_61_63_6b_O(new String[]{"track", "Comonad0"}, __field1, __field0); } }).get(); }; }
public static final Object censor = __init$censor();
    private static Object __init$censor() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply((java.util.function.Function<Object, Object>) (v1_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_1$r1))).apply(v1_3$r3); }))).apply(v_2$r2); }; }; }; }
}
