public class __M$Data_Profunctor_Split {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Profunctor.Split"); }
    };


public static final class SplitF {
            public final Object value0;
            public final Object value1;
            public final Object value2;
            public SplitF(Object value0, Object value1, Object value2){
                this.value0 = value0;
                this.value1 = value1;
                this.value2 = value2;
            }
        }
public static final Object SplitF = (java.util.function.Function<Object, Object>) (value0_i0) -> (java.util.function.Function<Object, Object>) (value1_i1) -> (java.util.function.Function<Object, Object>) (value2_i2) -> { return new __M$Data_Profunctor_Split.SplitF(value0_i0, value1_i1, value2_i2); };
public static final Object unSplit = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0_i0)).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value2); }; };
public static final Object split = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (g_1_i1) -> { return (java.util.function.Function<Object, Object>) (fx_2_i2) -> { return new __M$Data_Profunctor_Split.SplitF(f_0_i0, g_1_i1, fx_2_i2); }; }; };
public static final Object profunctorSplit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (g_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (h_3_i3) -> { return (java.util.function.Function<Object, Object>) (i_4_i4) -> { Object __local_var_5_i5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(h_3_i3))).apply(f_0_i0); Object __local_var_6_i6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(g_1_i1))).apply(i_4_i4); return (java.util.function.Function<Object, Object>) (fx_7_i7) -> { return new __M$Data_Profunctor_Split.SplitF(__local_var_5_i5, __local_var_6_i6, fx_7_i7); }; }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2_i2)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2_i2)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2_i2)).value2); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get();
public static final Object lowerSplit = (java.util.function.Function<Object, Object>) (dictInvariant_0_i0) -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Invariant.imap)).apply(dictInvariant_0_i0); return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (b_3_i3) -> { return (java.util.function.Function<Object, Object>) (a_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(a_4_i4))).apply(b_3_i3); }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2_i2)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2_i2)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2_i2)).value2); }; };
public static final Object liftSplit = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0_i0 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (fx_2_i2) -> { return new __M$Data_Profunctor_Split.SplitF(__local_var_0_i0, __local_var_1_i1, fx_2_i2); }; } }).get();
public static final Object hoistSplit = (java.util.function.Function<Object, Object>) (nat_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (f_2_i2) -> { return (java.util.function.Function<Object, Object>) (g_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (fx_4_i4) -> { return new __M$Data_Profunctor_Split.SplitF(f_2_i2, g_3_i3, fx_4_i4); }))).apply(nat_0_i0); }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value2); }; };
public static final Object functorSplit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (g_2_i2) -> { return (java.util.function.Function<Object, Object>) (h_3_i3) -> { return (java.util.function.Function<Object, Object>) (fx_4_i4) -> { return new __M$Data_Profunctor_Split.SplitF(g_2_i2, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0_i0))).apply(h_3_i3), fx_4_i4); }; }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1_i1)).value2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
}
