public class __M$Data_Ord {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ord"); }
    };
    // FFI provided by ../javapurs-prelude/src/Data/Ord.java
    public static Object unsafeCompareImpl = (java.util.function.Function<Object, Object>) (lt) -> (java.util.function.Function<Object, Object>) (eq) -> (java.util.function.Function<Object, Object>) (gt) -> (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> {
        int cmp;
        if (x instanceof String && y instanceof String) {
            cmp = ((String) x).compareTo((String) y);
        } else if (x instanceof Integer && y instanceof Integer) {
            cmp = ((Integer) x).compareTo((Integer) y);
        } else if (x instanceof Double && y instanceof Double) {
            // JavaScript compares with < and >, so -0.0 equals 0.0 and NaN is
            // equal to everything; Double.compareTo would order both instead.
            double left = (Double) x;
            double right = (Double) y;
            cmp = left < right ? -1 : left > right ? 1 : 0;
        } else if (x instanceof Boolean && y instanceof Boolean) {
            cmp = ((Boolean) x).compareTo((Boolean) y);
        } else {
            throw new RuntimeException("unsafeCompareImpl: Unsupported types " + x.getClass() + " and " + y.getClass());
        }
        if (cmp < 0) return lt;
        if (cmp > 0) return gt;
        return eq;
    };

    public static Object ordBooleanImpl = unsafeCompareImpl;
    public static Object ordIntImpl = unsafeCompareImpl;
    public static Object ordNumberImpl = unsafeCompareImpl;
    public static Object ordStringImpl = unsafeCompareImpl;
    public static Object ordCharImpl = unsafeCompareImpl;

    public static Object ordArrayImpl = (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Function<Object, Object>) (xs) -> (java.util.function.Function<Object, Object>) (ys) -> {
        Object[] arr1 = (Object[]) xs;
        Object[] arr2 = (Object[]) ys;
        int xlen = arr1.length;
        int ylen = arr2.length;
        int i = 0;
        while (i < xlen && i < ylen) {
            Object x = arr1[i];
            Object y = arr2[i];
            int o = (Integer) ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) f).apply(x)).apply(y);
            if (o != 0) {
                return o;
            }
            i++;
        }
        if (xlen == ylen) {
            return 0;
        } else if (xlen > ylen) {
            return -1;
        } else {
            return 1;
        }
    };


public static final Object ordVoid = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return __M$Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Eq.eqVoid; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordUnit = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return __M$Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Eq.eqUnit; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordString = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordStringImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Eq.eqString; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordRecordNil = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (java.util.function.Function<Object, Object>) (v2_2_i2) -> { return __M$Data_Ordering.__singleton$EQ.value; }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> { return __M$Data_Eq.eqRowNil; }; return new __Record$45_71_52_65_63_6f_72_64_30_O$63_6f_6d_70_61_72_65_52_65_63_6f_72_64_O(new String[]{"compareRecord", "EqRecord0"}, __field1, __field0); } }).get();
public static final Object ordProxy = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return __M$Data_Ordering.__singleton$EQ.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Eq.eqProxy; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordOrdering = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Ordering.LT))) ? ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Ordering.LT))) ? __M$Data_Ordering.__singleton$EQ.value : __M$Data_Ordering.__singleton$LT.value) : ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Ordering.EQ))) ? ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Ordering.EQ))) ? __M$Data_Ordering.__singleton$EQ.value : ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Ordering.LT))) ? __M$Data_Ordering.__singleton$GT.value : ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Ordering.GT))) ? __M$Data_Ordering.__singleton$LT.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))) : ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Ordering.GT))) ? ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Ordering.GT))) ? __M$Data_Ordering.__singleton$EQ.value : __M$Data_Ordering.__singleton$GT.value) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Ordering.eqOrdering; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordNumber = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordNumberImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Eq.eqNumber; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordInt = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordIntImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Eq.eqInt; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordChar = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordCharImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Eq.eqChar; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object ordBoolean = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordBooleanImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Eq.eqBoolean; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get();
public static final Object compareRecord = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("compareRecord"); };
public static final Object ordRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictOrdRecord_1_i1) -> { Object eqRec1_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Eq.eqRec)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_1_i1).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_1_i1).get("compareRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3_i3) -> { return eqRec1_2_i2; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; };
public static final Object compare1 = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("compare1"); };
public static final Object compare = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("compare"); };
public static final Object comparing = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(((java.util.function.Function<Object, Object>) (f_1_i1)).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (f_1_i1)).apply(y_3_i3)); }; }; }; };
public static final Object greaterThan = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (a1_1_i1) -> { return (java.util.function.Function<Object, Object>) (a2_2_i2) -> { return (((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2))) instanceof __M$Data_Ordering.GT); }; }; };
public static final Object greaterThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (a1_1_i1) -> { return (java.util.function.Function<Object, Object>) (a2_2_i2) -> { return (!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2))) instanceof __M$Data_Ordering.LT))))); }; }; };
public static final Object lessThan = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (a1_1_i1) -> { return (java.util.function.Function<Object, Object>) (a2_2_i2) -> { return (((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2))) instanceof __M$Data_Ordering.LT); }; }; };
public static final Object signum = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictRing_1_i1) -> { Object Semiring0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object zero_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Data_Semiring.zero)).apply(Semiring0_2_i2); Object Semiring01_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object one_5_i5 = ((java.util.function.Function<Object, Object>) (__M$Data_Semiring.one)).apply(Semiring0_2_i2); return (java.util.function.Function<Object, Object>) (x_6_i6) -> { return ( ((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_6_i6))).apply(zero_3_i3))) instanceof __M$Data_Ordering.LT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1_i1).get("sub"))).apply(((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(((java.util.Map<String, Object>) Semiring01_4_i4).get("one")) : ( ((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_6_i6))).apply(zero_3_i3))) instanceof __M$Data_Ordering.GT))) ? one_5_i5 : x_6_i6)); }; }; };
public static final Object lessThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (a1_1_i1) -> { return (java.util.function.Function<Object, Object>) (a2_2_i2) -> { return (!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(a1_1_i1))).apply(a2_2_i2))) instanceof __M$Data_Ordering.GT))))); }; }; };
public static final Object max = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return (java.util.function.Function<Object, Object>) (y_2_i2) -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_1_i1))).apply(y_2_i2); return ( ((Boolean) ((((Object) (v_3_i3)) instanceof __M$Data_Ordering.LT))) ? y_2_i2 : ( ((Boolean) ((((Object) (v_3_i3)) instanceof __M$Data_Ordering.EQ))) ? x_1_i1 : ( ((Boolean) ((((Object) (v_3_i3)) instanceof __M$Data_Ordering.GT))) ? x_1_i1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; };
public static final Object min = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return (java.util.function.Function<Object, Object>) (y_2_i2) -> { Object v_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_1_i1))).apply(y_2_i2); return ( ((Boolean) ((((Object) (v_3_i3)) instanceof __M$Data_Ordering.LT))) ? x_1_i1 : ( ((Boolean) ((((Object) (v_3_i3)) instanceof __M$Data_Ordering.EQ))) ? x_1_i1 : ( ((Boolean) ((((Object) (v_3_i3)) instanceof __M$Data_Ordering.GT))) ? y_2_i2 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; };
public static final Object ordArray = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { Object eqArray_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eqArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (xs_2_i2) -> { return (java.util.function.Function<Object, Object>) (ys_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordIntImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_4_i4) -> { return (java.util.function.Function<Object, Object>) (y_5_i5) -> { Object v_6_i6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_4_i4))).apply(y_5_i5); return ( ((Boolean) ((((Object) (v_6_i6)) instanceof __M$Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((((Object) (v_6_i6)) instanceof __M$Data_Ordering.LT))) ? 1 : ( ((Boolean) ((((Object) (v_6_i6)) instanceof __M$Data_Ordering.GT))) ? -1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }))).apply(xs_2_i2))).apply(ys_3_i3)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i7) -> { return eqArray_1_i1; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); };
public static final Object ord1Array = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordArray)).apply(dictOrd_0_i0)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> { return __M$Data_Eq.eq1Array; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get();
public static final Object ordRecordCons = (java.util.function.Function<Object, Object>) (dictOrdRecord_0_i0) -> { Object eqRowCons_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Eq.eqRowCons)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_0_i0).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (_dollar___unused_2_i2) -> { return (java.util.function.Function<Object, Object>) (dictIsSymbol_3_i3) -> { Object eqRowCons1_4_i4 = ((java.util.function.Function<Object, Object>) (eqRowCons_1_i1)).apply(dictIsSymbol_3_i3); return (java.util.function.Function<Object, Object>) (dictOrd_5_i5) -> { Object eqRowCons2_6_i6 = ((java.util.function.Function<Object, Object>) (eqRowCons1_4_i4)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_5_i5).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_7_i7) -> { return (java.util.function.Function<Object, Object>) (ra_8_i8) -> { return (java.util.function.Function<Object, Object>) (rb_9_i9) -> { Object key_10_i10 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_3_i3).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value); Object left_11_i11 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_5_i5).get("compare"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(key_10_i10))).apply(ra_8_i8)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(key_10_i10))).apply(rb_9_i9)); return ( ((Boolean) ((!(((Boolean) ((((Object) (left_11_i11)) instanceof __M$Data_Ordering.EQ))))))) ? left_11_i11 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrdRecord_0_i0).get("compareRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value))).apply(ra_8_i8))).apply(rb_9_i9)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_7_i12) -> { return eqRowCons2_6_i6; }; return new __Record$45_71_52_65_63_6f_72_64_30_O$63_6f_6d_70_61_72_65_52_65_63_6f_72_64_O(new String[]{"compareRecord", "EqRecord0"}, __field1, __field0); } }).get(); }; }; }; };
public static final Object clamp = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (low_1_i1) -> { return (java.util.function.Function<Object, Object>) (hi_2_i2) -> { return (java.util.function.Function<Object, Object>) (x_3_i3) -> { Object __local_var_4_i4 = (new java.util.function.Supplier<Object>() { public Object get() { Object v_4_i5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(low_1_i1))).apply(x_3_i3); return ( ((Boolean) ((((Object) (v_4_i5)) instanceof __M$Data_Ordering.LT))) ? x_3_i3 : ( ((Boolean) ((((Object) (v_4_i5)) instanceof __M$Data_Ordering.EQ))) ? low_1_i1 : ( ((Boolean) ((((Object) (v_4_i5)) instanceof __M$Data_Ordering.GT))) ? low_1_i1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); } }).get(); Object v_5_i6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(hi_2_i2))).apply(__local_var_4_i4); return ( ((Boolean) ((((Object) (v_5_i6)) instanceof __M$Data_Ordering.LT))) ? hi_2_i2 : ( ((Boolean) ((((Object) (v_5_i6)) instanceof __M$Data_Ordering.EQ))) ? hi_2_i2 : ( ((Boolean) ((((Object) (v_5_i6)) instanceof __M$Data_Ordering.GT))) ? __local_var_4_i4 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; }; };
public static final Object between = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (low_1_i1) -> { return (java.util.function.Function<Object, Object>) (hi_2_i2) -> { return (java.util.function.Function<Object, Object>) (x_3_i3) -> { return ( ((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_3_i3))).apply(low_1_i1))) instanceof __M$Data_Ordering.LT))) ? false : (!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_3_i3))).apply(hi_2_i2))) instanceof __M$Data_Ordering.GT)))))); }; }; }; };
public static final Object abs = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictRing_1_i1) -> { Object zero_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_Semiring.zero)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (x_3_i3) -> { return ( ((Boolean) ((!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(x_3_i3))).apply(zero_2_i2))) instanceof __M$Data_Ordering.LT))))))) ? x_3_i3 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1_i1).get("sub"))).apply(((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_1_i1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(x_3_i3)); }; }; };
}
