public class __M$Data_Ring {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ring"); }
    };
    // FFI provided by ../javapurs-prelude/src/Data/Ring.java
    public static Object intSub = (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> (Integer) x - (Integer) y;
    public static Object numSub = (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> (Double) x - (Double) y;


public static final Object subRecord = __init$subRecord();
    private static Object __init$subRecord() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("subRecord"); }; }
public static final Object sub = __init$sub();
    private static Object __init$sub() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("sub"); }; }
public static final Object ringUnit = __init$ringUnit();
    private static Object __init$ringUnit() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return __M$Data_Unit.unit; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r2) -> { return __M$Data_Semiring.semiringUnit; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); }
public static final Object ringRecordNil = __init$ringRecordNil();
    private static Object __init$ringRecordNil() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (java.util.function.Function<Object, Object>) (v2_2$r2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { return new __Record$(new String[]{}); } }).get(); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r3) -> { return __M$Data_Semiring.semiringRecordNil; }; return new __Record$53_65_6d_69_72_69_6e_67_52_65_63_6f_72_64_30_O$73_75_62_52_65_63_6f_72_64_O(new String[]{"subRecord", "SemiringRecord0"}, __field1, __field0); } }).get(); }
public static final Object ringRecordCons = __init$ringRecordCons();
    private static Object __init$ringRecordCons() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (dictRingRecord_2$r2) -> { Object semiringRecordCons1_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semiring.semiringRecordCons)).apply(dictIsSymbol_0$r0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_2$r2).get("SemiringRecord0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictRing_4$r4) -> { Object semiringRecordCons2_5$r5 = ((java.util.function.Function<Object, Object>) (semiringRecordCons1_3$r3)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_4$r4).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_6$r6) -> { return (java.util.function.Function<Object, Object>) (ra_7$r7) -> { return (java.util.function.Function<Object, Object>) (rb_8$r8) -> { Object key_9$r9 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value); Object get_10$r10 = ((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(key_9$r9); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeSet)).apply(key_9$r9))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_4$r4).get("sub"))).apply(((java.util.function.Function<Object, Object>) (get_10$r10)).apply(ra_7$r7)))).apply(((java.util.function.Function<Object, Object>) (get_10$r10)).apply(rb_8$r8))))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_2$r2).get("subRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value))).apply(ra_7$r7))).apply(rb_8$r8)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_6$r11) -> { return semiringRecordCons2_5$r5; }; return new __Record$53_65_6d_69_72_69_6e_67_52_65_63_6f_72_64_30_O$73_75_62_52_65_63_6f_72_64_O(new String[]{"subRecord", "SemiringRecord0"}, __field1, __field0); } }).get(); }; }; }; }; }
public static final Object ringRecord = __init$ringRecord();
    private static Object __init$ringRecord() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictRingRecord_1$r1) -> { Object semiringRecord1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semiring.semiringRecord)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_1$r1).get("SemiringRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRingRecord_1$r1).get("subRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r3) -> { return semiringRecord1_2$r2; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); }; }; }
public static final Object ringProxy = __init$ringProxy();
    private static Object __init$ringProxy() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return __M$Type_Proxy.__singleton$Proxy.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r2) -> { return __M$Data_Semiring.semiringProxy; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); }
public static final Object ringNumber = __init$ringNumber();
    private static Object __init$ringNumber() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Ring.numSub; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Semiring.semiringNumber; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); }
public static final Object ringInt = __init$ringInt();
    private static Object __init$ringInt() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Ring.intSub; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Semiring.semiringInt; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); }
public static final Object ringFn = __init$ringFn();
    private static Object __init$ringFn() { return (java.util.function.Function<Object, Object>) (dictRing_0$r0) -> { Object semiringFn_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Semiring.semiringFn)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0$r0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (g_3$r3) -> { return (java.util.function.Function<Object, Object>) (x_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0$r0).get("sub"))).apply(((java.util.function.Function<Object, Object>) (f_2$r2)).apply(x_4$r4)))).apply(((java.util.function.Function<Object, Object>) (g_3$r3)).apply(x_4$r4)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r5) -> { return semiringFn_1$r1; }; return new __Record$53_65_6d_69_72_69_6e_67_30_O$73_75_62_O(new String[]{"sub", "Semiring0"}, __field1, __field0); } }).get(); }; }
public static final Object negate = __init$negate();
    private static Object __init$negate() { return (java.util.function.Function<Object, Object>) (dictRing_0$r0) -> { Object Semiring0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0$r0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0$r0).get("sub"))).apply(((java.util.Map<String, Object>) Semiring0_1$r1).get("zero")))).apply(a_2$r2); }; }; }
}
