public class __M$Data_Decidable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Decidable"); }
    };


public static final Object lose = __init$lose();
    private static Object __init$lose() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("lose"); }; }
public static final Object lost = __init$lost();
    private static Object __init$lost() { return (java.util.function.Function<Object, Object>) (dictDecidable_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDecidable_0$r0).get("lose"))).apply((java.util.function.Function<Object, Object>) (x_1$r1) -> { return x_1$r1; }); }; }
public static final Object decidablePredicate = __init$decidablePredicate();
    private static Object __init$decidablePredicate() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (a_1$r1) -> { Object spin_2$r2 = (java.util.function.Function<Object, Object>) (v_3$r3) -> { Object __tco_v_3$r3 = v_3$r3; while(true) { final Object __final_v_3$r3 = __tco_v_3$r3; try { { final Object __next_v_3$r3 = __final_v_3$r3; __tco_v_3$r3 = __next_v_3$r3; continue; } } catch (TcoLoop __tco_ex) { if (!"spin_2$r2".equals(__tco_ex.loopId)) throw __tco_ex; __tco_v_3$r3 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_2$r2)).apply(((java.util.function.Function<Object, Object>) (f_0$r0)).apply(a_1$r1)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r4) -> { return __M$Data_Decide.choosePredicate; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r5) -> { return __M$Data_Divisible.divisiblePredicate; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get(); }
public static final Object decidableOp = __init$decidableOp();
    private static Object __init$decidableOp() { return (java.util.function.Function<Object, Object>) (dictMonoid_0$r0) -> { Object chooseOp_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Decide.chooseOp)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_0$r0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); Object divisibleOp_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Divisible.divisibleOp)).apply(dictMonoid_0$r0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_3$r3) -> { return (java.util.function.Function<Object, Object>) (a_4$r4) -> { Object spin_5$r5 = (java.util.function.Function<Object, Object>) (v_6$r6) -> { Object __tco_v_6$r6 = v_6$r6; while(true) { final Object __final_v_6$r6 = __tco_v_6$r6; try { { final Object __next_v_6$r6 = __final_v_6$r6; __tco_v_6$r6 = __next_v_6$r6; continue; } } catch (TcoLoop __tco_ex) { if (!"spin_5$r5".equals(__tco_ex.loopId)) throw __tco_ex; __tco_v_6$r6 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_5$r5)).apply(((java.util.function.Function<Object, Object>) (f_3$r3)).apply(a_4$r4)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r7) -> { return chooseOp_1$r1; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r8) -> { return divisibleOp_2$r2; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get(); }; }
public static final Object decidableEquivalence = __init$decidableEquivalence();
    private static Object __init$decidableEquivalence() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (a_1$r1) -> { Object spin_2$r2 = (java.util.function.Function<Object, Object>) (v_3$r3) -> { Object __tco_v_3$r3 = v_3$r3; while(true) { final Object __final_v_3$r3 = __tco_v_3$r3; try { { final Object __next_v_3$r3 = __final_v_3$r3; __tco_v_3$r3 = __next_v_3$r3; continue; } } catch (TcoLoop __tco_ex) { if (!"spin_2$r2".equals(__tco_ex.loopId)) throw __tco_ex; __tco_v_3$r3 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_2$r2)).apply(((java.util.function.Function<Object, Object>) (f_0$r0)).apply(a_1$r1)); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r4) -> { return __M$Data_Decide.chooseEquivalence; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r5) -> { return __M$Data_Divisible.divisibleEquivalence; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get(); }
public static final Object decidableComparison = __init$decidableComparison();
    private static Object __init$decidableComparison() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (a_1$r1) -> { return (java.util.function.Function<Object, Object>) (v_2$r2) -> { Object spin_3$r3 = (java.util.function.Function<Object, Object>) (v_4$r4) -> { Object __tco_v_4$r4 = v_4$r4; while(true) { final Object __final_v_4$r4 = __tco_v_4$r4; try { { final Object __next_v_4$r4 = __final_v_4$r4; __tco_v_4$r4 = __next_v_4$r4; continue; } } catch (TcoLoop __tco_ex) { if (!"spin_3$r3".equals(__tco_ex.loopId)) throw __tco_ex; __tco_v_4$r4 = __tco_ex.args[0]; } } }; return ((java.util.function.Function<Object, Object>) (spin_3$r3)).apply(((java.util.function.Function<Object, Object>) (f_0$r0)).apply(a_1$r1)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r5) -> { return __M$Data_Decide.chooseComparison; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r6) -> { return __M$Data_Divisible.divisibleComparison; }; return new __Record$44_65_63_69_64_65_30_O$44_69_76_69_73_69_62_6c_65_31_O$6c_6f_73_65_O(new String[]{"lose", "Decide0", "Divisible1"}, __field1, __field2, __field0); } }).get(); }
}
