public class __M$Data_Array_NonEmpty {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Array.NonEmpty"); }
    };


public static final Object unsafeFromArrayF = __init$unsafeFromArrayF();
    private static Object __init$unsafeFromArrayF() { return __M$Unsafe_Coerce.unsafeCoerce; }
public static final Object unsafeFromArray = __init$unsafeFromArray();
    private static Object __init$unsafeFromArray() { return __M$Data_Array_NonEmpty_Internal.NonEmptyArray; }
public static final Object transpose = __init$transpose();
    private static Object __init$transpose() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.transpose))).apply(((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))); }
public static final Object toArray = __init$toArray();
    private static Object __init$toArray() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return v_0_i0; }; }
public static final Object unionByprime = __init$unionByprime();
    private static Object __init$unionByprime() { return (java.util.function.Function<Object, Object>) (eq_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.unionBy)).apply(eq_0_i0))).apply(xs_1_i1)); }; }; }
public static final Object unionprime = __init$unionprime();
    private static Object __init$unionprime() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unionByprime)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0_i0)); }; }
public static final Object unionBy = __init$unionBy();
    private static Object __init$unionBy() { return (java.util.function.Function<Object, Object>) (eq_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.unionBy)).apply(eq_0_i0))).apply(xs_1_i1))))).apply(__M$Data_Array_NonEmpty.toArray); }; }; }
public static final Object union = __init$union();
    private static Object __init$union() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unionBy)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0_i0)); }; }
public static final Object unzip = __init$unzip();
    private static Object __init$unzip() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value0), ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)); }))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.unzip))).apply(__M$Data_Array_NonEmpty.toArray)); }
public static final Object updateAt = __init$updateAt();
    private static Object __init$updateAt() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArrayF))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.updateAt)).apply(i_0_i0))).apply(x_1_i1)))).apply(__M$Data_Array_NonEmpty.toArray)); }; }; }
public static final Object zip = __init$zip();
    private static Object __init$zip() { return (java.util.function.Function<Object, Object>) (xs_0_i0) -> { return (java.util.function.Function<Object, Object>) (ys_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.zipWithImpl)).apply(__M$Data_Tuple.Tuple))).apply(xs_0_i0))).apply(ys_1_i1)); }; }; }
public static final Object zipWith = __init$zipWith();
    private static Object __init$zipWith() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return (java.util.function.Function<Object, Object>) (ys_2_i2) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.zipWithImpl)).apply(f_0_i0))).apply(xs_1_i1))).apply(ys_2_i2)); }; }; }; }
public static final Object zipWithA = __init$zipWithA();
    private static Object __init$zipWithA() { return (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (xs_2_i2) -> { return (java.util.function.Function<Object, Object>) (ys_3_i3) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArrayF)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Traversable.sequenceDefault)).apply(__M$Data_Traversable.traversableArray))).apply(dictApplicative_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.zipWithImpl)).apply(f_1_i1))).apply(xs_2_i2))).apply(ys_3_i3))); }; }; }; }; }
public static final Object splitAt = __init$splitAt();
    private static Object __init$splitAt() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.splitAt)).apply(i_0_i0))).apply(xs_1_i1); }; }; }
public static final Object some = __init$some();
    private static Object __init$some() { return (java.util.function.Function<Object, Object>) (dictAlternative_0_i0) -> { Object some1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Array.some)).apply(dictAlternative_0_i0); return (java.util.function.Function<Object, Object>) (dictLazy_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArrayF))).apply(((java.util.function.Function<Object, Object>) (some1_1_i1)).apply(dictLazy_2_i2)); }; }; }
public static final Object snocprime = __init$snocprime();
    private static Object __init$snocprime() { return (java.util.function.Function<Object, Object>) (xs_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (__M$Control_Monad_ST_Internal.run)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array_ST.withArray)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array_ST.push)).apply(x_1_i1)))).apply(xs_0_i0))); }; }; }
public static final Object snoc = __init$snoc();
    private static Object __init$snoc() { return (java.util.function.Function<Object, Object>) (xs_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (__M$Control_Monad_ST_Internal.run)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array_ST.withArray)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array_ST.push)).apply(x_1_i1)))).apply(xs_0_i0))); }; }; }
public static final Object singleton = __init$singleton();
    private static Object __init$singleton() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(__M$Data_Array.singleton); }
public static final Object replicate = __init$replicate();
    private static Object __init$replicate() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.replicateImpl)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object v_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_Ord.ordInt).get("compare"))).apply(1))).apply(i_0_i0); return ( ((Boolean) ((((Object) (v_2_i2)) instanceof __M$Data_Ordering.LT))) ? i_0_i0 : ( ((Boolean) ((((Object) (v_2_i2)) instanceof __M$Data_Ordering.EQ))) ? 1 : ( ((Boolean) ((((Object) (v_2_i2)) instanceof __M$Data_Ordering.GT))) ? 1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); } }).get()))).apply(x_1_i1)); }; }; }
public static final Object range = __init$range();
    private static Object __init$range() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return (java.util.function.Function<Object, Object>) (y_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.rangeImpl)).apply(x_0_i0))).apply(y_1_i1)); }; }; }
public static final Object prependArray = __init$prependArray();
    private static Object __init$prependArray() { return (java.util.function.Function<Object, Object>) (xs_0_i0) -> { return (java.util.function.Function<Object, Object>) (ys_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.concatArray)).apply(xs_0_i0))).apply(ys_1_i1)); }; }; }
public static final Object modifyAt = __init$modifyAt();
    private static Object __init$modifyAt() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArrayF))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.modifyAt)).apply(i_0_i0))).apply(f_1_i1)))).apply(__M$Data_Array_NonEmpty.toArray)); }; }; }
public static final Object intersectByprime = __init$intersectByprime();
    private static Object __init$intersectByprime() { return (java.util.function.Function<Object, Object>) (eq_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return __M$Data_Array_NonEmpty.__direct$22(eq_0_i0, xs_1_i1); }; }; }
private static Object __direct$22(Object eq_0_i0, Object xs_1_i1) { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.intersectBy)).apply(eq_0_i0))).apply(xs_1_i1); }
public static final Object intersectBy = __init$intersectBy();
    private static Object __init$intersectBy() { return (java.util.function.Function<Object, Object>) (eq_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(( ((Boolean) ((__M$Data_Array_NonEmpty.intersectByprime == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.intersectByprime)).apply(eq_0_i0))).apply(xs_1_i1) : __M$Data_Array_NonEmpty.__direct$22(eq_0_i0, xs_1_i1))))).apply(__M$Data_Array_NonEmpty.toArray); }; }; }
public static final Object intersectprime = __init$intersectprime();
    private static Object __init$intersectprime() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.intersectByprime)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0_i0)); }; }
public static final Object intersect = __init$intersect();
    private static Object __init$intersect() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.intersectBy)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0_i0)); }; }
public static final Object intercalate = __init$intercalate();
    private static Object __init$intercalate() { return (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.intercalate)).apply(__M$Data_Array_NonEmpty_Internal.foldable1NonEmptyArray))).apply(dictSemigroup_0_i0); }; }
public static final Object insertAt = __init$insertAt();
    private static Object __init$insertAt() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArrayF))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.insertAt)).apply(i_0_i0))).apply(x_1_i1)))).apply(__M$Data_Array_NonEmpty.toArray)); }; }; }
public static final Object fromFoldable1 = __init$fromFoldable1();
    private static Object __init$fromFoldable1() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.fromFoldable)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("Foldable0"))).apply(null /* TODO: PrimUndefined */))); }; }
public static final Object fromArray = __init$fromArray();
    private static Object __init$fromArray() { return (java.util.function.Function<Object, Object>) (xs_0_i0) -> { return ( ((Boolean) ((((int) (((Object[]) (Object)(xs_0_i0)).length)) > ((int) (0))))) ? new __M$Data_Maybe.Just(xs_0_i0) : __M$Data_Maybe.__singleton$Nothing.value); }; }
public static final Object fromFoldable = __init$fromFoldable();
    private static Object __init$fromFoldable() { return (java.util.function.Function<Object, Object>) (dictFoldable_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.fromArray))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.fromFoldable)).apply(dictFoldable_0_i0)); }; }
public static final Object transposeprime = __init$transposeprime();
    private static Object __init$transposeprime() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.fromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.transpose))).apply(((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))); }
public static final Object foldr1 = __init$foldr1();
    private static Object __init$foldr1() { return ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.foldr1)).apply(__M$Data_Array_NonEmpty_Internal.foldable1NonEmptyArray); }
public static final Object foldl1 = __init$foldl1();
    private static Object __init$foldl1() { return ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.foldl1)).apply(__M$Data_Array_NonEmpty_Internal.foldable1NonEmptyArray); }
public static final Object foldMap1 = __init$foldMap1();
    private static Object __init$foldMap1() { return (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.foldMap1)).apply(__M$Data_Array_NonEmpty_Internal.foldable1NonEmptyArray))).apply(dictSemigroup_0_i0); }; }
public static final Object fold1 = __init$fold1();
    private static Object __init$fold1() { return (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.fold1)).apply(__M$Data_Array_NonEmpty_Internal.foldable1NonEmptyArray))).apply(dictSemigroup_0_i0); }; }
public static final Object differenceprime = __init$differenceprime();
    private static Object __init$differenceprime() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { Object difference1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Array.difference)).apply(dictEq_0_i0); return (java.util.function.Function<Object, Object>) (xs_2_i2) -> { return ((java.util.function.Function<Object, Object>) (difference1_1_i1)).apply(xs_2_i2); }; }; }
public static final Object consprime = __init$consprime();
    private static Object __init$consprime() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.concatArray)).apply(new Object[]{x_0_i0}))).apply(xs_1_i1)); }; }; }
public static final Object fromNonEmpty = __init$fromNonEmpty();
    private static Object __init$fromNonEmpty() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.concatArray)).apply(new Object[]{((__M$Data_NonEmpty.NonEmpty) (Object)(v_0_i0)).value0}))).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(v_0_i0)).value1)); }; }
public static final Object concatMap = __init$concatMap();
    private static Object __init$concatMap() { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0_i0 = ((java.util.function.Function<Object, Object>) (__M$Control_Bind.bind)).apply(__M$Control_Bind.bindArray); return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (a_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_0_i0)).apply(a_2_i2))).apply(b_1_i1); }; }; } }).get(); }
public static final Object concat = __init$concat();
    private static Object __init$concat() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.concat))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.toArray))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Functor.arrayMap)).apply(__M$Data_Array_NonEmpty.toArray)))); }
public static final Object appendArray = __init$appendArray();
    private static Object __init$appendArray() { return (java.util.function.Function<Object, Object>) (xs_0_i0) -> { return (java.util.function.Function<Object, Object>) (ys_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeFromArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.concatArray)).apply(xs_0_i0))).apply(ys_1_i1)); }; }; }
public static final Object alterAt = __init$alterAt();
    private static Object __init$alterAt() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.alterAt)).apply(i_0_i0))).apply(f_1_i1)))).apply(__M$Data_Array_NonEmpty.toArray); }; }; }
public static final Object adaptMaybe = __init$adaptMaybe();
    private static Object __init$adaptMaybe() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Partial_Unsafe.unsafePartial)).apply((java.util.function.Function<Object, Object>) (_dollar___unused_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Maybe.fromJust)).apply(null /* TODO: PrimUndefined */)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0_i0))).apply(__M$Data_Array_NonEmpty.toArray)); }); }; }
public static final Object head = __init$head();
    private static Object __init$head() { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptMaybe)).apply(__M$Data_Array.head); }
public static final Object init = __init$init();
    private static Object __init$init() { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptMaybe)).apply(__M$Data_Array.init); }
public static final Object last = __init$last();
    private static Object __init$last() { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptMaybe)).apply(__M$Data_Array.last); }
public static final Object tail = __init$tail();
    private static Object __init$tail() { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptMaybe)).apply(__M$Data_Array.tail); }
public static final Object uncons = __init$uncons();
    private static Object __init$uncons() { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptMaybe)).apply(__M$Data_Array.uncons); }
public static final Object toNonEmpty = __init$toNonEmpty();
    private static Object __init$toNonEmpty() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.uncons))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return new __M$Data_NonEmpty.NonEmpty(__Record$68_65_61_64_O$74_61_69_6c_O.read0(v_0_i0), __Record$68_65_61_64_O$74_61_69_6c_O.read1(v_0_i0)); }); }
public static final Object unsnoc = __init$unsnoc();
    private static Object __init$unsnoc() { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptMaybe)).apply(__M$Data_Array.unsnoc); }
public static final Object adaptAny = __init$adaptAny();
    private static Object __init$adaptAny() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0_i0))).apply(__M$Data_Array_NonEmpty.toArray); }; }
public static final Object all = __init$all();
    private static Object __init$all() { return (java.util.function.Function<Object, Object>) (p_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.all)).apply(p_0_i0)); }; }
public static final Object any = __init$any();
    private static Object __init$any() { return (java.util.function.Function<Object, Object>) (p_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.any)).apply(p_0_i0)); }; }
public static final Object catMaybes = __init$catMaybes();
    private static Object __init$catMaybes() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.catMaybes))).apply(__M$Data_Array_NonEmpty.toArray); }
public static final Object delete = __init$delete();
    private static Object __init$delete() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.delete)).apply(dictEq_0_i0))).apply(x_1_i1)); }; }; }
public static final Object deleteAt = __init$deleteAt();
    private static Object __init$deleteAt() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.deleteAt)).apply(i_0_i0)); }; }
public static final Object deleteBy = __init$deleteBy();
    private static Object __init$deleteBy() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.deleteBy)).apply(f_0_i0))).apply(x_1_i1)); }; }; }
public static final Object difference = __init$difference();
    private static Object __init$difference() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.difference)).apply(dictEq_0_i0))).apply(xs_1_i1)); }; }; }
public static final Object drop = __init$drop();
    private static Object __init$drop() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.drop)).apply(i_0_i0)); }; }
public static final Object dropEnd = __init$dropEnd();
    private static Object __init$dropEnd() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.dropEnd)).apply(i_0_i0)); }; }
public static final Object dropWhile = __init$dropWhile();
    private static Object __init$dropWhile() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.dropWhile)).apply(f_0_i0)); }; }
public static final Object elem = __init$elem();
    private static Object __init$elem() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.elem)).apply(dictEq_0_i0))).apply(x_1_i1)); }; }; }
public static final Object elemIndex = __init$elemIndex();
    private static Object __init$elemIndex() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.elemIndex)).apply(dictEq_0_i0))).apply(x_1_i1)); }; }; }
public static final Object elemLastIndex = __init$elemLastIndex();
    private static Object __init$elemLastIndex() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.elemLastIndex)).apply(dictEq_0_i0))).apply(x_1_i1)); }; }; }
public static final Object filter = __init$filter();
    private static Object __init$filter() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.filter)).apply(f_0_i0)); }; }
public static final Object filterA = __init$filterA();
    private static Object __init$filterA() { return (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.filterA)).apply(dictApplicative_0_i0))).apply(f_1_i1)); }; }; }
public static final Object find = __init$find();
    private static Object __init$find() { return (java.util.function.Function<Object, Object>) (p_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.find)).apply(p_0_i0)); }; }
public static final Object findIndex = __init$findIndex();
    private static Object __init$findIndex() { return (java.util.function.Function<Object, Object>) (p_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.findIndex)).apply(p_0_i0)); }; }
public static final Object findLastIndex = __init$findLastIndex();
    private static Object __init$findLastIndex() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.findLastIndex)).apply(x_0_i0)); }; }
public static final Object findMap = __init$findMap();
    private static Object __init$findMap() { return (java.util.function.Function<Object, Object>) (p_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.findMap)).apply(p_0_i0)); }; }
public static final Object foldM = __init$foldM();
    private static Object __init$foldM() { return (java.util.function.Function<Object, Object>) (dictMonad_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (acc_2_i2) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.foldM)).apply(dictMonad_0_i0))).apply(f_1_i1))).apply(acc_2_i2)); }; }; }; }
public static final Object foldRecM = __init$foldRecM();
    private static Object __init$foldRecM() { return (java.util.function.Function<Object, Object>) (dictMonadRec_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (acc_2_i2) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.foldRecM)).apply(dictMonadRec_0_i0))).apply(f_1_i1))).apply(acc_2_i2)); }; }; }; }
public static final Object index = __init$index();
    private static Object __init$index() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.index))).apply(__M$Data_Array_NonEmpty.toArray); }
public static final Object length = __init$length();
    private static Object __init$length() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.length))).apply(__M$Data_Array_NonEmpty.toArray); }
public static final Object mapMaybe = __init$mapMaybe();
    private static Object __init$mapMaybe() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.mapMaybe)).apply(f_0_i0)); }; }
public static final Object notElem = __init$notElem();
    private static Object __init$notElem() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.notElem)).apply(dictEq_0_i0))).apply(x_1_i1)); }; }; }
public static final Object partition = __init$partition();
    private static Object __init$partition() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.partition)).apply(f_0_i0)); }; }
public static final Object slice = __init$slice();
    private static Object __init$slice() { return (java.util.function.Function<Object, Object>) (start_0_i0) -> { return (java.util.function.Function<Object, Object>) (end_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.slice)).apply(start_0_i0))).apply(end_1_i1)); }; }; }
public static final Object span = __init$span();
    private static Object __init$span() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.span)).apply(f_0_i0)); }; }
public static final Object take = __init$take();
    private static Object __init$take() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.take)).apply(i_0_i0)); }; }
public static final Object takeEnd = __init$takeEnd();
    private static Object __init$takeEnd() { return (java.util.function.Function<Object, Object>) (i_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.takeEnd)).apply(i_0_i0)); }; }
public static final Object takeWhile = __init$takeWhile();
    private static Object __init$takeWhile() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.adaptAny)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.takeWhile)).apply(f_0_i0)); }; }
public static final Object toUnfoldable = __init$toUnfoldable();
    private static Object __init$toUnfoldable() { return (java.util.function.Function<Object, Object>) (dictUnfoldable_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.toUnfoldable)).apply(dictUnfoldable_0_i0)))).apply(__M$Data_Array_NonEmpty.toArray); }; }
public static final Object unsafeAdapt = __init$unsafeAdapt();
    private static Object __init$unsafeAdapt() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0_i0))).apply(__M$Data_Array_NonEmpty.toArray)); }; }
public static final Object cons = __init$cons();
    private static Object __init$cons() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.cons)).apply(x_0_i0)); }; }
public static final Object group = __init$group();
    private static Object __init$group() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.group)).apply(dictEq_0_i0)); }; }
public static final Object groupAllBy = __init$groupAllBy();
    private static Object __init$groupAllBy() { return (java.util.function.Function<Object, Object>) (op_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.groupAllBy)).apply(op_0_i0)); }; }
public static final Object groupAll = __init$groupAll();
    private static Object __init$groupAll() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.groupAllBy)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(dictOrd_0_i0))); }; }
public static final Object groupBy = __init$groupBy();
    private static Object __init$groupBy() { return (java.util.function.Function<Object, Object>) (op_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.groupBy)).apply(op_0_i0)); }; }
public static final Object insert = __init$insert();
    private static Object __init$insert() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.insert)).apply(dictOrd_0_i0))).apply(x_1_i1)); }; }; }
public static final Object insertBy = __init$insertBy();
    private static Object __init$insertBy() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.insertBy)).apply(f_0_i0))).apply(x_1_i1)); }; }; }
public static final Object intersperse = __init$intersperse();
    private static Object __init$intersperse() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.intersperse)).apply(x_0_i0)); }; }
public static final Object mapWithIndex = __init$mapWithIndex();
    private static Object __init$mapWithIndex() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_FunctorWithIndex.mapWithIndex)).apply(__M$Data_FunctorWithIndex.functorWithIndexArray))).apply(f_0_i0)); }; }
public static final Object modifyAtIndices = __init$modifyAtIndices();
    private static Object __init$modifyAtIndices() { return (java.util.function.Function<Object, Object>) (dictFoldable_0_i0) -> { return (java.util.function.Function<Object, Object>) (is_1_i1) -> { return (java.util.function.Function<Object, Object>) (f_2_i2) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.modifyAtIndices)).apply(dictFoldable_0_i0))).apply(is_1_i1))).apply(f_2_i2)); }; }; }; }
public static final Object nub = __init$nub();
    private static Object __init$nub() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.nub)).apply(dictOrd_0_i0)))).apply(__M$Data_Array_NonEmpty.toArray)); }; }
public static final Object nubBy = __init$nubBy();
    private static Object __init$nubBy() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.nubBy)).apply(f_0_i0)); }; }
public static final Object nubByEq = __init$nubByEq();
    private static Object __init$nubByEq() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.nubByEq)).apply(f_0_i0)); }; }
public static final Object nubEq = __init$nubEq();
    private static Object __init$nubEq() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.nubEq)).apply(dictEq_0_i0)))).apply(__M$Data_Array_NonEmpty.toArray)); }; }
public static final Object reverse = __init$reverse();
    private static Object __init$reverse() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array.reverse))).apply(__M$Data_Array_NonEmpty.toArray)); }
public static final Object scanl = __init$scanl();
    private static Object __init$scanl() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.scanl)).apply(f_0_i0))).apply(x_1_i1)); }; }; }
public static final Object scanr = __init$scanr();
    private static Object __init$scanr() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.scanr)).apply(f_0_i0))).apply(x_1_i1)); }; }; }
public static final Object sort = __init$sort();
    private static Object __init$sort() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.unsafeFromArray))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.sort)).apply(dictOrd_0_i0)))).apply(__M$Data_Array_NonEmpty.toArray)); }; }
public static final Object sortBy = __init$sortBy();
    private static Object __init$sortBy() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.sortBy)).apply(f_0_i0)); }; }
public static final Object sortWith = __init$sortWith();
    private static Object __init$sortWith() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.sortWith)).apply(dictOrd_0_i0))).apply(f_1_i1)); }; }; }
public static final Object updateAtIndices = __init$updateAtIndices();
    private static Object __init$updateAtIndices() { return (java.util.function.Function<Object, Object>) (dictFoldable_0_i0) -> { return (java.util.function.Function<Object, Object>) (pairs_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.unsafeAdapt)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array.updateAtIndices)).apply(dictFoldable_0_i0))).apply(pairs_1_i1)); }; }; }
public static final Object unsafeIndex = __init$unsafeIndex();
    private static Object __init$unsafeIndex() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.unsafeIndex)).apply(null /* TODO: PrimUndefined */)))).apply(__M$Data_Array_NonEmpty.toArray); }; }
public static final Object toUnfoldable1 = __init$toUnfoldable1();
    private static Object __init$toUnfoldable1() { return (java.util.function.Function<Object, Object>) (dictUnfoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (xs_1_i1) -> { int len_2_i2 = ((int) (((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty.length)).apply(xs_1_i1))); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable1_0_i0).get("unfoldr1"))).apply((java.util.function.Function<Object, Object>) (i_3_i3) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array.unsafeIndex)).apply(null /* TODO: PrimUndefined */)))).apply(__M$Data_Array_NonEmpty.toArray))).apply(xs_1_i1))).apply(i_3_i3), ( ((Boolean) ((((int) (i_3_i3)) < ((int) ((((int) (len_2_i2)) - ((int) (1)))))))) ? new __M$Data_Maybe.Just((((int) (i_3_i3)) + ((int) (1)))) : __M$Data_Maybe.__singleton$Nothing.value)); }))).apply(0); }; }; }
}
