public class __M$Data_Monoid_Multiplicative {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Monoid.Multiplicative"); }
    };


public static final Object Multiplicative = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object showMultiplicative = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (((String) ((((String) ("(Multiplicative ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semigroupMultiplicative = (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemiring_0_i0).get("mul"))).apply(v_1_i1))).apply(v1_2_i2); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); };
public static final Object ordMultiplicative = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return dictOrd_0_i0; };
public static final Object monoidMultiplicative = (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> { Object semigroupMultiplicative1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Monoid_Multiplicative.semigroupMultiplicative)).apply(dictSemiring_0_i0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictSemiring_0_i0).get("one"); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i2) -> { return semigroupMultiplicative1_1_i1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); };
public static final Object functorMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (m_1_i1) -> { return ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(m_1_i1); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get();
public static final Object eqMultiplicative = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return dictEq_0_i0; };
public static final Object eq1Multiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0_i0); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get();
public static final Object ord1Multiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(dictOrd_0_i0); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> { return __M$Data_Monoid_Multiplicative.eq1Multiplicative; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get();
public static final Object boundedMultiplicative = (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> { return dictBounded_0_i0; };
public static final Object applyMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ((java.util.function.Function<Object, Object>) (v_0_i0)).apply(v1_1_i1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Monoid_Multiplicative.functorMultiplicative; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get();
public static final Object bindMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(v_0_i0); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Monoid_Multiplicative.applyMultiplicative; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get();
public static final Object applicativeMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Monoid_Multiplicative.Multiplicative; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Monoid_Multiplicative.applyMultiplicative; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get();
public static final Object monadMultiplicative = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Monoid_Multiplicative.applicativeMultiplicative; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> { return __M$Data_Monoid_Multiplicative.bindMultiplicative; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get();
}
