public class __M$Data_Bifunctor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Bifunctor"); }
    };


public static final Object bimap = __init$bimap();
    private static Object __init$bimap() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("bimap"); }; }
public static final Object bivoid = __init$bivoid();
    private static Object __init$bivoid() { return (java.util.function.Function<Object, Object>) (dictBifunctor_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0$r0).get("bimap"))).apply((java.util.function.Function<Object, Object>) (v_1$r1) -> { return __M$Data_Unit.unit; }))).apply((java.util.function.Function<Object, Object>) (v_1$r2) -> { return __M$Data_Unit.unit; }); }; }
public static final Object lmap = __init$lmap();
    private static Object __init$lmap() { return (java.util.function.Function<Object, Object>) (dictBifunctor_0$r0) -> { return (java.util.function.Function<Object, Object>) (f_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0$r0).get("bimap"))).apply(f_1$r1))).apply((java.util.function.Function<Object, Object>) (x_2$r2) -> { return x_2$r2; }); }; }; }
public static final Object rmap = __init$rmap();
    private static Object __init$rmap() { return (java.util.function.Function<Object, Object>) (dictBifunctor_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0$r0).get("bimap"))).apply((java.util.function.Function<Object, Object>) (x_1$r1) -> { return x_1$r1; }); }; }
public static final Object bifunctorTuple = __init$bifunctorTuple();
    private static Object __init$bifunctorTuple() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (g_1$r1) -> { return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_0$r0)).apply(((__M$Data_Tuple.Tuple) (Object)(v_2$r2)).value0), ((java.util.function.Function<Object, Object>) (g_1$r1)).apply(((__M$Data_Tuple.Tuple) (Object)(v_2$r2)).value1)); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); }
public static final Object bifunctorEither = __init$bifunctorEither();
    private static Object __init$bifunctorEither() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (java.util.function.Function<Object, Object>) (v2_2$r2) -> { return ( ((Boolean) ((((Object) (v2_2$r2)) instanceof __M$Data_Either.Left))) ? new __M$Data_Either.Left(((java.util.function.Function<Object, Object>) (v_0$r0)).apply(((__M$Data_Either.Left) (Object)(v2_2$r2)).value0)) : ( ((Boolean) ((((Object) (v2_2$r2)) instanceof __M$Data_Either.Right))) ? new __M$Data_Either.Right(((java.util.function.Function<Object, Object>) (v1_1$r1)).apply(((__M$Data_Either.Right) (Object)(v2_2$r2)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); }
public static final Object bifunctorConst = __init$bifunctorConst();
    private static Object __init$bifunctorConst() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (v1_2$r2) -> { return ((java.util.function.Function<Object, Object>) (f_0$r0)).apply(v1_2$r2); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); }
}
