public class __M$Data_Ring_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ring.Generic"); }
    };


public static final Object genericSubprime = __init$genericSubprime();
    private static Object __init$genericSubprime() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("genericSub'"); }; }
public static final Object genericSub = __init$genericSub();
    private static Object __init$genericSub() { return (java.util.function.Function<Object, Object>) (dictGeneric_0$r0) -> { Object to_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Generic_Rep.to)).apply(dictGeneric_0$r0); return (java.util.function.Function<Object, Object>) (dictGenericRing_2$r2) -> { return (java.util.function.Function<Object, Object>) (x_3$r3) -> { return (java.util.function.Function<Object, Object>) (y_4$r4) -> { return ((java.util.function.Function<Object, Object>) (to_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing_2$r2).get("genericSub'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("from"))).apply(x_3$r3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("from"))).apply(y_4$r4))); }; }; }; }; }
public static final Object genericRingProduct = __init$genericRingProduct();
    private static Object __init$genericRingProduct() { return (java.util.function.Function<Object, Object>) (dictGenericRing_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictGenericRing1_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (v1_3$r3) -> { return new __M$Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing_0$r0).get("genericSub'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r2)).value0))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3$r3)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing1_1$r1).get("genericSub'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r2)).value1))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3$r3)).value1)); }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get(); }; }; }
public static final Object genericRingNoArguments = __init$genericRingNoArguments();
    private static Object __init$genericRingNoArguments() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return __M$Data_Generic_Rep.__singleton$NoArguments.value; }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get(); }
public static final Object genericRingConstructor = __init$genericRingConstructor();
    private static Object __init$genericRingConstructor() { return (java.util.function.Function<Object, Object>) (dictGenericRing_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (v1_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericRing_0$r0).get("genericSub'"))).apply(v_1$r1))).apply(v1_2$r2); }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get(); }; }
public static final Object genericRingArgument = __init$genericRingArgument();
    private static Object __init$genericRingArgument() { return (java.util.function.Function<Object, Object>) (dictRing_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (v1_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictRing_0$r0).get("sub"))).apply(v_1$r1))).apply(v1_2$r2); }; }; return new __Record$67_65_6e_65_72_69_63_53_75_62_27_O(new String[]{"genericSub'"}, __field0); } }).get(); }; }
}
