public class __M$Control_Monad_RWS {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Monad.RWS"); }
    };


public static final Object withRWS = __init$withRWS();
    private static Object __init$withRWS() { return __M$Control_Monad_RWS_Trans.withRWST; }
public static final Object rws = __init$rws();
    private static Object __init$rws() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (r_1$r1) -> { return (java.util.function.Function<Object, Object>) (s_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0$r0)).apply(r_1$r1))).apply(s_2$r2); }; }; }; }
public static final Object runRWS = __init$runRWS();
    private static Object __init$runRWS() { return (java.util.function.Function<Object, Object>) (m_0$r0) -> { return (java.util.function.Function<Object, Object>) (r_1$r1) -> { return (java.util.function.Function<Object, Object>) (s_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0$r0)).apply(r_1$r1))).apply(s_2$r2); }; }; }; }
public static final Object mapRWS = __init$mapRWS();
    private static Object __init$mapRWS() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { Object __local_var_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0$r0))).apply(__M$Data_Identity.Identity)); return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (r_3$r3) -> { return (java.util.function.Function<Object, Object>) (s_4$r4) -> { return ((java.util.function.Function<Object, Object>) (__local_var_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_2$r2)).apply(r_3$r3))).apply(s_4$r4)); }; }; }; }; }
public static final Object execRWS = __init$execRWS();
    private static Object __init$execRWS() { return (java.util.function.Function<Object, Object>) (m_0$r0) -> { return (java.util.function.Function<Object, Object>) (r_1$r1) -> { return (java.util.function.Function<Object, Object>) (s_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0$r0)).apply(r_1$r1))).apply(s_2$r2); return new __M$Data_Tuple.Tuple(((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3$r3)).value0, ((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3$r3)).value2); } }).get()); }; }; }; }
public static final Object evalRWS = __init$evalRWS();
    private static Object __init$evalRWS() { return (java.util.function.Function<Object, Object>) (m_0$r0) -> { return (java.util.function.Function<Object, Object>) (r_1$r1) -> { return (java.util.function.Function<Object, Object>) (s_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (m_0$r0)).apply(r_1$r1))).apply(s_2$r2); return new __M$Data_Tuple.Tuple(((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3$r3)).value1, ((__M$Control_Monad_RWS_Trans.RWSResult) (Object)(__local_var_3$r3)).value2); } }).get()); }; }; }; }
}
