public class __M$Data_Array_ST_Iterator {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Array.ST.Iterator"); }
    };


public static final class Iterator {
            public final Object value0;
            public final Object value1;
            public Iterator(Object value0, Object value1){
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object Iterator = __init$Iterator();
    private static Object __init$Iterator() { return (java.util.function.Function<Object, Object>) (value0_i0) -> (java.util.function.Function<Object, Object>) (value1_i1) -> { return new __M$Data_Array_ST_Iterator.Iterator(value0_i0, value1_i1); }; }
public static final Object peek = __init$peek();
    private static Object __init$peek() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1_i1 = ((__M$Data_Array_ST_Iterator.Iterator) (Object)(v_0_i0)).value1; Object i_2_i2 = ((Object[]) (__local_var_1_i1))[((int) (0))]; return ((java.util.function.Function<Object, Object>) (((__M$Data_Array_ST_Iterator.Iterator) (Object)(v_0_i0)).value0)).apply(i_2_i2); } }); }; }
public static final Object next = __init$next();
    private static Object __init$next() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1_i1 = ((__M$Data_Array_ST_Iterator.Iterator) (Object)(v_0_i0)).value1; Object i_2_i2 = ((Object[]) (__local_var_1_i1))[((int) (0))]; Object _dollar___unused_3_i3 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Monad_ST_Internal.modifyImpl)).apply((java.util.function.Function<Object, Object>) (s_3_i4) -> { Object s_prime__4_i5 = (((int) (s_3_i4)) + ((int) (1))); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = s_prime__4_i5; final Object __field1 = s_prime__4_i5; return new __Record$73_74_61_74_65_O$76_61_6c_75_65_O(new String[]{"state", "value"}, __field0, __field1); } }).get(); }))).apply(__local_var_1_i1))).get(); return ((java.util.function.Function<Object, Object>) (((__M$Data_Array_ST_Iterator.Iterator) (Object)(v_0_i0)).value0)).apply(i_2_i2); } }); }; }
public static final Object pushWhile = __init$pushWhile();
    private static Object __init$pushWhile() { return (java.util.function.Function<Object, Object>) (p_0_i0) -> { return (java.util.function.Function<Object, Object>) (iter_1_i1) -> { return (java.util.function.Function<Object, Object>) (array_2_i2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object go__break_3_i3 = new Object[]{false}; return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Monad_ST_Internal.$while)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4_i4 = ((java.util.function.Function<Object, Object>) (__M$Data_HeytingAlgebra.not)).apply(__M$Data_HeytingAlgebra.heytingAlgebraBoolean); Object __local_var_5_i5 = ((Object[]) (go__break_3_i3))[((int) (0))]; return ((java.util.function.Function<Object, Object>) (__local_var_4_i4)).apply(__local_var_5_i5); } })))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4_i6 = ((__M$Data_Array_ST_Iterator.Iterator) (Object)(iter_1_i1)).value1; Object mx_5_i7 = (new java.util.function.Supplier<Object>() { public Object get() { Object i_5_i8 = ((Object[]) (__local_var_4_i6))[((int) (0))]; return ((java.util.function.Function<Object, Object>) (((__M$Data_Array_ST_Iterator.Iterator) (Object)(iter_1_i1)).value0)).apply(i_5_i8); } }).get(); return ((java.util.function.Supplier) (Object)(( ((Boolean) ((((Boolean) ((((Object) (mx_5_i7)) instanceof __M$Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (p_0_i0)).apply(((__M$Data_Maybe.Just) (Object)(mx_5_i7)).value0)))))) ? (new java.util.function.Supplier<Object>() { public Object get() { Object _dollar___unused_6_i9 = ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array_ST.push)).apply(((__M$Data_Maybe.Just) (Object)(mx_5_i7)).value0))).apply(array_2_i2))).get(); return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor.$void)).apply(__M$Control_Monad_ST_Internal.functorST))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Array_ST_Iterator.next)).apply(iter_1_i1)))).get(); } }) : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor.$void)).apply(__M$Control_Monad_ST_Internal.functorST))).apply((new java.util.function.Supplier<Object>() { public Object get() { ((Object[]) (go__break_3_i3))[((int) (0))] = true; return true; } }))))).get(); } })))).get(); } }); }; }; }; }
public static final Object pushAll = __init$pushAll();
    private static Object __init$pushAll() { return ((java.util.function.Function<Object, Object>) (__M$Data_Array_ST_Iterator.pushWhile)).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return true; }); }
public static final Object iterator = __init$iterator();
    private static Object __init$iterator() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Array_ST_Iterator.Iterator)).apply(f_0_i0); Object __local_var_2_i2 = new Object[]{0}; return ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(__local_var_2_i2); } }); }; }
public static final Object iterate = __init$iterate();
    private static Object __init$iterate() { return (java.util.function.Function<Object, Object>) (iter_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object go__break_2_i2 = new Object[]{false}; return ((java.util.function.Supplier) (Object)(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Monad_ST_Internal.$while)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Data_HeytingAlgebra.not)).apply(__M$Data_HeytingAlgebra.heytingAlgebraBoolean); Object __local_var_4_i4 = ((Object[]) (go__break_2_i2))[((int) (0))]; return ((java.util.function.Function<Object, Object>) (__local_var_3_i3)).apply(__local_var_4_i4); } })))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3_i5 = ((java.util.function.Function<Object, Object>) (__M$Data_Array_ST_Iterator.next)).apply(iter_0_i0); Object mx_4_i6 = ((java.util.function.Supplier) (Object)(__local_var_3_i5)).get(); return ((java.util.function.Supplier) (Object)(( ((Boolean) ((((Object) (mx_4_i6)) instanceof __M$Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(((__M$Data_Maybe.Just) (Object)(mx_4_i6)).value0) : ( ((Boolean) ((((Object) (mx_4_i6)) instanceof __M$Data_Maybe.Nothing))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor.$void)).apply(__M$Control_Monad_ST_Internal.functorST))).apply((new java.util.function.Supplier<Object>() { public Object get() { ((Object[]) (go__break_2_i2))[((int) (0))] = true; return true; } })) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())))).get(); } })))).get(); } }); }; }; }
public static final Object exhausted = __init$exhausted();
    private static Object __init$exhausted() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (__local_var_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1_i1 = ((java.util.function.Supplier) (Object)(__local_var_0_i0)).get(); return ((java.util.function.Function<Object, Object>) (__M$Data_Maybe.isNothing)).apply(__local_var_1_i1); } }); }))).apply(__M$Data_Array_ST_Iterator.peek); }
}
