public class __M$Record {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Record"); }
    };


public static final Object union = __init$union();
    private static Object __init$union() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return (java.util.function.Function<Object, Object>) (l_1$r1) -> { return (java.util.function.Function<Object, Object>) (r_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe_Union.unsafeUnionFn)).apply(l_1$r1))).apply(r_2$r2); }; }; }; }
public static final Object set = __init$set();
    private static Object __init$set() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return (java.util.function.Function<Object, Object>) (l_3$r3) -> { return (java.util.function.Function<Object, Object>) (b_4$r4) -> { return (java.util.function.Function<Object, Object>) (r_5$r5) -> { return __M$Record.__direct$1(dictIsSymbol_0$r0, _dollar___unused_1$r1, _dollar___unused_2$r2, l_3$r3, b_4$r4, r_5$r5); }; }; }; }; }; }; }
private static Object __direct$1(Object dictIsSymbol_0$r0, Object _dollar___unused_1$r1, Object _dollar___unused_2$r2, Object l_3$r3, Object b_4$r4, Object r_5$r5) { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeSet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(l_3$r3)))).apply(b_4$r4))).apply(r_5$r5); }
public static final Object nub = __init$nub();
    private static Object __init$nub() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Unsafe_Coerce.unsafeCoerce; }; }
public static final Object merge = __init$merge();
    private static Object __init$merge() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (l_2$r2) -> { return (java.util.function.Function<Object, Object>) (r_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe_Union.unsafeUnionFn)).apply(l_2$r2))).apply(r_3$r3); }; }; }; }; }
public static final Object insert = __init$insert();
    private static Object __init$insert() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return (java.util.function.Function<Object, Object>) (l_3$r3) -> { return (java.util.function.Function<Object, Object>) (a_4$r4) -> { return (java.util.function.Function<Object, Object>) (r_5$r5) -> { return __M$Record.__direct$4(dictIsSymbol_0$r0, _dollar___unused_1$r1, _dollar___unused_2$r2, l_3$r3, a_4$r4, r_5$r5); }; }; }; }; }; }; }
private static Object __direct$4(Object dictIsSymbol_0$r0, Object _dollar___unused_1$r1, Object _dollar___unused_2$r2, Object l_3$r3, Object a_4$r4, Object r_5$r5) { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeSet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(l_3$r3)))).apply(a_4$r4))).apply(r_5$r5); }
public static final Object get = __init$get();
    private static Object __init$get() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (l_2$r2) -> { return (java.util.function.Function<Object, Object>) (r_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(l_2$r2)))).apply(r_3$r3); }; }; }; }; }
public static final Object modify = __init$modify();
    private static Object __init$modify() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return (java.util.function.Function<Object, Object>) (l_3$r3) -> { return (java.util.function.Function<Object, Object>) (f_4$r4) -> { return (java.util.function.Function<Object, Object>) (r_5$r5) -> { return __M$Record.__direct$1(dictIsSymbol_0$r0, null /* TODO: PrimUndefined */, null /* TODO: PrimUndefined */, l_3$r3, ((java.util.function.Function<Object, Object>) (f_4$r4)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(l_3$r3)))).apply(r_5$r5)), r_5$r5); }; }; }; }; }; }; }
public static final Object equalFieldsNil = __init$equalFieldsNil();
    private static Object __init$equalFieldsNil() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (java.util.function.Function<Object, Object>) (v2_2$r2) -> { return true; }; }; }; return new __Record$65_71_75_61_6c_46_69_65_6c_64_73_O(new String[]{"equalFields"}, __field0); } }).get(); }
public static final Object equalFields = __init$equalFields();
    private static Object __init$equalFields() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("equalFields"); }; }
public static final Object equalFieldsCons = __init$equalFieldsCons();
    private static Object __init$equalFieldsCons() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictEq_1$r1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return (java.util.function.Function<Object, Object>) (dictEqualFields_3$r3) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_4$r4) -> { return (java.util.function.Function<Object, Object>) (a_5$r5) -> { return (java.util.function.Function<Object, Object>) (b_6$r6) -> { return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_1$r1).get("eq"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value)))).apply(a_5$r5)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value)))).apply(b_6$r6)))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEqualFields_3$r3).get("equalFields"))).apply(__M$Type_Proxy.__singleton$Proxy.value))).apply(a_5$r5))).apply(b_6$r6)))); }; }; }; return new __Record$65_71_75_61_6c_46_69_65_6c_64_73_O(new String[]{"equalFields"}, __field0); } }).get(); }; }; }; }; }
public static final Object equal = __init$equal();
    private static Object __init$equal() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictEqualFields_1$r1) -> { return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return (java.util.function.Function<Object, Object>) (b_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEqualFields_1$r1).get("equalFields"))).apply(__M$Type_Proxy.__singleton$Proxy.value))).apply(a_2$r2))).apply(b_3$r3); }; }; }; }; }
public static final Object disjointUnion = __init$disjointUnion();
    private static Object __init$disjointUnion() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (l_2$r2) -> { return (java.util.function.Function<Object, Object>) (r_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe_Union.unsafeUnionFn)).apply(l_2$r2))).apply(r_3$r3); }; }; }; }; }
public static final Object delete = __init$delete();
    private static Object __init$delete() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return (java.util.function.Function<Object, Object>) (l_3$r3) -> { return (java.util.function.Function<Object, Object>) (r_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeDelete)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(l_3$r3)))).apply(r_4$r4); }; }; }; }; }; }
public static final Object rename = __init$rename();
    private static Object __init$rename() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictIsSymbol1_1$r1) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_3$r3) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_4$r4) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_5$r5) -> { return (java.util.function.Function<Object, Object>) (prev_6$r6) -> { return (java.util.function.Function<Object, Object>) (next_7$r7) -> { return (java.util.function.Function<Object, Object>) (record_8$r8) -> { return __M$Record.__direct$4(dictIsSymbol1_1$r1, null /* TODO: PrimUndefined */, null /* TODO: PrimUndefined */, next_7$r7, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(prev_6$r6)))).apply(record_8$r8), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeDelete)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(prev_6$r6)))).apply(record_8$r8)); }; }; }; }; }; }; }; }; }; }
}
