public class __M$Data_Functor_Flip {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Flip"); }
    };


public static final Object Flip = __init$Flip();
    private static Object __init$Flip() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; }; }
public static final Object showFlip = __init$showFlip();
    private static Object __init$showFlip() { return (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (((String) ((((String) ("(Flip ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object semigroupoidFlip = __init$semigroupoidFlip();
    private static Object __init$semigroupoidFlip() { return (java.util.function.Function<Object, Object>) (dictSemigroupoid_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(dictSemigroupoid_0_i0))).apply(v1_2_i2))).apply(v_1_i1); }; }; return new __Record$63_6f_6d_70_6f_73_65_O(new String[]{"compose"}, __field0); } }).get(); }; }
public static final Object ordFlip = __init$ordFlip();
    private static Object __init$ordFlip() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return dictOrd_0_i0; }; }
public static final Object newtypeFlip = __init$newtypeFlip();
    private static Object __init$newtypeFlip() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object functorFlip = __init$functorFlip();
    private static Object __init$functorFlip() { return (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply(f_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn)))).apply(v_2_i2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }; }
public static final Object eqFlip = __init$eqFlip();
    private static Object __init$eqFlip() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return dictEq_0_i0; }; }
public static final Object contravariantFlip = __init$contravariantFlip();
    private static Object __init$contravariantFlip() { return (java.util.function.Function<Object, Object>) (dictProfunctor_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictProfunctor_0_i0).get("dimap"))).apply(f_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn)))).apply(v_2_i2); }; }; return new __Record$63_6d_61_70_O(new String[]{"cmap"}, __field0); } }).get(); }; }
public static final Object categoryFlip = __init$categoryFlip();
    private static Object __init$categoryFlip() { return (java.util.function.Function<Object, Object>) (dictCategory_0_i0) -> { Object semigroupoidFlip1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Flip.semigroupoidFlip)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCategory_0_i0).get("Semigroupoid0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(dictCategory_0_i0); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i2) -> { return semigroupoidFlip1_1_i1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_6f_69_64_30_O$69_64_65_6e_74_69_74_79_O(new String[]{"identity", "Semigroupoid0"}, __field1, __field0); } }).get(); }; }
public static final Object bifunctorFlip = __init$bifunctorFlip();
    private static Object __init$bifunctorFlip() { return (java.util.function.Function<Object, Object>) (dictBifunctor_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (g_2_i2) -> { return (java.util.function.Function<Object, Object>) (v_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBifunctor_0_i0).get("bimap"))).apply(g_2_i2))).apply(f_1_i1))).apply(v_3_i3); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); }; }
public static final Object biapplyFlip = __init$biapplyFlip();
    private static Object __init$biapplyFlip() { return (java.util.function.Function<Object, Object>) (dictBiapply_0_i0) -> { Object bifunctorFlip1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Flip.bifunctorFlip)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0_i0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapply_0_i0).get("biapply"))).apply(v_2_i2))).apply(v1_3_i3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return bifunctorFlip1_1_i1; }; return new __Record$42_69_66_75_6e_63_74_6f_72_30_O$62_69_61_70_70_6c_79_O(new String[]{"biapply", "Bifunctor0"}, __field1, __field0); } }).get(); }; }
public static final Object biapplicativeFlip = __init$biapplicativeFlip();
    private static Object __init$biapplicativeFlip() { return (java.util.function.Function<Object, Object>) (dictBiapplicative_0_i0) -> { Object biapplyFlip1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Flip.biapplyFlip)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0_i0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_2_i2) -> { return (java.util.function.Function<Object, Object>) (b_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBiapplicative_0_i0).get("bipure"))).apply(b_3_i3))).apply(a_2_i2); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return biapplyFlip1_1_i1; }; return new __Record$42_69_61_70_70_6c_79_30_O$62_69_70_75_72_65_O(new String[]{"bipure", "Biapply0"}, __field1, __field0); } }).get(); }; }
}
