public class __M$Data_Monoid {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Monoid"); }
    };


public static final Object monoidUnit = __init$monoidUnit();
    private static Object __init$monoidUnit() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Unit.unit; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Semigroup.semigroupUnit; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object monoidString = __init$monoidString();
    private static Object __init$monoidString() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ""; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Semigroup.semigroupString; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object monoidRecordNil = __init$monoidRecordNil();
    private static Object __init$monoidRecordNil() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { return new __Record$(new String[]{}); } }).get(); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r1) -> { return __M$Data_Semigroup.semigroupRecordNil; }; return new __Record$53_65_6d_69_67_72_6f_75_70_52_65_63_6f_72_64_30_O$6d_65_6d_70_74_79_52_65_63_6f_72_64_O(new String[]{"memptyRecord", "SemigroupRecord0"}, __field1, __field0); } }).get(); }
public static final Object monoidOrdering = __init$monoidOrdering();
    private static Object __init$monoidOrdering() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Ordering.__singleton$EQ.value; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Ordering.semigroupOrdering; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object monoidArray = __init$monoidArray();
    private static Object __init$monoidArray() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new Object[]{}; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Semigroup.semigroupArray; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }
public static final Object memptyRecord = __init$memptyRecord();
    private static Object __init$memptyRecord() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("memptyRecord"); }; }
public static final Object monoidRecord = __init$monoidRecord();
    private static Object __init$monoidRecord() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictMonoidRecord_1$r1) -> { Object semigroupRecord1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.semigroupRecord)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoidRecord_1$r1).get("SemigroupRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoidRecord_1$r1).get("memptyRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r3) -> { return semigroupRecord1_2$r2; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_R(new String[]{"mempty", "Semigroup0"}, __field1, ((java.util.Map<String, Object>) (__field0))); } }).get(); }; }; }
public static final Object mempty = __init$mempty();
    private static Object __init$mempty() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("mempty"); }; }
public static final Object monoidFn = __init$monoidFn();
    private static Object __init$monoidFn() { return (java.util.function.Function<Object, Object>) (dictMonoid_0$r0) -> { Object semigroupFn_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.semigroupFn)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_0$r0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ((java.util.Map<String, Object>) dictMonoid_0$r0).get("mempty"); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r3) -> { return semigroupFn_1$r1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }; }
public static final Object monoidRecordCons = __init$monoidRecordCons();
    private static Object __init$monoidRecordCons() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictMonoid_1$r1) -> { Object mempty1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Monoid.mempty)).apply(dictMonoid_1$r1); Object Semigroup0_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_1$r1).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (_dollar___unused_4$r4) -> { return (java.util.function.Function<Object, Object>) (dictMonoidRecord_5$r5) -> { Object semigroupRecordCons1_6$r6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.semigroupRecordCons)).apply(dictIsSymbol_0$r0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoidRecord_5$r5).get("SemigroupRecord0"))).apply(null /* TODO: PrimUndefined */)))).apply(Semigroup0_3$r3); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_7$r7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Record_Unsafe.unsafeSet)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_0$r0).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value)))).apply(mempty1_2$r2))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoidRecord_5$r5).get("memptyRecord"))).apply(__M$Type_Proxy.__singleton$Proxy.value)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_7$r8) -> { return semigroupRecordCons1_6$r6; }; return new __Record$53_65_6d_69_67_72_6f_75_70_52_65_63_6f_72_64_30_O$6d_65_6d_70_74_79_52_65_63_6f_72_64_O(new String[]{"memptyRecord", "SemigroupRecord0"}, __field1, __field0); } }).get(); }; }; }; }; }
public static final Object power = __init$power();
    private static Object __init$power() { return (java.util.function.Function<Object, Object>) (dictMonoid_0$r0) -> { Object mempty1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Monoid.mempty)).apply(dictMonoid_0$r0); Object Semigroup0_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_0$r0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (x_3$r3) -> { return (new java.util.function.Supplier<Object>() { public Object get() { class LetRecScope_go__go_4$r4 { Object go__go_4$r4; LetRecScope_go__go_4$r4() { go__go_4$r4 = (java.util.function.Function<Object, Object>) (p_5$r5) -> { if ((Boolean) ((((int) (p_5$r5)) <= ((int) (0))))) { return mempty1_1$r1; } else { if ((Boolean) ((((int) (p_5$r5)) == ((int) (1))))) { return x_3$r3; } else { {  if ((Boolean) ((((int) ((new java.util.function.Supplier<Object>() { public Object get() { Object __mod_l$r6 = p_5$r5; Object __mod_r$r7 = 2; return (((Integer) __mod_r$r7) == 0 ? 0 : (int) Math.floorMod((long) ((Integer) __mod_l$r6), Math.abs((long) ((Integer) __mod_r$r7)))); } }).get())) == ((int) (0))))) { { Object x_prime__6$r8 = ((java.util.function.Function<Object, Object>) (go__go_4$r4)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __div_l$r9 = p_5$r5; Object __div_r$r10 = 2; return (((Integer) __div_r$r10) == 0 ? 0 : (((Integer) __div_r$r10) > 0 ? (int) Math.floor((double) ((Integer) __div_l$r9) / ((Integer) __div_r$r10)) : -(int) Math.floor((double) ((Integer) __div_l$r9) / -((double) ((Integer) __div_r$r10))))); } }).get()); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semigroup0_2$r2).get("append"))).apply(x_prime__6$r8))).apply(x_prime__6$r8); } } else { { Object x_prime__6$r11 = ((java.util.function.Function<Object, Object>) (go__go_4$r4)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __div_l$r12 = p_5$r5; Object __div_r$r13 = 2; return (((Integer) __div_r$r13) == 0 ? 0 : (((Integer) __div_r$r13) > 0 ? (int) Math.floor((double) ((Integer) __div_l$r12) / ((Integer) __div_r$r13)) : -(int) Math.floor((double) ((Integer) __div_l$r12) / -((double) ((Integer) __div_r$r13))))); } }).get()); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semigroup0_2$r2).get("append"))).apply(x_prime__6$r11))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semigroup0_2$r2).get("append"))).apply(x_prime__6$r11))).apply(x_3$r3)); } } } } }  }; } } LetRecScope_go__go_4$r4 __letrec_go__go_4$r4 = new LetRecScope_go__go_4$r4(); Object go__go_4$r4 = __letrec_go__go_4$r4.go__go_4$r4; return go__go_4$r4; } }).get(); }; }; }
public static final Object guard = __init$guard();
    private static Object __init$guard() { return (java.util.function.Function<Object, Object>) (dictMonoid_0$r0) -> { Object mempty1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Monoid.mempty)).apply(dictMonoid_0$r0); return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (v1_3$r3) -> { return ( ((Boolean) (v_2$r2)) ? v1_3$r3 : mempty1_1$r1); }; }; }; }
}
