public class __M$Control_Comonad_Traced_Trans {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Comonad.Traced.Trans"); }
    };


public static final Object TracedT = __init$TracedT();
    private static Object __init$TracedT() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; }; }
public static final Object runTracedT = __init$runTracedT();
    private static Object __init$runTracedT() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return v_0_i0; }; }
public static final Object newtypeTracedT = __init$newtypeTracedT();
    private static Object __init$newtypeTracedT() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object functorTracedT = __init$functorTracedT();
    private static Object __init$functorTracedT() { return (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply((java.util.function.Function<Object, Object>) (g_3_i3) -> { return (java.util.function.Function<Object, Object>) (t_4_i4) -> { return ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(((java.util.function.Function<Object, Object>) (g_3_i3)).apply(t_4_i4)); }; }))).apply(v_2_i2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }; }
public static final Object extendTracedT = __init$extendTracedT();
    private static Object __init$extendTracedT() { return (java.util.function.Function<Object, Object>) (dictExtend_0_i0) -> { Object Functor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object functorTracedT1_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Trans.functorTracedT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictSemigroup_3_i3) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_4_i4) -> { return (java.util.function.Function<Object, Object>) (v_5_i5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0_i0).get("extend"))).apply((java.util.function.Function<Object, Object>) (w_prime__6_i6) -> { return (java.util.function.Function<Object, Object>) (t_7_i7) -> { return ((java.util.function.Function<Object, Object>) (f_4_i4)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1_i1).get("map"))).apply((java.util.function.Function<Object, Object>) (h_8_i8) -> { return (java.util.function.Function<Object, Object>) (t_prime__9_i9) -> { return ((java.util.function.Function<Object, Object>) (h_8_i8)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_3_i3).get("append"))).apply(t_7_i7))).apply(t_prime__9_i9)); }; }))).apply(w_prime__6_i6)); }; }))).apply(v_5_i5); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4_i10) -> { return functorTracedT1_2_i2; }; return new __Record$46_75_6e_63_74_6f_72_30_O$65_78_74_65_6e_64_O(new String[]{"extend", "Functor0"}, __field1, __field0); } }).get(); }; }; }
public static final Object comonadTransTracedT = __init$comonadTransTracedT();
    private static Object __init$comonadTransTracedT() { return (java.util.function.Function<Object, Object>) (dictMonoid_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictComonad_1_i1) -> { Object Functor0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_1_i1).get("Extend0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (v_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_2_i2).get("map"))).apply((java.util.function.Function<Object, Object>) (f_4_i4) -> { return ((java.util.function.Function<Object, Object>) (f_4_i4)).apply(((java.util.Map<String, Object>) dictMonoid_0_i0).get("mempty")); }))).apply(v_3_i3); }; }; return new __Record$6c_6f_77_65_72_O(new String[]{"lower"}, __field0); } }).get(); }; }
public static final Object comonadTracedT = __init$comonadTracedT();
    private static Object __init$comonadTracedT() { return (java.util.function.Function<Object, Object>) (dictComonad_0_i0) -> { Object extendTracedT1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Trans.extendTracedT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_0_i0).get("Extend0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictMonoid_2_i2) -> { Object extendTracedT2_3_i3 = ((java.util.function.Function<Object, Object>) (extendTracedT1_1_i1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_2_i2).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_0_i0).get("extract"))).apply(v_4_i4))).apply(((java.util.Map<String, Object>) dictMonoid_2_i2).get("mempty")); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4_i5) -> { return extendTracedT2_3_i3; }; return new __Record$45_78_74_65_6e_64_30_O$65_78_74_72_61_63_74_O(new String[]{"extract", "Extend0"}, __field1, __field0); } }).get(); }; }; }
}
