public class __M$Data_Eq_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Eq.Generic"); }
    };


public static final Object genericEqNoConstructors = __init$genericEqNoConstructors();
    private static Object __init$genericEqNoConstructors() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return true; }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }
public static final Object genericEqNoArguments = __init$genericEqNoArguments();
    private static Object __init$genericEqNoArguments() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return true; }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }
public static final Object genericEqArgument = __init$genericEqArgument();
    private static Object __init$genericEqArgument() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0_i0).get("eq"))).apply(v_1_i1))).apply(v1_2_i2); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }; }
public static final Object genericEqprime = __init$genericEqprime();
    private static Object __init$genericEqprime() { return (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("genericEq'"); }; }
public static final Object genericEqConstructor = __init$genericEqConstructor();
    private static Object __init$genericEqConstructor() { return (java.util.function.Function<Object, Object>) (dictGenericEq_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_0_i0).get("genericEq'"))).apply(v_1_i1))).apply(v1_2_i2); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }; }
public static final Object genericEqProduct = __init$genericEqProduct();
    private static Object __init$genericEqProduct() { return (java.util.function.Function<Object, Object>) (dictGenericEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictGenericEq1_1_i1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_0_i0).get("genericEq'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2_i2)).value0))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3_i3)).value0))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq1_1_i1).get("genericEq'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2_i2)).value1))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3_i3)).value1)))); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }; }; }
public static final Object genericEqSum = __init$genericEqSum();
    private static Object __init$genericEqSum() { return (java.util.function.Function<Object, Object>) (dictGenericEq_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictGenericEq1_1_i1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return ( ((Boolean) ((((Object) (v_2_i2)) instanceof __M$Data_Generic_Rep.Inl))) ? (((Boolean) ((((Object) (v1_3_i3)) instanceof __M$Data_Generic_Rep.Inl))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_0_i0).get("genericEq'"))).apply(((__M$Data_Generic_Rep.Inl) (Object)(v_2_i2)).value0))).apply(((__M$Data_Generic_Rep.Inl) (Object)(v1_3_i3)).value0)))) : (((Boolean) ((((Object) (v_2_i2)) instanceof __M$Data_Generic_Rep.Inr))) && ((Boolean) ((((Boolean) ((((Object) (v1_3_i3)) instanceof __M$Data_Generic_Rep.Inr))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq1_1_i1).get("genericEq'"))).apply(((__M$Data_Generic_Rep.Inr) (Object)(v_2_i2)).value0))).apply(((__M$Data_Generic_Rep.Inr) (Object)(v1_3_i3)).value0)))))))); }; }; return new __Record$67_65_6e_65_72_69_63_45_71_27_O(new String[]{"genericEq'"}, __field0); } }).get(); }; }; }
public static final Object genericEq = __init$genericEq();
    private static Object __init$genericEq() { return (java.util.function.Function<Object, Object>) (dictGeneric_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictGenericEq_1_i1) -> { return (java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericEq_1_i1).get("genericEq'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0_i0).get("from"))).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0_i0).get("from"))).apply(y_3_i3)); }; }; }; }; }
}
