public class __M$Data_Functor_Product_Nested {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Product.Nested"); }
    };


public static final Object product9 = __init$product9();
    private static Object __init$product9() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return (java.util.function.Function<Object, Object>) (d_3_i3) -> { return (java.util.function.Function<Object, Object>) (e_4_i4) -> { return (java.util.function.Function<Object, Object>) (f_5_i5) -> { return (java.util.function.Function<Object, Object>) (g_6_i6) -> { return (java.util.function.Function<Object, Object>) (h_7_i7) -> { return (java.util.function.Function<Object, Object>) (i_8_i8) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(d_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(e_4_i4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(f_5_i5))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(g_6_i6))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(h_7_i7))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(i_8_i8))).apply(__M$Data_Unit.unit))))))))); }; }; }; }; }; }; }; }; }; }
public static final Object product8 = __init$product8();
    private static Object __init$product8() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return (java.util.function.Function<Object, Object>) (d_3_i3) -> { return (java.util.function.Function<Object, Object>) (e_4_i4) -> { return (java.util.function.Function<Object, Object>) (f_5_i5) -> { return (java.util.function.Function<Object, Object>) (g_6_i6) -> { return (java.util.function.Function<Object, Object>) (h_7_i7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(d_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(e_4_i4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(f_5_i5))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(g_6_i6))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(h_7_i7))).apply(__M$Data_Unit.unit)))))))); }; }; }; }; }; }; }; }; }
public static final Object product7 = __init$product7();
    private static Object __init$product7() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return (java.util.function.Function<Object, Object>) (d_3_i3) -> { return (java.util.function.Function<Object, Object>) (e_4_i4) -> { return (java.util.function.Function<Object, Object>) (f_5_i5) -> { return (java.util.function.Function<Object, Object>) (g_6_i6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(d_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(e_4_i4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(f_5_i5))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(g_6_i6))).apply(__M$Data_Unit.unit))))))); }; }; }; }; }; }; }; }
public static final Object product6 = __init$product6();
    private static Object __init$product6() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return (java.util.function.Function<Object, Object>) (d_3_i3) -> { return (java.util.function.Function<Object, Object>) (e_4_i4) -> { return (java.util.function.Function<Object, Object>) (f_5_i5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(d_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(e_4_i4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(f_5_i5))).apply(__M$Data_Unit.unit)))))); }; }; }; }; }; }; }
public static final Object product5 = __init$product5();
    private static Object __init$product5() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return (java.util.function.Function<Object, Object>) (d_3_i3) -> { return (java.util.function.Function<Object, Object>) (e_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(d_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(e_4_i4))).apply(__M$Data_Unit.unit))))); }; }; }; }; }; }
public static final Object product4 = __init$product4();
    private static Object __init$product4() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return (java.util.function.Function<Object, Object>) (d_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(d_3_i3))).apply(__M$Data_Unit.unit)))); }; }; }; }; }
public static final Object product3 = __init$product3();
    private static Object __init$product3() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(__M$Data_Unit.unit))); }; }; }; }
public static final Object product2 = __init$product2();
    private static Object __init$product2() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(__M$Data_Unit.unit)); }; }; }
public static final Object product10 = __init$product10();
    private static Object __init$product10() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (c_2_i2) -> { return (java.util.function.Function<Object, Object>) (d_3_i3) -> { return (java.util.function.Function<Object, Object>) (e_4_i4) -> { return (java.util.function.Function<Object, Object>) (f_5_i5) -> { return (java.util.function.Function<Object, Object>) (g_6_i6) -> { return (java.util.function.Function<Object, Object>) (h_7_i7) -> { return (java.util.function.Function<Object, Object>) (i_8_i8) -> { return (java.util.function.Function<Object, Object>) (j_9_i9) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(b_1_i1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(c_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(d_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(e_4_i4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(f_5_i5))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(g_6_i6))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(h_7_i7))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(i_8_i8))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(j_9_i9))).apply(__M$Data_Unit.unit)))))))))); }; }; }; }; }; }; }; }; }; }; }
public static final Object product1 = __init$product1();
    private static Object __init$product1() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_Product.product)).apply(a_0_i0))).apply(__M$Data_Unit.unit); }; }
public static final Object get9 = __init$get9();
    private static Object __init$get9() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0; }; }
public static final Object get8 = __init$get8();
    private static Object __init$get8() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0; }; }
public static final Object get7 = __init$get7();
    private static Object __init$get7() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value1)).value1)).value1)).value1)).value0; }; }
public static final Object get6 = __init$get6();
    private static Object __init$get6() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value1)).value1)).value1)).value0; }; }
public static final Object get5 = __init$get5();
    private static Object __init$get5() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value1)).value1)).value0; }; }
public static final Object get4 = __init$get4();
    private static Object __init$get4() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value1)).value0; }; }
public static final Object get3 = __init$get3();
    private static Object __init$get3() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value0; }; }
public static final Object get2 = __init$get2();
    private static Object __init$get2() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value0; }; }
public static final Object get10 = __init$get10();
    private static Object __init$get10() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0; }; }
public static final Object get1 = __init$get1();
    private static Object __init$get1() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_Tuple.Tuple) (Object)(v_0_i0)).value0; }; }
}
