public class __M$Data_Nullable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Nullable"); }
    };
    // FFI provided by ../javapurs-nullable/src/Data/Nullable.java
    public static Object $null = null;

    public static Object nullable = (java.util.function.Function<Object, Object>) (a) ->
        (java.util.function.Function<Object, Object>) (r) ->
        (java.util.function.Function<Object, Object>) (f) -> a == null ? r : ((java.util.function.Function<Object, Object>) f).apply(a);

    public static Object notNull = (java.util.function.Function<Object, Object>) (x) -> x;


public static final Object toNullable = __init$toNullable();
    private static Object __init$toNullable() { return (java.util.function.Function<Object, Object>) (v2_0$r0) -> { return ( ((Boolean) ((((Object) (v2_0$r0)) instanceof __M$Data_Maybe.Nothing))) ? __M$Data_Nullable.$null : ( ((Boolean) ((((Object) (v2_0$r0)) instanceof __M$Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (__M$Data_Nullable.notNull)).apply(((__M$Data_Maybe.Just) (Object)(v2_0$r0)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }
public static final Object toMaybe = __init$toMaybe();
    private static Object __init$toMaybe() { return (java.util.function.Function<Object, Object>) (n_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Nullable.nullable)).apply(n_0$r0))).apply(__M$Data_Maybe.__singleton$Nothing.value))).apply(__M$Data_Maybe.Just); }; }
public static final Object showNullable = __init$showNullable();
    private static Object __init$showNullable() { return (java.util.function.Function<Object, Object>) (dictShow_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Show.show)).apply(dictShow_0$r0); return (java.util.function.Function<Object, Object>) (v2_2$r2) -> { return ( ((Boolean) ((((Object) (v2_2$r2)) instanceof __M$Data_Maybe.Nothing))) ? "null" : ( ((Boolean) ((((Object) (v2_2$r2)) instanceof __M$Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (__local_var_1$r1)).apply(((__M$Data_Maybe.Just) (Object)(v2_2$r2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; } }).get()))).apply(__M$Data_Nullable.toMaybe); return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object eqNullable = __init$eqNullable();
    private static Object __init$eqNullable() { return (java.util.function.Function<Object, Object>) (dictEq_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Maybe.eqMaybe)).apply(dictEq_0$r0)); return (java.util.function.Function<Object, Object>) (x_2$r2) -> { return (java.util.function.Function<Object, Object>) (y_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1$r1)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Nullable.toMaybe)).apply(x_2$r2)))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Nullable.toMaybe)).apply(y_3$r3)); }; }; } }).get(); return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); }; }
public static final Object ordNullable = __init$ordNullable();
    private static Object __init$ordNullable() { return (java.util.function.Function<Object, Object>) (dictOrd_0$r0) -> { Object eqNullable1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Nullable.eqNullable)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0$r0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Maybe.ordMaybe)).apply(dictOrd_0$r0)); return (java.util.function.Function<Object, Object>) (x_3$r3) -> { return (java.util.function.Function<Object, Object>) (y_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_2$r2)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Nullable.toMaybe)).apply(x_3$r3)))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Nullable.toMaybe)).apply(y_4$r4)); }; }; } }).get(); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r5) -> { return eqNullable1_1$r1; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; }
public static final Object eq1Nullable = __init$eq1Nullable();
    private static Object __init$eq1Nullable() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Nullable.eqNullable)).apply(dictEq_0$r0)); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get(); }
public static final Object ord1Nullable = __init$ord1Nullable();
    private static Object __init$ord1Nullable() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Nullable.ordNullable)).apply(dictOrd_0$r0)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r1) -> { return __M$Data_Nullable.eq1Nullable; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get(); }
}
