public class __M$Data_Equivalence {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Equivalence"); }
    };


public static final Object Equivalence = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object semigroupEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (java.util.function.Function<Object, Object>) (a_2_i2) -> { return (java.util.function.Function<Object, Object>) (b_3_i3) -> { return (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_0_i0)).apply(a_2_i2))).apply(b_3_i3))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v1_1_i1)).apply(a_2_i2))).apply(b_3_i3)))); }; }; }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get();
public static final Object newtypeEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get();
public static final Object monoidEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return true; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Equivalence.semigroupEquivalence; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get();
public static final Object defaultEquivalence = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0_i0); };
public static final Object contravariantEquivalence = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_1_i1)).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(x_2_i2)))).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(y_3_i3)); }; }; }; }; return new __Record$63_6d_61_70_O(new String[]{"cmap"}, __field0); } }).get();
public static final Object comparisonEquivalence = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (a_1_i1) -> { return (java.util.function.Function<Object, Object>) (b_2_i2) -> { return (((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_0_i0)).apply(a_1_i1))).apply(b_2_i2))) instanceof __M$Data_Ordering.EQ); }; }; };
}
