public class __M$Data_Show_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Show.Generic"); }
    };
    // FFI provided by ../javapurs-prelude/src/Data/Show/Generic.java
    public static Object intercalate = (java.util.function.Function<Object, Object>) (separator) ->
        (java.util.function.Function<Object, Object>) (xs) -> {
            Object[] items = (Object[]) xs;
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < items.length; i++) {
                if (i > 0) builder.append((String) separator);
                builder.append(items[i]);
            }
            return builder.toString();
        };


public static final Object genericShowArgsNoArguments = __init$genericShowArgsNoArguments();
    private static Object __init$genericShowArgsNoArguments() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return new Object[]{}; }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_41_72_67_73_O(new String[]{"genericShowArgs"}, __field0); } }).get(); }
public static final Object genericShowArgsArgument = __init$genericShowArgsArgument();
    private static Object __init$genericShowArgsArgument() { return (java.util.function.Function<Object, Object>) (dictShow_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return new Object[]{((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0$r0).get("show"))).apply(v_1$r1)}; }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_41_72_67_73_O(new String[]{"genericShowArgs"}, __field0); } }).get(); }; }
public static final Object genericShowArgs = __init$genericShowArgs();
    private static Object __init$genericShowArgs() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("genericShowArgs"); }; }
public static final Object genericShowArgsProduct = __init$genericShowArgsProduct();
    private static Object __init$genericShowArgsProduct() { return (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictGenericShowArgs1_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.concatArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShowArgs_0$r0).get("genericShowArgs"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r2)).value0)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShowArgs1_1$r1).get("genericShowArgs"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r2)).value1)); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_41_72_67_73_O(new String[]{"genericShowArgs"}, __field0); } }).get(); }; }; }
public static final Object genericShowConstructor = __init$genericShowConstructor();
    private static Object __init$genericShowConstructor() { return (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictIsSymbol_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { Object ctor_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictIsSymbol_1$r1).get("reflectSymbol"))).apply(__M$Type_Proxy.__singleton$Proxy.value); Object v1_4$r4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShowArgs_0$r0).get("genericShowArgs"))).apply(v_2$r2); return ( ((Boolean) ((((int) (((Object[]) (Object)(v1_4$r4)).length)) == ((int) (0))))) ? ctor_3$r3 : (((String) ((((String) ("(")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Show_Generic.intercalate)).apply(" "))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.concatArray)).apply(new Object[]{ctor_3$r3}))).apply(v1_4$r4))))))) + ((String) (")")))); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_27_O(new String[]{"genericShow'"}, __field0); } }).get(); }; }; }
public static final Object genericShowprime = __init$genericShowprime();
    private static Object __init$genericShowprime() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("genericShow'"); }; }
private static Object __lazy_value_genericShowNoConstructors;
private static int __lazy_state_genericShowNoConstructors;
private static Object __lazy_get_genericShowNoConstructors() { if (__lazy_state_genericShowNoConstructors == 2) return __lazy_value_genericShowNoConstructors; if (__lazy_state_genericShowNoConstructors == 1) throw new IllegalStateException("Recursive initialization of genericShowNoConstructors"); __lazy_state_genericShowNoConstructors = 1; __lazy_value_genericShowNoConstructors = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_Show_Generic.__lazy_get_genericShowNoConstructors()).get("genericShow'"))).apply(a_0$r0); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_27_O(new String[]{"genericShow'"}, __field0); } }).get(); __lazy_state_genericShowNoConstructors = 2; return __lazy_value_genericShowNoConstructors; }
public static final Object genericShowNoConstructors = __init$genericShowNoConstructors();
    private static Object __init$genericShowNoConstructors() { return __lazy_get_genericShowNoConstructors(); }
public static final Object genericShowSum = __init$genericShowSum();
    private static Object __init$genericShowSum() { return (java.util.function.Function<Object, Object>) (dictGenericShow_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictGenericShow1_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ( ((Boolean) ((((Object) (v_2$r2)) instanceof __M$Data_Generic_Rep.Inl))) ? ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShow_0$r0).get("genericShow'"))).apply(((__M$Data_Generic_Rep.Inl) (Object)(v_2$r2)).value0) : ( ((Boolean) ((((Object) (v_2$r2)) instanceof __M$Data_Generic_Rep.Inr))) ? ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShow1_1$r1).get("genericShow'"))).apply(((__M$Data_Generic_Rep.Inr) (Object)(v_2$r2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$67_65_6e_65_72_69_63_53_68_6f_77_27_O(new String[]{"genericShow'"}, __field0); } }).get(); }; }; }
public static final Object genericShow = __init$genericShow();
    private static Object __init$genericShow() { return (java.util.function.Function<Object, Object>) (dictGeneric_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictGenericShow_1$r1) -> { return (java.util.function.Function<Object, Object>) (x_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericShow_1$r1).get("genericShow'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("from"))).apply(x_2$r2)); }; }; }; }
}
