public class __M$Data_List_Lazy_NonEmpty {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.List.Lazy.NonEmpty"); }
    };


public static final Object uncons = __init$uncons();
    private static Object __init$uncons() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { Object v1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0_i0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value0; final Object __field1 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value1; return new __Record$68_65_61_64_O$74_61_69_6c_O(new String[]{"head", "tail"}, __field0, __field1); } }).get(); }; }
public static final Object toList = __init$toList();
    private static Object __init$toList() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { Object v1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0_i0); Object __local_var_2_i2 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value0; Object __local_var_3_i3 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value1; return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_4_i4) -> { return new __M$Data_List_Lazy_Types.Cons(__local_var_2_i2, __local_var_3_i3); }); }; }
public static final Object toUnfoldable = __init$toUnfoldable();
    private static Object __init$toUnfoldable() { return (java.util.function.Function<Object, Object>) (dictUnfoldable_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable_0_i0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (xs_1_i1) -> { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.uncons)).apply(xs_1_i1); return ( ((Boolean) ((((Object) (__local_var_2_i2)) instanceof __M$Data_Maybe.Just))) ? new __M$Data_Maybe.Just(new __M$Data_Tuple.Tuple(((java.util.Map<String, Object>) ((__M$Data_Maybe.Just) (Object)(__local_var_2_i2)).value0).get("head"), ((java.util.Map<String, Object>) ((__M$Data_Maybe.Just) (Object)(__local_var_2_i2)).value0).get("tail"))) : __M$Data_Maybe.__singleton$Nothing.value); })))).apply(__M$Data_List_Lazy_NonEmpty.toList); }; }
public static final Object tail = __init$tail();
    private static Object __init$tail() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0_i0))).value1; }; }
public static final Object singleton = __init$singleton();
    private static Object __init$singleton() { return ((java.util.function.Function<Object, Object>) (__M$Control_Applicative.pure)).apply(__M$Data_List_Lazy_Types.applicativeNonEmptyList); }
public static final Object repeat = __init$repeat();
    private static Object __init$repeat() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_1_i1) -> { return new __M$Data_NonEmpty.NonEmpty(x_0_i0, ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.repeat)).apply(x_0_i0)); }); }; }
public static final Object length = __init$length();
    private static Object __init$length() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (((int) (1)) + ((int) (((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.length)).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0_i0))).value1)))); }; }
public static final Object last = __init$last();
    private static Object __init$last() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { Object v1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0_i0); return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Maybe.fromMaybe)).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value0))).apply(((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.last)).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value1)); }; }
public static final Object iterate = __init$iterate();
    private static Object __init$iterate() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (x_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_2_i2) -> { return new __M$Data_NonEmpty.NonEmpty(x_1_i1, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.iterate)).apply(f_0_i0))).apply(((java.util.function.Function<Object, Object>) (f_0_i0)).apply(x_1_i1))); }); }; }; }
public static final Object init = __init$init();
    private static Object __init$init() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { { Object v1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0_i0); Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.init)).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value1); if ((Boolean) ((((Object) (__local_var_2_i2)) instanceof __M$Data_Maybe.Nothing))) { return __M$Data_List_Lazy_Types.nil; } else { {  if ((Boolean) ((((Object) (__local_var_2_i2)) instanceof __M$Data_Maybe.Just))) { { Object __local_var_3_i3 = ((__M$Data_Maybe.Just) (Object)(__local_var_2_i2)).value0; return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_4_i4) -> { return new __M$Data_List_Lazy_Types.Cons(((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1_i1)).value0, __local_var_3_i3); }); } } else { return (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get(); } } } }  }; }
public static final Object head = __init$head();
    private static Object __init$head() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0_i0))).value0; }; }
public static final Object fromList = __init$fromList();
    private static Object __init$fromList() { return (java.util.function.Function<Object, Object>) (l_0_i0) -> { { Object v_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy_Types.step)).apply(l_0_i0); if ((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_List_Lazy_Types.Nil))) { return __M$Data_Maybe.__singleton$Nothing.value; } else { {  if ((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_List_Lazy_Types.Cons))) { { Object __local_var_2_i2 = ((__M$Data_List_Lazy_Types.Cons) (Object)(v_1_i1)).value0; Object __local_var_3_i3 = ((__M$Data_List_Lazy_Types.Cons) (Object)(v_1_i1)).value1; return new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v1_4_i4) -> { return new __M$Data_NonEmpty.NonEmpty(__local_var_2_i2, __local_var_3_i3); })); } } else { return (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get(); } } } }  }; }
public static final Object fromFoldable = __init$fromFoldable();
    private static Object __init$fromFoldable() { return (java.util.function.Function<Object, Object>) (dictFoldable_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_List_Lazy_NonEmpty.fromList))).apply(((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.fromFoldable)).apply(dictFoldable_0_i0)); }; }
public static final Object cons = __init$cons();
    private static Object __init$cons() { return (java.util.function.Function<Object, Object>) (y_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v1_2_i2) -> { Object v2_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_1_i1); Object __local_var_4_i4 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v2_3_i3)).value0; Object __local_var_5_i5 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v2_3_i3)).value1; return new __M$Data_NonEmpty.NonEmpty(y_0_i0, ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_6_i6) -> { return new __M$Data_List_Lazy_Types.Cons(__local_var_4_i4, __local_var_5_i5); })); }); }; }; }
public static final Object concatMap = __init$concatMap();
    private static Object __init$concatMap() { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0_i0 = ((java.util.function.Function<Object, Object>) (__M$Control_Bind.bind)).apply(__M$Data_List_Lazy_Types.bindNonEmptyList); return (java.util.function.Function<Object, Object>) (b_1_i1) -> { return (java.util.function.Function<Object, Object>) (a_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_0_i0)).apply(a_2_i2))).apply(b_1_i1); }; }; } }).get(); }
public static final Object appendFoldable = __init$appendFoldable();
    private static Object __init$appendFoldable() { return (java.util.function.Function<Object, Object>) (dictFoldable_0_i0) -> { return (java.util.function.Function<Object, Object>) (nel_1_i1) -> { return (java.util.function.Function<Object, Object>) (ys_2_i2) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_3_i3) -> { return new __M$Data_NonEmpty.NonEmpty(((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(nel_1_i1))).value0, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_List_Lazy_Types.semigroupList).get("append"))).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(nel_1_i1))).value1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable_0_i0).get("foldr"))).apply(__M$Data_List_Lazy_Types.cons))).apply(__M$Data_List_Lazy_Types.nil))).apply(ys_2_i2))); }); }; }; }; }
}
