public class __M$Data_Distributive {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Distributive"); }
    };


public static final Object distributiveIdentity = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Identity.Identity))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))); }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictFunctor_0_i1) -> { return (java.util.function.Function<Object, Object>) (f_1_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Identity.Identity))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i1).get("map"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */)))).apply(f_1_i2))); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i3) -> { return __M$Data_Identity.functorIdentity; }; return new __Record$46_75_6e_63_74_6f_72_30_O$63_6f_6c_6c_65_63_74_O$64_69_73_74_72_69_62_75_74_65_O(new String[]{"distribute", "collect", "Functor0"}, __field2, __field1, __field0); } }).get();
public static final Object distribute = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("distribute"); };
private static Object __lazy_value_distributiveFunction;
private static int __lazy_state_distributiveFunction;
private static Object __lazy_get_distributiveFunction() { if (__lazy_state_distributiveFunction == 2) return __lazy_value_distributiveFunction; if (__lazy_state_distributiveFunction == 1) throw new IllegalStateException("Recursive initialization of distributiveFunction"); __lazy_state_distributiveFunction = 1; __lazy_value_distributiveFunction = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> { return (java.util.function.Function<Object, Object>) (a_1_i1) -> { return (java.util.function.Function<Object, Object>) (e_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply((java.util.function.Function<Object, Object>) (v_3_i3) -> { return ((java.util.function.Function<Object, Object>) (v_3_i3)).apply(e_2_i2); }))).apply(a_1_i1); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictFunctor_0_i4) -> { return (java.util.function.Function<Object, Object>) (f_1_i5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Distributive.distribute)).apply(__M$Data_Distributive.__lazy_get_distributiveFunction()))).apply(dictFunctor_0_i4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i4).get("map"))).apply(f_1_i5)); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i6) -> { return __M$Data_Functor.functorFn; }; return new __Record$46_75_6e_63_74_6f_72_30_O$63_6f_6c_6c_65_63_74_O$64_69_73_74_72_69_62_75_74_65_O(new String[]{"distribute", "collect", "Functor0"}, __field2, __field1, __field0); } }).get(); __lazy_state_distributiveFunction = 2; return __lazy_value_distributiveFunction; }
public static final Object distributiveFunction = __lazy_get_distributiveFunction();
public static final Object cotraverse = (java.util.function.Function<Object, Object>) (dictDistributive_0_i0) -> { Object Functor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDistributive_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object distribute1_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_Distributive.distribute)).apply(dictDistributive_0_i0); return (java.util.function.Function<Object, Object>) (dictFunctor_3_i3) -> { Object distribute2_4_i4 = ((java.util.function.Function<Object, Object>) (distribute1_2_i2)).apply(dictFunctor_3_i3); return (java.util.function.Function<Object, Object>) (f_5_i5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1_i1).get("map"))).apply(f_5_i5)))).apply(distribute2_4_i4); }; }; };
public static final Object collectDefault = (java.util.function.Function<Object, Object>) (dictDistributive_0_i0) -> { Object distribute1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Distributive.distribute)).apply(dictDistributive_0_i0); return (java.util.function.Function<Object, Object>) (dictFunctor_2_i2) -> { Object distribute2_3_i3 = ((java.util.function.Function<Object, Object>) (distribute1_1_i1)).apply(dictFunctor_2_i2); return (java.util.function.Function<Object, Object>) (f_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(distribute2_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_2_i2).get("map"))).apply(f_4_i4)); }; }; };
private static Object __lazy_value_distributiveTuple;
private static int __lazy_state_distributiveTuple;
private static Object __lazy_get_distributiveTuple() { if (__lazy_state_distributiveTuple == 2) return __lazy_value_distributiveTuple; if (__lazy_state_distributiveTuple == 1) throw new IllegalStateException("Recursive initialization of distributiveTuple"); __lazy_state_distributiveTuple = 1; __lazy_value_distributiveTuple = (java.util.function.Function<Object, Object>) (dictTypeEquals_0_i0) -> { return __M$Data_Distributive.__direct$5(dictTypeEquals_0_i0); }; __lazy_state_distributiveTuple = 2; return __lazy_value_distributiveTuple; }
public static final Object distributiveTuple = __lazy_get_distributiveTuple();
private static Object __direct$5(Object dictTypeEquals_0_i0) { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictFunctor_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Distributive.collectDefault)).apply(__M$Data_Distributive.__direct$5(dictTypeEquals_0_i0)))).apply(dictFunctor_1_i1); }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictFunctor_1_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Tuple.Tuple)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Type_Equality.proof)).apply(dictTypeEquals_0_i0))).apply((java.util.function.Function<Object, Object>) (a_2_i3) -> { return a_2_i3; }))).apply(__M$Data_Unit.unit))))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_1_i2).get("map"))).apply(__M$Data_Tuple.snd)); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_1_i4) -> { return __M$Data_Tuple.functorTuple; }; return new __Record$46_75_6e_63_74_6f_72_30_O$63_6f_6c_6c_65_63_74_O$64_69_73_74_72_69_62_75_74_65_O(new String[]{"collect", "distribute", "Functor0"}, __field2, __field0, __field1); } }).get(); }
public static final Object collect = (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("collect"); };
public static final Object distributeDefault = (java.util.function.Function<Object, Object>) (dictDistributive_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDistributive_0_i0).get("collect"))).apply(dictFunctor_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn)); }; };
}
