public class __M$Data_Functor_Joker {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Joker"); }
    };


public static final Object Joker = __init$Joker();
    private static Object __init$Joker() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; }; }
public static final Object showJoker = __init$showJoker();
    private static Object __init$showJoker() { return (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (((String) ((((String) ("(Joker ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0_i0).get("show"))).apply(v_1_i1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object profunctorJoker = __init$profunctorJoker();
    private static Object __init$profunctorJoker() { return (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (g_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply(g_2_i2))).apply(v1_3_i3); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get(); }; }
public static final Object ordJoker = __init$ordJoker();
    private static Object __init$ordJoker() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return dictOrd_0_i0; }; }
public static final Object newtypeJoker = __init$newtypeJoker();
    private static Object __init$newtypeJoker() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object hoistJoker = __init$hoistJoker();
    private static Object __init$hoistJoker() { return (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v_1_i1); }; }; }
public static final Object functorJoker = __init$functorJoker();
    private static Object __init$functorJoker() { return (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply(f_1_i1))).apply(v_2_i2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }; }
public static final Object eqJoker = __init$eqJoker();
    private static Object __init$eqJoker() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return dictEq_0_i0; }; }
public static final Object choiceJoker = __init$choiceJoker();
    private static Object __init$choiceJoker() { return (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> { Object profunctorJoker1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.profunctorJoker)).apply(dictFunctor_0_i0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply(__M$Data_Either.Left))).apply(v_2_i2); }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_2_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply(__M$Data_Either.Right))).apply(v_2_i3); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return profunctorJoker1_1_i1; }; return new __Record$50_72_6f_66_75_6e_63_74_6f_72_30_O$6c_65_66_74_O$72_69_67_68_74_O(new String[]{"left", "right", "Profunctor0"}, __field2, __field0, __field1); } }).get(); }; }
public static final Object bifunctorJoker = __init$bifunctorJoker();
    private static Object __init$bifunctorJoker() { return (java.util.function.Function<Object, Object>) (dictFunctor_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (g_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0_i0).get("map"))).apply(g_2_i2))).apply(v1_3_i3); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); }; }
public static final Object biapplyJoker = __init$biapplyJoker();
    private static Object __init$biapplyJoker() { return (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> { Object bifunctorJoker1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.bifunctorJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0_i0).get("apply"))).apply(v_2_i2))).apply(v1_3_i3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return bifunctorJoker1_1_i1; }; return new __Record$42_69_66_75_6e_63_74_6f_72_30_O$62_69_61_70_70_6c_79_O(new String[]{"biapply", "Bifunctor0"}, __field1, __field0); } }).get(); }; }
public static final Object biapplicativeJoker = __init$biapplicativeJoker();
    private static Object __init$biapplicativeJoker() { return (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> { Object biapplyJoker1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.biapplyJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0_i0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (b_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0_i0).get("pure"))).apply(b_3_i3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return biapplyJoker1_1_i1; }; return new __Record$42_69_61_70_70_6c_79_30_O$62_69_70_75_72_65_O(new String[]{"bipure", "Biapply0"}, __field1, __field0); } }).get(); }; }
public static final Object applyJoker = __init$applyJoker();
    private static Object __init$applyJoker() { return (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> { Object functorJoker1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.functorJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0_i0).get("apply"))).apply(v_2_i2))).apply(v1_3_i3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return functorJoker1_1_i1; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }; }
public static final Object bindJoker = __init$bindJoker();
    private static Object __init$bindJoker() { return (java.util.function.Function<Object, Object>) (dictBind_0_i0) -> { Object applyJoker1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.applyJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0_i0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (amb_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBind_0_i0).get("bind"))).apply(v_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(amb_3_i3))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Newtype.unwrap)).apply(null /* TODO: PrimUndefined */))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return applyJoker1_1_i1; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get(); }; }
public static final Object applicativeJoker = __init$applicativeJoker();
    private static Object __init$applicativeJoker() { return (java.util.function.Function<Object, Object>) (dictApplicative_0_i0) -> { Object applyJoker1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.applyJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0_i0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Functor_Joker.Joker))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Applicative.pure)).apply(dictApplicative_0_i0)); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i2) -> { return applyJoker1_1_i1; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); }; }
public static final Object monadJoker = __init$monadJoker();
    private static Object __init$monadJoker() { return (java.util.function.Function<Object, Object>) (dictMonad_0_i0) -> { Object applicativeJoker1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.applicativeJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0_i0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)); Object bindJoker1_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Joker.bindJoker)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonad_0_i0).get("Bind1"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_3_i3) -> { return applicativeJoker1_1_i1; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3_i4) -> { return bindJoker1_2_i2; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get(); }; }
}
