public class __M$Data_String_NonEmpty_CodeUnits {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.String.NonEmpty.CodeUnits"); }
    };


public static final Object snoc = (java.util.function.Function<Object, Object>) (c_0_i0) -> { return (java.util.function.Function<Object, Object>) (s_1_i1) -> { return (((String) (s_1_i1)) + ((String) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.singleton)).apply(c_0_i0)))); }; };
public static final Object singleton = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_Internal.NonEmptyString))).apply(__M$Data_String_CodeUnits.singleton);
public static final Object liftS = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (f_0_i0)).apply(v_1_i1); }; };
public static final Object takeWhile = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_Internal.fromString))).apply((java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.take)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.countPrefix)).apply(f_0_i0))).apply(v_1_i1)))).apply(v_1_i1); }); };
public static final Object lastIndexOfprime = (java.util.function.Function<Object, Object>) (pat_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_CodeUnits.liftS))).apply(((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.lastIndexOfprime)).apply(pat_0_i0)); };
public static final Object lastIndexOf = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_CodeUnits.liftS))).apply(__M$Data_String_CodeUnits.lastIndexOf);
public static final Object indexOfprime = (java.util.function.Function<Object, Object>) (pat_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_CodeUnits.liftS))).apply(((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.indexOfprime)).apply(pat_0_i0)); };
public static final Object indexOf = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_CodeUnits.liftS))).apply(__M$Data_String_CodeUnits.indexOf);
public static final Object fromNonEmptyString = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return v_0_i0; };
public static final Object length = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_CodeUnits.length))).apply(__M$Data_String_NonEmpty_CodeUnits.fromNonEmptyString);
public static final Object splitAt = (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (nes_1_i1) -> { Object v_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.splitAt)).apply(i_0_i0))).apply(nes_1_i1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ( ((Boolean) (java.util.Objects.equals(__Record$61_66_74_65_72_O$62_65_66_6f_72_65_O.read1(v_2_i2), ""))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(__Record$61_66_74_65_72_O$62_65_66_6f_72_65_O.read1(v_2_i2))); final Object __field1 = ( ((Boolean) (java.util.Objects.equals(__Record$61_66_74_65_72_O$62_65_66_6f_72_65_O.read0(v_2_i2), ""))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(__Record$61_66_74_65_72_O$62_65_66_6f_72_65_O.read0(v_2_i2))); return new __Record$61_66_74_65_72_O$62_65_66_6f_72_65_O(new String[]{"before", "after"}, __field1, __field0); } }).get(); }; };
public static final Object take = (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (nes_1_i1) -> { return ( ((Boolean) ((((int) (i_0_i0)) < ((int) (1))))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.take)).apply(i_0_i0))).apply(nes_1_i1))); }; };
public static final Object takeRight = (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (nes_1_i1) -> { return ( ((Boolean) ((((int) (i_0_i0)) < ((int) (1))))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.drop)).apply((((int) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.length)).apply(nes_1_i1))) - ((int) (i_0_i0)))))).apply(nes_1_i1))); }; };
public static final Object toChar = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_CodeUnits.toChar))).apply(__M$Data_String_NonEmpty_CodeUnits.fromNonEmptyString);
public static final Object toCharArray = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_CodeUnits.toCharArray))).apply(__M$Data_String_NonEmpty_CodeUnits.fromNonEmptyString);
public static final Object toNonEmptyCharArray = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Maybe.Just))) ? ((__M$Data_Maybe.Just) (Object)(v_0_i0)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Array_NonEmpty.fromArray))).apply(__M$Data_String_NonEmpty_CodeUnits.toCharArray));
public static final Object uncons = (java.util.function.Function<Object, Object>) (nes_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_Unsafe.charAt)).apply(0))).apply(nes_0_i0); final Object __field1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.drop)).apply(1))).apply(nes_0_i0); return ( ((Boolean) (java.util.Objects.equals(__local_var_1_i1, ""))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(__local_var_1_i1)); } }).get(); return new __Record$68_65_61_64_O$74_61_69_6c_O(new String[]{"head", "tail"}, __field0, __field1); } }).get(); };
public static final Object fromFoldable1 = (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldMap1"))).apply(__M$Data_Semigroup.semigroupString))).apply(__M$Data_String_NonEmpty_CodeUnits.singleton); };
public static final Object fromCharArray = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ( ((Boolean) ((((int) (((Object[]) (Object)(v_0_i0)).length)) == ((int) (0))))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.fromCharArray)).apply(v_0_i0))); };
public static final Object fromNonEmptyCharArray = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (v_0_i0) -> { return ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Maybe.Just))) ? ((__M$Data_Maybe.Just) (Object)(v_0_i0)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_CodeUnits.fromCharArray))).apply(__M$Data_Array_NonEmpty.toArray));
public static final Object dropWhile = (java.util.function.Function<Object, Object>) (f_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_Internal.fromString))).apply((java.util.function.Function<Object, Object>) (v_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.countPrefix)).apply(f_0_i0))).apply(v_1_i1)))).apply(v_1_i1); }); };
public static final Object dropRight = (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (nes_1_i1) -> { return ( ((Boolean) ((((int) (i_0_i0)) >= ((int) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.length)).apply(nes_1_i1)))))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.take)).apply((((int) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.length)).apply(nes_1_i1))) - ((int) (i_0_i0)))))).apply(nes_1_i1))); }; };
public static final Object drop = (java.util.function.Function<Object, Object>) (i_0_i0) -> { return (java.util.function.Function<Object, Object>) (nes_1_i1) -> { return ( ((Boolean) ((((int) (i_0_i0)) >= ((int) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.length)).apply(nes_1_i1)))))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.drop)).apply(i_0_i0))).apply(nes_1_i1))); }; };
public static final Object countPrefix = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_CodeUnits.liftS))).apply(__M$Data_String_CodeUnits.countPrefix);
public static final Object cons = (java.util.function.Function<Object, Object>) (c_0_i0) -> { return (java.util.function.Function<Object, Object>) (s_1_i1) -> { return (((String) (((java.util.function.Function<Object, Object>) (__M$Data_String_CodeUnits.singleton)).apply(c_0_i0))) + ((String) (s_1_i1))); }; };
public static final Object charAt = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_String_NonEmpty_CodeUnits.liftS))).apply(__M$Data_String_CodeUnits.charAt);
}
