public class __M$Data_Ord_Down {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Ord.Down"); }
    };


public static final Object Down = __init$Down();
    private static Object __init$Down() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object showDown = __init$showDown();
    private static Object __init$showDown() { return (java.util.function.Function<Object, Object>) (dictShow_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (((String) ((((String) ("(Down ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0$r0).get("show"))).apply(v_1$r1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object newtypeDown = __init$newtypeDown();
    private static Object __init$newtypeDown() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object eqDown = __init$eqDown();
    private static Object __init$eqDown() { return (java.util.function.Function<Object, Object>) (dictEq_0$r0) -> { return dictEq_0$r0; }; }
public static final Object ordDown = __init$ordDown();
    private static Object __init$ordDown() { return (java.util.function.Function<Object, Object>) (dictOrd_0$r0) -> { Object eqDown1_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0$r0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (v1_3$r3) -> { Object __local_var_4$r4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0$r0).get("compare"))).apply(v_2$r2))).apply(v1_3$r3); return ( ((Boolean) ((((Object) (__local_var_4$r4)) instanceof __M$Data_Ordering.GT))) ? __M$Data_Ordering.__singleton$LT.value : ( ((Boolean) ((((Object) (__local_var_4$r4)) instanceof __M$Data_Ordering.EQ))) ? __M$Data_Ordering.__singleton$EQ.value : ( ((Boolean) ((((Object) (__local_var_4$r4)) instanceof __M$Data_Ordering.LT))) ? __M$Data_Ordering.__singleton$GT.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r5) -> { return eqDown1_1$r1; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; }
public static final Object boundedDown = __init$boundedDown();
    private static Object __init$boundedDown() { return (java.util.function.Function<Object, Object>) (dictBounded_0$r0) -> { Object ordDown1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Ord_Down.ordDown)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBounded_0$r0).get("Ord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictBounded_0$r0).get("bottom"); final Object __field1 = ((java.util.Map<String, Object>) dictBounded_0$r0).get("top"); final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return ordDown1_1$r1; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_O$74_6f_70_O(new String[]{"top", "bottom", "Ord0"}, __field2, __field1, __field0); } }).get(); }; }
}
