public class __M$Control_Apply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Apply"); }
    };
    // FFI provided by ../javapurs-prelude/src/Control/Apply.java
    public static Object arrayApply = (java.util.function.Function<Object, Object>) (fs) ->
        (java.util.function.Function<Object, Object>) (xs) -> {
            Object[] functions = (Object[]) fs;
            Object[] values = (Object[]) xs;
            Object[] result = new Object[functions.length * values.length];
            int next = 0;
            for (Object function : functions) {
                for (Object value : values) {
                    result[next++] = ((java.util.function.Function<Object, Object>) function).apply(value);
                }
            }
            return result;
        };


public static final Object applyProxy = __init$applyProxy();
    private static Object __init$applyProxy() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return __M$Type_Proxy.__singleton$Proxy.value; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r2) -> { return __M$Data_Functor.functorProxy; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object applyFn = __init$applyFn();
    private static Object __init$applyFn() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (g_1$r1) -> { return (java.util.function.Function<Object, Object>) (x_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0$r0)).apply(x_2$r2))).apply(((java.util.function.Function<Object, Object>) (g_1$r1)).apply(x_2$r2)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r3) -> { return __M$Data_Functor.functorFn; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object applyArray = __init$applyArray();
    private static Object __init$applyArray() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Control_Apply.arrayApply; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Functor.functorArray; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object apply = __init$apply();
    private static Object __init$apply() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("apply"); }; }
public static final Object applyFirst = __init$applyFirst();
    private static Object __init$applyFirst() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object Functor0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return (java.util.function.Function<Object, Object>) (b_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1$r1).get("map"))).apply(__M$Data_Function.$const))).apply(a_2$r2)))).apply(b_3$r3); }; }; }; }
public static final Object applySecond = __init$applySecond();
    private static Object __init$applySecond() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object Functor0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return (java.util.function.Function<Object, Object>) (b_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1$r1).get("map"))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4$r4 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (v_5$r5) -> { return __local_var_4$r4; }; } }).get()))).apply(a_2$r2)))).apply(b_3$r3); }; }; }; }
public static final Object lift2 = __init$lift2();
    private static Object __init$lift2() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object Functor0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (a_3$r3) -> { return (java.util.function.Function<Object, Object>) (b_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1$r1).get("map"))).apply(f_2$r2))).apply(a_3$r3)))).apply(b_4$r4); }; }; }; }; }
public static final Object lift3 = __init$lift3();
    private static Object __init$lift3() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object Functor0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (a_3$r3) -> { return (java.util.function.Function<Object, Object>) (b_4$r4) -> { return (java.util.function.Function<Object, Object>) (c_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1$r1).get("map"))).apply(f_2$r2))).apply(a_3$r3)))).apply(b_4$r4)))).apply(c_5$r5); }; }; }; }; }; }
public static final Object lift4 = __init$lift4();
    private static Object __init$lift4() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object Functor0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (a_3$r3) -> { return (java.util.function.Function<Object, Object>) (b_4$r4) -> { return (java.util.function.Function<Object, Object>) (c_5$r5) -> { return (java.util.function.Function<Object, Object>) (d_6$r6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1$r1).get("map"))).apply(f_2$r2))).apply(a_3$r3)))).apply(b_4$r4)))).apply(c_5$r5)))).apply(d_6$r6); }; }; }; }; }; }; }
public static final Object lift5 = __init$lift5();
    private static Object __init$lift5() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object Functor0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (a_3$r3) -> { return (java.util.function.Function<Object, Object>) (b_4$r4) -> { return (java.util.function.Function<Object, Object>) (c_5$r5) -> { return (java.util.function.Function<Object, Object>) (d_6$r6) -> { return (java.util.function.Function<Object, Object>) (e_7$r7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1$r1).get("map"))).apply(f_2$r2))).apply(a_3$r3)))).apply(b_4$r4)))).apply(c_5$r5)))).apply(d_6$r6)))).apply(e_7$r7); }; }; }; }; }; }; }; }
}
