public class __M$Data_Monoid_Dual {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Monoid.Dual"); }
    };


public static final Object Dual = __init$Dual();
    private static Object __init$Dual() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object showDual = __init$showDual();
    private static Object __init$showDual() { return (java.util.function.Function<Object, Object>) (dictShow_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (((String) ((((String) ("(Dual ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0$r0).get("show"))).apply(v_1$r1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object semigroupDual = __init$semigroupDual();
    private static Object __init$semigroupDual() { return (java.util.function.Function<Object, Object>) (dictSemigroup_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (v1_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0$r0).get("append"))).apply(v1_2$r2))).apply(v_1$r1); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }; }
public static final Object ordDual = __init$ordDual();
    private static Object __init$ordDual() { return (java.util.function.Function<Object, Object>) (dictOrd_0$r0) -> { return dictOrd_0$r0; }; }
public static final Object monoidDual = __init$monoidDual();
    private static Object __init$monoidDual() { return (java.util.function.Function<Object, Object>) (dictMonoid_0$r0) -> { Object semigroupDual1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Monoid_Dual.semigroupDual)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonoid_0$r0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.Map<String, Object>) dictMonoid_0$r0).get("mempty"); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return semigroupDual1_1$r1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }; }
public static final Object functorDual = __init$functorDual();
    private static Object __init$functorDual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (m_1$r1) -> { return ((java.util.function.Function<Object, Object>) (f_0$r0)).apply(m_1$r1); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }
public static final Object eqDual = __init$eqDual();
    private static Object __init$eqDual() { return (java.util.function.Function<Object, Object>) (dictEq_0$r0) -> { return dictEq_0$r0; }; }
public static final Object eq1Dual = __init$eq1Dual();
    private static Object __init$eq1Dual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(dictEq_0$r0); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get(); }
public static final Object ord1Dual = __init$ord1Dual();
    private static Object __init$ord1Dual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(dictOrd_0$r0); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r1) -> { return __M$Data_Monoid_Dual.eq1Dual; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get(); }
public static final Object boundedDual = __init$boundedDual();
    private static Object __init$boundedDual() { return (java.util.function.Function<Object, Object>) (dictBounded_0$r0) -> { return dictBounded_0$r0; }; }
public static final Object applyDual = __init$applyDual();
    private static Object __init$applyDual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return ((java.util.function.Function<Object, Object>) (v_0$r0)).apply(v1_1$r1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r2) -> { return __M$Data_Monoid_Dual.functorDual; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object bindDual = __init$bindDual();
    private static Object __init$bindDual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (f_1$r1) -> { return ((java.util.function.Function<Object, Object>) (f_1$r1)).apply(v_0$r0); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r2) -> { return __M$Data_Monoid_Dual.applyDual; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get(); }
public static final Object applicativeDual = __init$applicativeDual();
    private static Object __init$applicativeDual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Monoid_Dual.Dual; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Monoid_Dual.applyDual; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); }
public static final Object monadDual = __init$monadDual();
    private static Object __init$monadDual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Monoid_Dual.applicativeDual; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r1) -> { return __M$Data_Monoid_Dual.bindDual; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get(); }
}
