public class __M$Effect_Class_Console {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Effect.Class.Console"); }
    };


public static final Object warnShow = __init$warnShow();
    private static Object __init$warnShow() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { Object liftEffect_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0); return (java.util.function.Function<Object, Object>) (dictShow_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1$r1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.warnShow)).apply(dictShow_2$r2)); }; }; }
public static final Object warn = __init$warn();
    private static Object __init$warn() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.warn); }; }
public static final Object timeLog = __init$timeLog();
    private static Object __init$timeLog() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.timeLog); }; }
public static final Object timeEnd = __init$timeEnd();
    private static Object __init$timeEnd() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.timeEnd); }; }
public static final Object time = __init$time();
    private static Object __init$time() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.time); }; }
public static final Object logShow = __init$logShow();
    private static Object __init$logShow() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { Object liftEffect_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0); return (java.util.function.Function<Object, Object>) (dictShow_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1$r1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.logShow)).apply(dictShow_2$r2)); }; }; }
public static final Object log = __init$log();
    private static Object __init$log() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; }); }; }
public static final Object infoShow = __init$infoShow();
    private static Object __init$infoShow() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { Object liftEffect_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0); return (java.util.function.Function<Object, Object>) (dictShow_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1$r1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.infoShow)).apply(dictShow_2$r2)); }; }; }
public static final Object info = __init$info();
    private static Object __init$info() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.info); }; }
public static final Object groupEnd = __init$groupEnd();
    private static Object __init$groupEnd() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0$r0).get("liftEffect"))).apply(__M$Effect_Console.groupEnd); }; }
public static final Object groupCollapsed = __init$groupCollapsed();
    private static Object __init$groupCollapsed() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.groupCollapsed); }; }
public static final Object group = __init$group();
    private static Object __init$group() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.group); }; }
public static final Object grouped = __init$grouped();
    private static Object __init$grouped() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { Object Monad0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0$r0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1$r1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object groupEnd1_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class_Console.groupEnd)).apply(dictMonadEffect_0$r0); Object Applicative0_4$r4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1$r1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (name_5$r5) -> { return (java.util.function.Function<Object, Object>) (inner_6$r6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Bind.bind)).apply(Bind1_2$r2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.group))).apply(name_5$r5)))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_7$r7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_2$r2).get("bind"))).apply(inner_6$r6))).apply((java.util.function.Function<Object, Object>) (result_8$r8) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Bind.bind)).apply(Bind1_2$r2))).apply(groupEnd1_3$r3))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_9$r9) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Applicative0_4$r4).get("pure"))).apply(result_8$r8); }); }); }); }; }; }; }
public static final Object errorShow = __init$errorShow();
    private static Object __init$errorShow() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { Object liftEffect_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0); return (java.util.function.Function<Object, Object>) (dictShow_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1$r1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.errorShow)).apply(dictShow_2$r2)); }; }; }
public static final Object error = __init$error();
    private static Object __init$error() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.error); }; }
public static final Object debugShow = __init$debugShow();
    private static Object __init$debugShow() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { Object liftEffect_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0); return (java.util.function.Function<Object, Object>) (dictShow_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1$r1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.debugShow)).apply(dictShow_2$r2)); }; }; }
public static final Object debug = __init$debug();
    private static Object __init$debug() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0$r0)))).apply(__M$Effect_Console.debug); }; }
public static final Object clear = __init$clear();
    private static Object __init$clear() { return (java.util.function.Function<Object, Object>) (dictMonadEffect_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0$r0).get("liftEffect"))).apply(__M$Effect_Console.clear); }; }
}
