public class __M$Data_Profunctor_Strong {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Profunctor.Strong"); }
    };


public static final Object strongFn = __init$strongFn();
    private static Object __init$strongFn() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a2b_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (a2b_0$r0)).apply(((__M$Data_Tuple.Tuple) (Object)(v_1$r1)).value0), ((__M$Data_Tuple.Tuple) (Object)(v_1$r1)).value1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (f_0$r2) -> { return (java.util.function.Function<Object, Object>) (m_1$r3) -> { return new __M$Data_Tuple.Tuple(((__M$Data_Tuple.Tuple) (Object)(m_1$r3)).value0, ((java.util.function.Function<Object, Object>) (f_0$r2)).apply(((__M$Data_Tuple.Tuple) (Object)(m_1$r3)).value1)); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r4) -> { return __M$Data_Profunctor.profunctorFn; }; return new __Record$50_72_6f_66_75_6e_63_74_6f_72_30_O$66_69_72_73_74_O$73_65_63_6f_6e_64_O(new String[]{"first", "second", "Profunctor0"}, __field2, __field0, __field1); } }).get(); }
public static final Object second = __init$second();
    private static Object __init$second() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("second"); }; }
public static final Object first = __init$first();
    private static Object __init$first() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("first"); }; }
public static final Object splitStrong = __init$splitStrong();
    private static Object __init$splitStrong() { return (java.util.function.Function<Object, Object>) (dictSemigroupoid_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictStrong_1$r1) -> { return (java.util.function.Function<Object, Object>) (l_2$r2) -> { return (java.util.function.Function<Object, Object>) (r_3$r3) -> { return __M$Data_Profunctor_Strong.__direct$3(dictSemigroupoid_0$r0, dictStrong_1$r1, l_2$r2, r_3$r3); }; }; }; }; }
private static Object __direct$3(Object dictSemigroupoid_0$r0, Object dictStrong_1$r1, Object l_2$r2, Object r_3$r3) { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(dictSemigroupoid_0$r0))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictStrong_1$r1).get("first"))).apply(l_2$r2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictStrong_1$r1).get("second"))).apply(r_3$r3)); }
public static final Object fanout = __init$fanout();
    private static Object __init$fanout() { return (java.util.function.Function<Object, Object>) (dictSemigroupoid_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictStrong_1$r1) -> { Object Profunctor0_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictStrong_1$r1).get("Profunctor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (l_3$r3) -> { return (java.util.function.Function<Object, Object>) (r_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Profunctor0_2$r2).get("dimap"))).apply((java.util.function.Function<Object, Object>) (a_5$r5) -> { return new __M$Data_Tuple.Tuple(a_5$r5, a_5$r5); }))).apply((java.util.function.Function<Object, Object>) (x_5$r6) -> { return x_5$r6; }))).apply(__M$Data_Profunctor_Strong.__direct$3(dictSemigroupoid_0$r0, dictStrong_1$r1, l_3$r3, r_4$r4)); }; }; }; }; }
}
