public class __M$Data_Array_NonEmpty_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Array.NonEmpty.Internal"); }
    };
    public static Object foldl1Impl = FFI_STUB;
    public static Object foldl1Impl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Array.NonEmpty.Internal.foldl1Impl"); }
    public static Object foldr1Impl = FFI_STUB;
    public static Object foldr1Impl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Array.NonEmpty.Internal.foldr1Impl"); }
    public static Object traverse1Impl = FFI_STUB;
    public static Object traverse1Impl(Object... args) { throw new UnsupportedOperationException("Missing Java FFI: Data.Array.NonEmpty.Internal.traverse1Impl"); }

public static final Object NonEmptyArray = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; };
public static final Object unfoldable1NonEmptyArray = __M$Data_Unfoldable1.unfoldable1Array;
public static final Object traversableWithIndexNonEmptyArray = __M$Data_TraversableWithIndex.traversableWithIndexArray;
public static final Object traversableNonEmptyArray = __M$Data_Traversable.traversableArray;
public static final Object showNonEmptyArray = (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { Object showArray_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Show.showArray)).apply(dictShow_0_i0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (((String) ((((String) ("(NonEmptyArray ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) showArray_1_i1).get("show"))).apply(v_2_i2)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); };
public static final Object semigroupNonEmptyArray = __M$Data_Semigroup.semigroupArray;
public static final Object ordNonEmptyArray = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordArray)).apply(dictOrd_0_i0); };
public static final Object ord1NonEmptyArray = __M$Data_Ord.ord1Array;
public static final Object monadNonEmptyArray = __M$Control_Monad.monadArray;
public static final Object functorWithIndexNonEmptyArray = __M$Data_FunctorWithIndex.functorWithIndexArray;
public static final Object functorNonEmptyArray = __M$Data_Functor.functorArray;
public static final Object foldableWithIndexNonEmptyArray = __M$Data_FoldableWithIndex.foldableWithIndexArray;
public static final Object foldableNonEmptyArray = __M$Data_Foldable.foldableArray;
private static Object __lazy_value_foldable1NonEmptyArray;
private static int __lazy_state_foldable1NonEmptyArray;
private static Object __lazy_get_foldable1NonEmptyArray() { if (__lazy_state_foldable1NonEmptyArray == 2) return __lazy_value_foldable1NonEmptyArray; if (__lazy_state_foldable1NonEmptyArray == 1) throw new IllegalStateException("Recursive initialization of foldable1NonEmptyArray"); __lazy_state_foldable1NonEmptyArray = 1; __lazy_value_foldable1NonEmptyArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.foldMap1DefaultL)).apply(__M$Data_Array_NonEmpty_Internal.__lazy_get_foldable1NonEmptyArray()))).apply(__M$Data_Functor.functorArray))).apply(dictSemigroup_0_i0); }; final Object __field1 = (java.util.function.Function<Object, Object>) (__local_var_0_i1) -> { return (java.util.function.Function<Object, Object>) (__local_var_1_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty_Internal.foldr1Impl)).apply(__local_var_0_i1))).apply(__local_var_1_i2); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (__local_var_0_i3) -> { return (java.util.function.Function<Object, Object>) (__local_var_1_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty_Internal.foldl1Impl)).apply(__local_var_0_i3))).apply(__local_var_1_i4); }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i5) -> { return __M$Data_Foldable.foldableArray; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldMap1", "foldr1", "foldl1", "Foldable0"}, __field3, __field0, __field2, __field1); } }).get(); __lazy_state_foldable1NonEmptyArray = 2; return __lazy_value_foldable1NonEmptyArray; }
public static final Object foldable1NonEmptyArray = __lazy_get_foldable1NonEmptyArray();
private static Object __lazy_value_traversable1NonEmptyArray;
private static int __lazy_state_traversable1NonEmptyArray;
private static Object __lazy_get_traversable1NonEmptyArray() { if (__lazy_state_traversable1NonEmptyArray == 2) return __lazy_value_traversable1NonEmptyArray; if (__lazy_state_traversable1NonEmptyArray == 1) throw new IllegalStateException("Recursive initialization of traversable1NonEmptyArray"); __lazy_state_traversable1NonEmptyArray = 1; __lazy_value_traversable1NonEmptyArray = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> { Object apply_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Control_Apply.apply)).apply(dictApply_0_i0); Object go__map_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor.map)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (f_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Array_NonEmpty_Internal.traverse1Impl)).apply(apply_1_i1))).apply(go__map_2_i2))).apply(f_3_i3); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictApply_0_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Traversable.sequence1Default)).apply(__M$Data_Array_NonEmpty_Internal.__lazy_get_traversable1NonEmptyArray()))).apply(dictApply_0_i4); }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i5) -> { return __M$Data_Array_NonEmpty_Internal.foldable1NonEmptyArray; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i6) -> { return __M$Data_Traversable.traversableArray; }; return new __Record$46_6f_6c_64_61_62_6c_65_31_30_O$54_72_61_76_65_72_73_61_62_6c_65_31_O$73_65_71_75_65_6e_63_65_31_O$74_72_61_76_65_72_73_65_31_O(new String[]{"traverse1", "sequence1", "Foldable10", "Traversable1"}, __field2, __field3, __field1, __field0); } }).get(); __lazy_state_traversable1NonEmptyArray = 2; return __lazy_value_traversable1NonEmptyArray; }
public static final Object traversable1NonEmptyArray = __lazy_get_traversable1NonEmptyArray();
public static final Object eqNonEmptyArray = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eqArray)).apply(dictEq_0_i0); };
public static final Object eq1NonEmptyArray = __M$Data_Eq.eq1Array;
public static final Object bindNonEmptyArray = __M$Control_Bind.bindArray;
public static final Object applyNonEmptyArray = __M$Control_Apply.applyArray;
public static final Object applicativeNonEmptyArray = __M$Control_Applicative.applicativeArray;
public static final Object altNonEmptyArray = __M$Control_Alt.altArray;
}
