public class __M$Data_Number_Approximate {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Number.Approximate"); }
    };


public static final Object Tolerance = __init$Tolerance();
    private static Object __init$Tolerance() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object Fraction = __init$Fraction();
    private static Object __init$Fraction() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object eqRelative = __init$eqRelative();
    private static Object __init$eqRelative() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (java.util.function.Function<Object, Object>) (v2_2$r2) -> { return __M$Data_Number_Approximate.__direct$2(v_0$r0, v1_1$r1, v2_2$r2); }; }; }; }
private static Object __direct$2(Object v_0$r0, Object v1_1$r1, Object v2_2$r2) { return ( ((Boolean) ((((double) (v1_1$r1)) == ((double) (0.0))))) ? (!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordNumberImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Number.abs)).apply(v2_2$r2)))).apply(v_0$r0))) instanceof __M$Data_Ordering.GT))))) : ( ((Boolean) ((((double) (v2_2$r2)) == ((double) (0.0))))) ? (!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordNumberImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Number.abs)).apply(v1_1$r1)))).apply(v_0$r0))) instanceof __M$Data_Ordering.GT))))) : (!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordNumberImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Number.abs)).apply((((Double) (v1_1$r1)) - ((Double) (v2_2$r2))))))).apply((((Double) ((((Double) (v_0$r0)) * ((Double) (((java.util.function.Function<Object, Object>) (__M$Data_Number.abs)).apply((((Double) (v1_1$r1)) + ((Double) (v2_2$r2))))))))) / ((Double) (2.0)))))) instanceof __M$Data_Ordering.GT))))))); }
public static final Object eqApproximate = __init$eqApproximate();
    private static Object __init$eqApproximate() { return ((java.util.function.Function<Object, Object>) (__M$Data_Number_Approximate.eqRelative)).apply(0.000001); }
public static final Object neqApproximate = __init$neqApproximate();
    private static Object __init$neqApproximate() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return (java.util.function.Function<Object, Object>) (y_1$r1) -> { return (!(((Boolean) (__M$Data_Number_Approximate.__direct$2(0.000001, x_0$r0, y_1$r1))))); }; }; }
public static final Object eqAbsolute = __init$eqAbsolute();
    private static Object __init$eqAbsolute() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (x_1$r1) -> { return (java.util.function.Function<Object, Object>) (y_2$r2) -> { return (!(((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ord.ordNumberImpl)).apply(__M$Data_Ordering.__singleton$LT.value))).apply(__M$Data_Ordering.__singleton$EQ.value))).apply(__M$Data_Ordering.__singleton$GT.value))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Number.abs)).apply((((Double) (x_1$r1)) - ((Double) (y_2$r2))))))).apply(v_0$r0))) instanceof __M$Data_Ordering.GT))))); }; }; }; }
}
