public class __M$Data_Profunctor_Split {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Profunctor.Split"); }
    };


public static final class SplitF {
            public final Object value0;
            public final Object value1;
            public final Object value2;
            public SplitF(Object value0, Object value1, Object value2){
                this.value0 = value0;
                this.value1 = value1;
                this.value2 = value2;
            }
        }
public static final Object SplitF = __init$SplitF();
    private static Object __init$SplitF() { return (java.util.function.Function<Object, Object>) (value0$r0) -> (java.util.function.Function<Object, Object>) (value1$r1) -> (java.util.function.Function<Object, Object>) (value2$r2) -> { return new __M$Data_Profunctor_Split.SplitF(value0$r0, value1$r1, value2$r2); }; }
public static final Object unSplit = __init$unSplit();
    private static Object __init$unSplit() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0$r0)).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value2); }; }; }
public static final Object split = __init$split();
    private static Object __init$split() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (g_1$r1) -> { return (java.util.function.Function<Object, Object>) (fx_2$r2) -> { return new __M$Data_Profunctor_Split.SplitF(f_0$r0, g_1$r1, fx_2$r2); }; }; }; }
public static final Object profunctorSplit = __init$profunctorSplit();
    private static Object __init$profunctorSplit() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (g_1$r1) -> { return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (h_3$r3) -> { return (java.util.function.Function<Object, Object>) (i_4$r4) -> { Object __local_var_5$r5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(h_3$r3))).apply(f_0$r0); Object __local_var_6$r6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(g_1$r1))).apply(i_4$r4); return (java.util.function.Function<Object, Object>) (fx_7$r7) -> { return new __M$Data_Profunctor_Split.SplitF(__local_var_5$r5, __local_var_6$r6, fx_7$r7); }; }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2$r2)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2$r2)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2$r2)).value2); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get(); }
public static final Object lowerSplit = __init$lowerSplit();
    private static Object __init$lowerSplit() { return (java.util.function.Function<Object, Object>) (dictInvariant_0$r0) -> { Object __local_var_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Invariant.imap)).apply(dictInvariant_0$r0); return (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (b_3$r3) -> { return (java.util.function.Function<Object, Object>) (a_4$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1$r1)).apply(a_4$r4))).apply(b_3$r3); }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2$r2)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2$r2)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_2$r2)).value2); }; }; }
public static final Object liftSplit = __init$liftSplit();
    private static Object __init$liftSplit() { return (java.util.function.Function<Object, Object>) (fx_0$r0) -> { return new __M$Data_Profunctor_Split.SplitF((java.util.function.Function<Object, Object>) (x_1$r1) -> { return x_1$r1; }, (java.util.function.Function<Object, Object>) (x_1$r2) -> { return x_1$r2; }, fx_0$r0); }; }
public static final Object hoistSplit = __init$hoistSplit();
    private static Object __init$hoistSplit() { return (java.util.function.Function<Object, Object>) (nat_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (g_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((java.util.function.Function<Object, Object>) (fx_4$r4) -> { return new __M$Data_Profunctor_Split.SplitF(f_2$r2, g_3$r3, fx_4$r4); }))).apply(nat_0$r0); }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value2); }; }; }
public static final Object functorSplit = __init$functorSplit();
    private static Object __init$functorSplit() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (g_2$r2) -> { return (java.util.function.Function<Object, Object>) (h_3$r3) -> { return (java.util.function.Function<Object, Object>) (fx_4$r4) -> { return new __M$Data_Profunctor_Split.SplitF(g_2$r2, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0$r0))).apply(h_3$r3), fx_4$r4); }; }; })).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value0))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value1))).apply(((__M$Data_Profunctor_Split.SplitF) (Object)(v_1$r1)).value2); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }
}
