public class __M$Control_Monad_Writer_Class {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Monad.Writer.Class"); }
    };


public static final Object tell = __init$tell();
    private static Object __init$tell() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("tell"); }; }
public static final Object pass = __init$pass();
    private static Object __init$pass() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("pass"); }; }
public static final Object listen = __init$listen();
    private static Object __init$listen() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("listen"); }; }
public static final Object listens = __init$listens();
    private static Object __init$listens() { return (java.util.function.Function<Object, Object>) (dictMonadWriter_0$r0) -> { Object Monad1_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadWriter_0$r0).get("MonadTell1"))).apply(null /* TODO: PrimUndefined */)).get("Monad1"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad1_1$r1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object pure_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Control_Applicative.pure)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad1_1$r1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (f_4$r4) -> { return (java.util.function.Function<Object, Object>) (m_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_2$r2).get("bind"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadWriter_0$r0).get("listen"))).apply(m_5$r5)))).apply((java.util.function.Function<Object, Object>) (v_6$r6) -> { return ((java.util.function.Function<Object, Object>) (pure_3$r3)).apply(new __M$Data_Tuple.Tuple(((__M$Data_Tuple.Tuple) (Object)(v_6$r6)).value0, ((java.util.function.Function<Object, Object>) (f_4$r4)).apply(((__M$Data_Tuple.Tuple) (Object)(v_6$r6)).value1))); }); }; }; }; }
public static final Object censor = __init$censor();
    private static Object __init$censor() { return (java.util.function.Function<Object, Object>) (dictMonadWriter_0$r0) -> { Object Monad1_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadWriter_0$r0).get("MonadTell1"))).apply(null /* TODO: PrimUndefined */)).get("Monad1"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad1_1$r1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object pure_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Control_Applicative.pure)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad1_1$r1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (f_4$r4) -> { return (java.util.function.Function<Object, Object>) (m_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadWriter_0$r0).get("pass"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_2$r2).get("bind"))).apply(m_5$r5))).apply((java.util.function.Function<Object, Object>) (a_6$r6) -> { return ((java.util.function.Function<Object, Object>) (pure_3$r3)).apply(new __M$Data_Tuple.Tuple(a_6$r6, f_4$r4)); })); }; }; }; }
}
