public class __M$Data_Either_Inject {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Either.Inject"); }
    };


public static final Object prj = __init$prj();
    private static Object __init$prj() { return (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("prj"); }; }
public static final Object injectReflexive = __init$injectReflexive();
    private static Object __init$injectReflexive() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); final Object __field1 = __M$Data_Maybe.Just; return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get(); }
public static final Object injectLeft = __init$injectLeft();
    private static Object __init$injectLeft() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Either.Left; final Object __field1 = (java.util.function.Function<Object, Object>) (v2_0_i0) -> { return ( ((Boolean) ((((Object) (v2_0_i0)) instanceof __M$Data_Either.Left))) ? new __M$Data_Maybe.Just(((__M$Data_Either.Left) (Object)(v2_0_i0)).value0) : ( ((Boolean) ((((Object) (v2_0_i0)) instanceof __M$Data_Either.Right))) ? __M$Data_Maybe.__singleton$Nothing.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get(); }
public static final Object inj = __init$inj();
    private static Object __init$inj() { return (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("inj"); }; }
public static final Object injectRight = __init$injectRight();
    private static Object __init$injectRight() { return (java.util.function.Function<Object, Object>) (dictInject_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Either.Right))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Either_Inject.inj)).apply(dictInject_0_i0)); final Object __field1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Either_Inject.prj)).apply(dictInject_0_i0); return (java.util.function.Function<Object, Object>) (v2_2_i2) -> { return ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Either.Left))) ? __M$Data_Maybe.__singleton$Nothing.value : ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Either.Right))) ? ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(((__M$Data_Either.Right) (Object)(v2_2_i2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; } }).get(); return new __Record$69_6e_6a_O$70_72_6a_O(new String[]{"inj", "prj"}, __field0, __field1); } }).get(); }; }
}
