public class __M$Data_DivisionRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.DivisionRing"); }
    };


public static final Object recip = __init$recip();
    private static Object __init$recip() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("recip"); }; }
public static final Object rightDiv = __init$rightDiv();
    private static Object __init$rightDiv() { return (java.util.function.Function<Object, Object>) (dictDivisionRing_0$r0) -> { Object Semiring0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0$r0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return (java.util.function.Function<Object, Object>) (b_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semiring0_1$r1).get("mul"))).apply(a_2$r2))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0$r0).get("recip"))).apply(b_3$r3)); }; }; }; }
public static final Object leftDiv = __init$leftDiv();
    private static Object __init$leftDiv() { return (java.util.function.Function<Object, Object>) (dictDivisionRing_0$r0) -> { Object Semiring0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0$r0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return (java.util.function.Function<Object, Object>) (b_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Semiring0_1$r1).get("mul"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictDivisionRing_0$r0).get("recip"))).apply(b_3$r3)))).apply(a_2$r2); }; }; }; }
public static final Object divisionringNumber = __init$divisionringNumber();
    private static Object __init$divisionringNumber() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0$r0) -> { return (((Double) (1.0)) / ((Double) (x_0$r0))); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r1) -> { return __M$Data_Ring.ringNumber; }; return new __Record$52_69_6e_67_30_O$72_65_63_69_70_O(new String[]{"recip", "Ring0"}, __field1, __field0); } }).get(); }
}
