public class __M$Data_CommutativeRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.CommutativeRing"); }
    };


public static final Object commutativeRingUnit = __init$commutativeRingUnit();
    private static Object __init$commutativeRingUnit() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Ring.ringUnit; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); }
public static final Object commutativeRingRecordNil = __init$commutativeRingRecordNil();
    private static Object __init$commutativeRingRecordNil() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Ring.ringRecordNil; }; return new __Record$52_69_6e_67_52_65_63_6f_72_64_30_O(new String[]{"RingRecord0"}, __field0); } }).get(); }
public static final Object commutativeRingRecordCons = __init$commutativeRingRecordCons();
    private static Object __init$commutativeRingRecordCons() { return (java.util.function.Function<Object, Object>) (dictIsSymbol_0$r0) -> { return (java.util.function.Function<Object, Object>) (_dollar___unused_1$r1) -> { return (java.util.function.Function<Object, Object>) (dictCommutativeRingRecord_2$r2) -> { Object ringRecordCons1_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ring.ringRecordCons)).apply(dictIsSymbol_0$r0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRingRecord_2$r2).get("RingRecord0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictCommutativeRing_4$r4) -> { Object ringRecordCons2_5$r5 = ((java.util.function.Function<Object, Object>) (ringRecordCons1_3$r3)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRing_4$r4).get("Ring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_6$r6) -> { return ringRecordCons2_5$r5; }; return new __Record$52_69_6e_67_52_65_63_6f_72_64_30_O(new String[]{"RingRecord0"}, __field0); } }).get(); }; }; }; }; }
public static final Object commutativeRingRecord = __init$commutativeRingRecord();
    private static Object __init$commutativeRingRecord() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictCommutativeRingRecord_1$r1) -> { Object ringRecord1_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Ring.ringRecord)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRingRecord_1$r1).get("RingRecord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r3) -> { return ringRecord1_2$r2; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); }; }; }
public static final Object commutativeRingProxy = __init$commutativeRingProxy();
    private static Object __init$commutativeRingProxy() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Ring.ringProxy; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); }
public static final Object commutativeRingNumber = __init$commutativeRingNumber();
    private static Object __init$commutativeRingNumber() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Ring.ringNumber; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); }
public static final Object commutativeRingInt = __init$commutativeRingInt();
    private static Object __init$commutativeRingInt() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Ring.ringInt; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); }
public static final Object commutativeRingFn = __init$commutativeRingFn();
    private static Object __init$commutativeRingFn() { return (java.util.function.Function<Object, Object>) (dictCommutativeRing_0$r0) -> { Object ringFn_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Ring.ringFn)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictCommutativeRing_0$r0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return ringFn_1$r1; }; return new __Record$52_69_6e_67_30_O(new String[]{"Ring0"}, __field0); } }).get(); }; }
}
