public class __M$Data_Semiring_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Semiring.Generic"); }
    };


public static final Object genericZeroprime = __init$genericZeroprime();
    private static Object __init$genericZeroprime() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("genericZero'"); }; }
public static final Object genericZero = __init$genericZero();
    private static Object __init$genericZero() { return (java.util.function.Function<Object, Object>) (dictGeneric_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemiring_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("to"))).apply(((java.util.Map<String, Object>) dictGenericSemiring_1$r1).get("genericZero'")); }; }; }
public static final Object genericSemiringNoArguments = __init$genericSemiringNoArguments();
    private static Object __init$genericSemiringNoArguments() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return __M$Data_Generic_Rep.__singleton$NoArguments.value; }; }; final Object __field1 = __M$Data_Generic_Rep.__singleton$NoArguments.value; final Object __field2 = (java.util.function.Function<Object, Object>) (v_0$r2) -> { return (java.util.function.Function<Object, Object>) (v1_1$r3) -> { return __M$Data_Generic_Rep.__singleton$NoArguments.value; }; }; final Object __field3 = __M$Data_Generic_Rep.__singleton$NoArguments.value; return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get(); }
public static final Object genericSemiringArgument = __init$genericSemiringArgument();
    private static Object __init$genericSemiringArgument() { return (java.util.function.Function<Object, Object>) (dictSemiring_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (v1_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemiring_0$r0).get("add"))).apply(v_1$r1))).apply(v1_2$r2); }; }; final Object __field1 = ((java.util.Map<String, Object>) dictSemiring_0$r0).get("zero"); final Object __field2 = (java.util.function.Function<Object, Object>) (v_1$r3) -> { return (java.util.function.Function<Object, Object>) (v1_2$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemiring_0$r0).get("mul"))).apply(v_1$r3))).apply(v1_2$r4); }; }; final Object __field3 = ((java.util.Map<String, Object>) dictSemiring_0$r0).get("one"); return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get(); }; }
public static final Object genericOneprime = __init$genericOneprime();
    private static Object __init$genericOneprime() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("genericOne'"); }; }
public static final Object genericOne = __init$genericOne();
    private static Object __init$genericOne() { return (java.util.function.Function<Object, Object>) (dictGeneric_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemiring_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("to"))).apply(((java.util.Map<String, Object>) dictGenericSemiring_1$r1).get("genericOne'")); }; }; }
public static final Object genericMulprime = __init$genericMulprime();
    private static Object __init$genericMulprime() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("genericMul'"); }; }
public static final Object genericMul = __init$genericMul();
    private static Object __init$genericMul() { return (java.util.function.Function<Object, Object>) (dictGeneric_0$r0) -> { Object to_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Generic_Rep.to)).apply(dictGeneric_0$r0); return (java.util.function.Function<Object, Object>) (dictGenericSemiring_2$r2) -> { return (java.util.function.Function<Object, Object>) (x_3$r3) -> { return (java.util.function.Function<Object, Object>) (y_4$r4) -> { return ((java.util.function.Function<Object, Object>) (to_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_2$r2).get("genericMul'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("from"))).apply(x_3$r3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("from"))).apply(y_4$r4))); }; }; }; }; }
public static final Object genericAddprime = __init$genericAddprime();
    private static Object __init$genericAddprime() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("genericAdd'"); }; }
public static final Object genericSemiringConstructor = __init$genericSemiringConstructor();
    private static Object __init$genericSemiringConstructor() { return (java.util.function.Function<Object, Object>) (dictGenericSemiring_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (v1_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericAdd'"))).apply(v_1$r1))).apply(v1_2$r2); }; }; final Object __field1 = ((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericZero'"); final Object __field2 = (java.util.function.Function<Object, Object>) (v_1$r3) -> { return (java.util.function.Function<Object, Object>) (v1_2$r4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericMul'"))).apply(v_1$r3))).apply(v1_2$r4); }; }; final Object __field3 = ((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericOne'"); return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get(); }; }
public static final Object genericSemiringProduct = __init$genericSemiringProduct();
    private static Object __init$genericSemiringProduct() { return (java.util.function.Function<Object, Object>) (dictGenericSemiring_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictGenericSemiring1_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (v1_3$r3) -> { return new __M$Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericAdd'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r2)).value0))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3$r3)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring1_1$r1).get("genericAdd'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r2)).value1))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3$r3)).value1)); }; }; final Object __field1 = new __M$Data_Generic_Rep.Product(((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericZero'"), ((java.util.Map<String, Object>) dictGenericSemiring1_1$r1).get("genericZero'")); final Object __field2 = (java.util.function.Function<Object, Object>) (v_2$r4) -> { return (java.util.function.Function<Object, Object>) (v1_3$r5) -> { return new __M$Data_Generic_Rep.Product(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericMul'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r4)).value0))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3$r5)).value0), ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring1_1$r1).get("genericMul'"))).apply(((__M$Data_Generic_Rep.Product) (Object)(v_2$r4)).value1))).apply(((__M$Data_Generic_Rep.Product) (Object)(v1_3$r5)).value1)); }; }; final Object __field3 = new __M$Data_Generic_Rep.Product(((java.util.Map<String, Object>) dictGenericSemiring_0$r0).get("genericOne'"), ((java.util.Map<String, Object>) dictGenericSemiring1_1$r1).get("genericOne'")); return new __Record$67_65_6e_65_72_69_63_41_64_64_27_O$67_65_6e_65_72_69_63_4d_75_6c_27_O$67_65_6e_65_72_69_63_4f_6e_65_27_O$67_65_6e_65_72_69_63_5a_65_72_6f_27_O(new String[]{"genericAdd'", "genericZero'", "genericMul'", "genericOne'"}, __field0, __field2, __field3, __field1); } }).get(); }; }; }
public static final Object genericAdd = __init$genericAdd();
    private static Object __init$genericAdd() { return (java.util.function.Function<Object, Object>) (dictGeneric_0$r0) -> { Object to_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Generic_Rep.to)).apply(dictGeneric_0$r0); return (java.util.function.Function<Object, Object>) (dictGenericSemiring_2$r2) -> { return (java.util.function.Function<Object, Object>) (x_3$r3) -> { return (java.util.function.Function<Object, Object>) (y_4$r4) -> { return ((java.util.function.Function<Object, Object>) (to_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGenericSemiring_2$r2).get("genericAdd'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("from"))).apply(x_3$r3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictGeneric_0$r0).get("from"))).apply(y_4$r4))); }; }; }; }; }
}
