public class __M$Data_Functor_Costar {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Costar"); }
    };


public static final Object Costar = __init$Costar();
    private static Object __init$Costar() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object semigroupoidCostar = __init$semigroupoidCostar();
    private static Object __init$semigroupoidCostar() { return (java.util.function.Function<Object, Object>) (dictExtend_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (java.util.function.Function<Object, Object>) (v1_2$r2) -> { return (java.util.function.Function<Object, Object>) (w_3$r3) -> { return ((java.util.function.Function<Object, Object>) (v_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictExtend_0$r0).get("extend"))).apply(v1_2$r2))).apply(w_3$r3)); }; }; }; return new __Record$63_6f_6d_70_6f_73_65_O(new String[]{"compose"}, __field0); } }).get(); }; }
public static final Object profunctorCostar = __init$profunctorCostar();
    private static Object __init$profunctorCostar() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (g_2$r2) -> { return (java.util.function.Function<Object, Object>) (v_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply(f_1$r1)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(v_3$r3))).apply(g_2$r2)); }; }; }; return new __Record$64_69_6d_61_70_O(new String[]{"dimap"}, __field0); } }).get(); }; }
public static final Object strongCostar = __init$strongCostar();
    private static Object __init$strongCostar() { return (java.util.function.Function<Object, Object>) (dictComonad_0$r0) -> { Object Extend0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_0$r0).get("Extend0"))).apply(null /* TODO: PrimUndefined */); Object Functor0_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Extend0_1$r1).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object profunctorCostar1_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Costar.profunctorCostar)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Extend0_1$r1).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_4$r4) -> { return (java.util.function.Function<Object, Object>) (x_5$r5) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (v_4$r4)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_2$r2).get("map"))).apply(__M$Data_Tuple.fst))).apply(x_5$r5)), ((__M$Data_Tuple.Tuple) (Object)(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_0$r0).get("extract"))).apply(x_5$r5))).value1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_4$r6) -> { return (java.util.function.Function<Object, Object>) (x_5$r7) -> { return new __M$Data_Tuple.Tuple(((__M$Data_Tuple.Tuple) (Object)(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_0$r0).get("extract"))).apply(x_5$r7))).value0, ((java.util.function.Function<Object, Object>) (v_4$r6)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_2$r2).get("map"))).apply(__M$Data_Tuple.snd))).apply(x_5$r7))); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_4$r8) -> { return profunctorCostar1_3$r3; }; return new __Record$50_72_6f_66_75_6e_63_74_6f_72_30_O$66_69_72_73_74_O$73_65_63_6f_6e_64_O(new String[]{"first", "second", "Profunctor0"}, __field2, __field0, __field1); } }).get(); }; }
public static final Object newtypeCostar = __init$newtypeCostar();
    private static Object __init$newtypeCostar() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object hoistCostar = __init$hoistCostar();
    private static Object __init$hoistCostar() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0$r0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(v_1$r1))).apply((java.util.function.Function<Object, Object>) (x_2$r2) -> { return x_2$r2; })); }; }; }
public static final Object functorCostar = __init$functorCostar();
    private static Object __init$functorCostar() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(f_0$r0))).apply(v_1$r1); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }
public static final Object invariantCostar = __init$invariantCostar();
    private static Object __init$invariantCostar() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Invariant.imapF)).apply(__M$Data_Functor_Costar.functorCostar); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get(); }
private static Object __lazy_value_distributiveCostar;
private static int __lazy_state_distributiveCostar;
private static Object __lazy_get_distributiveCostar() { if (__lazy_state_distributiveCostar == 2) return __lazy_value_distributiveCostar; if (__lazy_state_distributiveCostar == 1) throw new IllegalStateException("Recursive initialization of distributiveCostar"); __lazy_state_distributiveCostar = 1; __lazy_value_distributiveCostar = (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply((java.util.function.Function<Object, Object>) (v_3$r3) -> { return ((java.util.function.Function<Object, Object>) (v_3$r3)).apply(a_2$r2); }))).apply(f_1$r1); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (dictFunctor_0$r4) -> { return (java.util.function.Function<Object, Object>) (f_1$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_Functor_Costar.__lazy_get_distributiveCostar()).get("distribute"))).apply(dictFunctor_0$r4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r4).get("map"))).apply(f_1$r5)); }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r6) -> { return __M$Data_Functor_Costar.functorCostar; }; return new __Record$46_75_6e_63_74_6f_72_30_O$63_6f_6c_6c_65_63_74_O$64_69_73_74_72_69_62_75_74_65_O(new String[]{"distribute", "collect", "Functor0"}, __field2, __field1, __field0); } }).get(); __lazy_state_distributiveCostar = 2; return __lazy_value_distributiveCostar; }
public static final Object distributiveCostar = __init$distributiveCostar();
    private static Object __init$distributiveCostar() { return __lazy_get_distributiveCostar(); }
public static final Object closedCostar = __init$closedCostar();
    private static Object __init$closedCostar() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { Object profunctorCostar1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Costar.profunctorCostar)).apply(dictFunctor_0$r0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return (java.util.function.Function<Object, Object>) (g_3$r3) -> { return (java.util.function.Function<Object, Object>) (x_4$r4) -> { return ((java.util.function.Function<Object, Object>) (v_2$r2)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply((java.util.function.Function<Object, Object>) (v1_5$r5) -> { return ((java.util.function.Function<Object, Object>) (v1_5$r5)).apply(x_4$r4); }))).apply(g_3$r3)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r6) -> { return profunctorCostar1_1$r1; }; return new __Record$50_72_6f_66_75_6e_63_74_6f_72_30_O$63_6c_6f_73_65_64_O(new String[]{"closed", "Profunctor0"}, __field1, __field0); } }).get(); }; }
public static final Object categoryCostar = __init$categoryCostar();
    private static Object __init$categoryCostar() { return (java.util.function.Function<Object, Object>) (dictComonad_0$r0) -> { Object semigroupoidCostar1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Costar.semigroupoidCostar)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonad_0$r0).get("Extend0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad.extract)).apply(dictComonad_0$r0); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r2) -> { return semigroupoidCostar1_1$r1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_6f_69_64_30_O$69_64_65_6e_74_69_74_79_O(new String[]{"identity", "Semigroupoid0"}, __field1, __field0); } }).get(); }; }
public static final Object bifunctorCostar = __init$bifunctorCostar();
    private static Object __init$bifunctorCostar() { return (java.util.function.Function<Object, Object>) (dictContravariant_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (g_2$r2) -> { return (java.util.function.Function<Object, Object>) (v_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictContravariant_0$r0).get("cmap"))).apply(f_1$r1)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(v_3$r3))).apply(g_2$r2)); }; }; }; return new __Record$62_69_6d_61_70_O(new String[]{"bimap"}, __field0); } }).get(); }; }
public static final Object applyCostar = __init$applyCostar();
    private static Object __init$applyCostar() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (v1_1$r1) -> { return (java.util.function.Function<Object, Object>) (a_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (v_0$r0)).apply(a_2$r2))).apply(((java.util.function.Function<Object, Object>) (v1_1$r1)).apply(a_2$r2)); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r3) -> { return __M$Data_Functor_Costar.functorCostar; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object bindCostar = __init$bindCostar();
    private static Object __init$bindCostar() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (x_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_1$r1)).apply(((java.util.function.Function<Object, Object>) (v_0$r0)).apply(x_2$r2)))).apply(x_2$r2); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r3) -> { return __M$Data_Functor_Costar.applyCostar; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get(); }
public static final Object applicativeCostar = __init$applicativeCostar();
    private static Object __init$applicativeCostar() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (a_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return a_0$r0; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r2) -> { return __M$Data_Functor_Costar.applyCostar; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); }
public static final Object monadCostar = __init$monadCostar();
    private static Object __init$monadCostar() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Functor_Costar.applicativeCostar; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r1) -> { return __M$Data_Functor_Costar.bindCostar; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get(); }
}
