public class __M$Effect_Class_Console {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Effect.Class.Console"); }
    };


public static final Object warnShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { Object liftEffect_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0); return (java.util.function.Function<Object, Object>) (dictShow_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.warnShow)).apply(dictShow_2_i2)); }; };
public static final Object warn = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.warn); };
public static final Object timeLog = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.timeLog); };
public static final Object timeEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.timeEnd); };
public static final Object time = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.time); };
public static final Object logShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { Object liftEffect_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0); return (java.util.function.Function<Object, Object>) (dictShow_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.logShow)).apply(dictShow_2_i2)); }; };
public static final Object log = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; }); };
public static final Object infoShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { Object liftEffect_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0); return (java.util.function.Function<Object, Object>) (dictShow_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.infoShow)).apply(dictShow_2_i2)); }; };
public static final Object info = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.info); };
public static final Object groupEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(__M$Effect_Console.groupEnd); };
public static final Object groupCollapsed = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.groupCollapsed); };
public static final Object group = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.group); };
public static final Object grouped = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { Object Monad0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0_i0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1_i1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object groupEnd1_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class_Console.groupEnd)).apply(dictMonadEffect_0_i0); Object Applicative0_4_i4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Monad0_1_i1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (name_5_i5) -> { return (java.util.function.Function<Object, Object>) (inner_6_i6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Bind.bind)).apply(Bind1_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.group))).apply(name_5_i5)))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_7_i7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Bind1_2_i2).get("bind"))).apply(inner_6_i6))).apply((java.util.function.Function<Object, Object>) (result_8_i8) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Bind.bind)).apply(Bind1_2_i2))).apply(groupEnd1_3_i3))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_9_i9) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Applicative0_4_i4).get("pure"))).apply(result_8_i8); }); }); }); }; }; };
public static final Object errorShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { Object liftEffect_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0); return (java.util.function.Function<Object, Object>) (dictShow_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.errorShow)).apply(dictShow_2_i2)); }; };
public static final Object error = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.error); };
public static final Object debugShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { Object liftEffect_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0); return (java.util.function.Function<Object, Object>) (dictShow_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(liftEffect_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Console.debugShow)).apply(dictShow_2_i2)); }; };
public static final Object debug = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(dictMonadEffect_0_i0)))).apply(__M$Effect_Console.debug); };
public static final Object clear = (java.util.function.Function<Object, Object>) (dictMonadEffect_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictMonadEffect_0_i0).get("liftEffect"))).apply(__M$Effect_Console.clear); };
}
