public class __M$Data_Semigroup_Foldable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Semigroup.Foldable"); }
    };


public static final class FoldRight1 {
            public final Object value0;
            public final Object value1;
            public FoldRight1(Object value0, Object value1){
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object JoinWith = __init$JoinWith();
    private static Object __init$JoinWith() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; }; }
public static final Object FoldRight1 = __init$FoldRight1();
    private static Object __init$FoldRight1() { return (java.util.function.Function<Object, Object>) (value0_i0) -> (java.util.function.Function<Object, Object>) (value1_i1) -> { return new __M$Data_Semigroup_Foldable.FoldRight1(value0_i0, value1_i1); }; }
public static final Object Act = __init$Act();
    private static Object __init$Act() { return (java.util.function.Function<Object, Object>) (x_0_i0) -> { return x_0_i0; }; }
public static final Object semigroupJoinWith = __init$semigroupJoinWith();
    private static Object __init$semigroupJoinWith() { return (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { return (java.util.function.Function<Object, Object>) (j_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0_i0).get("append"))).apply(((java.util.function.Function<Object, Object>) (v_1_i1)).apply(j_3_i3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0_i0).get("append"))).apply(j_3_i3))).apply(((java.util.function.Function<Object, Object>) (v1_2_i2)).apply(j_3_i3))); }; }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }; }
public static final Object semigroupAct = __init$semigroupAct();
    private static Object __init$semigroupAct() { return (java.util.function.Function<Object, Object>) (dictApply_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Apply.applySecond)).apply(dictApply_0_i0))).apply(v_1_i1))).apply(v1_2_i2); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }; }
public static final Object runFoldRight1 = __init$runFoldRight1();
    private static Object __init$runFoldRight1() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((__M$Data_Semigroup_Foldable.FoldRight1) (Object)(v_0_i0)).value0)).apply(((__M$Data_Semigroup_Foldable.FoldRight1) (Object)(v_0_i0)).value1); }; }
public static final Object mkFoldRight1 = __init$mkFoldRight1();
    private static Object __init$mkFoldRight1() { return ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.FoldRight1)).apply(__M$Data_Function.$const); }
public static final Object getAct = __init$getAct();
    private static Object __init$getAct() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return v_0_i0; }; }
public static final Object foldr1 = __init$foldr1();
    private static Object __init$foldr1() { return (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("foldr1"); }; }
public static final Object foldl1 = __init$foldl1();
    private static Object __init$foldl1() { return (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("foldl1"); }; }
public static final Object maximumBy = __init$maximumBy();
    private static Object __init$maximumBy() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (cmp_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldl1"))).apply((java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return ( ((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (cmp_1_i1)).apply(x_2_i2))).apply(y_3_i3))) instanceof __M$Data_Ordering.GT))) ? x_2_i2 : y_3_i3); }; }); }; }; }
public static final Object minimumBy = __init$minimumBy();
    private static Object __init$minimumBy() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (cmp_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldl1"))).apply((java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return ( ((Boolean) ((((Object) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (cmp_1_i1)).apply(x_2_i2))).apply(y_3_i3))) instanceof __M$Data_Ordering.LT))) ? x_2_i2 : y_3_i3); }; }); }; }; }
public static final Object foldableTuple = __init$foldableTuple();
    private static Object __init$foldableTuple() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(((__M$Data_Tuple.Tuple) (Object)(v_2_i2)).value1); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0_i3) -> { return (java.util.function.Function<Object, Object>) (v1_1_i4) -> { return ((__M$Data_Tuple.Tuple) (Object)(v1_1_i4)).value1; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (v_0_i5) -> { return (java.util.function.Function<Object, Object>) (v1_1_i6) -> { return ((__M$Data_Tuple.Tuple) (Object)(v1_1_i6)).value1; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i7) -> { return __M$Data_Foldable.foldableTuple; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldMap1", "foldr1", "foldl1", "Foldable0"}, __field3, __field0, __field2, __field1); } }).get(); }
public static final Object foldableMultiplicative = __init$foldableMultiplicative();
    private static Object __init$foldableMultiplicative() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return v1_1_i1; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0_i2) -> { return (java.util.function.Function<Object, Object>) (v1_1_i3) -> { return v1_1_i3; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i4) -> { return (java.util.function.Function<Object, Object>) (f_1_i5) -> { return (java.util.function.Function<Object, Object>) (v_2_i6) -> { return ((java.util.function.Function<Object, Object>) (f_1_i5)).apply(v_2_i6); }; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i7) -> { return __M$Data_Foldable.foldableMultiplicative; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldr1", "foldl1", "foldMap1", "Foldable0"}, __field3, __field2, __field1, __field0); } }).get(); }
public static final Object foldableIdentity = __init$foldableIdentity();
    private static Object __init$foldableIdentity() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return (java.util.function.Function<Object, Object>) (f_1_i1) -> { return (java.util.function.Function<Object, Object>) (v_2_i2) -> { return ((java.util.function.Function<Object, Object>) (f_1_i1)).apply(v_2_i2); }; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0_i3) -> { return (java.util.function.Function<Object, Object>) (v1_1_i4) -> { return v1_1_i4; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (v_0_i5) -> { return (java.util.function.Function<Object, Object>) (v1_1_i6) -> { return v1_1_i6; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i7) -> { return __M$Data_Foldable.foldableIdentity; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldMap1", "foldl1", "foldr1", "Foldable0"}, __field3, __field0, __field1, __field2); } }).get(); }
public static final Object foldableDual = __init$foldableDual();
    private static Object __init$foldableDual() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return v1_1_i1; }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (v_0_i2) -> { return (java.util.function.Function<Object, Object>) (v1_1_i3) -> { return v1_1_i3; }; }; final Object __field2 = (java.util.function.Function<Object, Object>) (dictSemigroup_0_i4) -> { return (java.util.function.Function<Object, Object>) (f_1_i5) -> { return (java.util.function.Function<Object, Object>) (v_2_i6) -> { return ((java.util.function.Function<Object, Object>) (f_1_i5)).apply(v_2_i6); }; }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i7) -> { return __M$Data_Foldable.foldableDual; }; return new __Record$46_6f_6c_64_61_62_6c_65_30_O$66_6f_6c_64_4d_61_70_31_O$66_6f_6c_64_6c_31_O$66_6f_6c_64_72_31_O(new String[]{"foldr1", "foldl1", "foldMap1", "Foldable0"}, __field3, __field2, __field1, __field0); } }).get(); }
public static final Object foldRight1Semigroup = __init$foldRight1Semigroup();
    private static Object __init$foldRight1Semigroup() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { Object __local_var_2_i2 = ((__M$Data_Semigroup_Foldable.FoldRight1) (Object)(v_0_i0)).value1; return new __M$Data_Semigroup_Foldable.FoldRight1((java.util.function.Function<Object, Object>) (a_3_i3) -> { return (java.util.function.Function<Object, Object>) (f_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((__M$Data_Semigroup_Foldable.FoldRight1) (Object)(v_0_i0)).value0)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_4_i4)).apply(__local_var_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((__M$Data_Semigroup_Foldable.FoldRight1) (Object)(v1_1_i1)).value0)).apply(a_3_i3))).apply(f_4_i4))))).apply(f_4_i4); }; }, ((__M$Data_Semigroup_Foldable.FoldRight1) (Object)(v1_1_i1)).value1); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }
public static final Object foldMap1DefaultR = __init$foldMap1DefaultR();
    private static Object __init$foldMap1DefaultR() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_1_i1) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_2_i2) -> { Object append_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.append)).apply(dictSemigroup_2_i2); return (java.util.function.Function<Object, Object>) (f_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_1_i1).get("map"))).apply(f_4_i4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldr1"))).apply(append_3_i3)); }; }; }; }; }
public static final Object foldMap1DefaultL = __init$foldMap1DefaultL();
    private static Object __init$foldMap1DefaultL() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_1_i1) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_2_i2) -> { Object append_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup.append)).apply(dictSemigroup_2_i2); return (java.util.function.Function<Object, Object>) (f_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.composeFlipped)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_1_i1).get("map"))).apply(f_4_i4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldl1"))).apply(append_3_i3)); }; }; }; }; }
public static final Object foldMap1 = __init$foldMap1();
    private static Object __init$foldMap1() { return (java.util.function.Function<Object, Object>) (dict_0_i0) -> { return ((java.util.Map<String, Object>) dict_0_i0).get("foldMap1"); }; }
public static final Object foldl1Default = __init$foldl1Default();
    private static Object __init$foldl1Default() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Semigroup_Foldable.runFoldRight1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.foldMap1)).apply(dictFoldable1_0_i0))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Monoid_Dual.semigroupDual)).apply(__M$Data_Semigroup_Foldable.foldRight1Semigroup))))).apply(__M$Data_Semigroup_Foldable.mkFoldRight1)); return (java.util.function.Function<Object, Object>) (b_2_i2) -> { return (java.util.function.Function<Object, Object>) (a_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(a_3_i3))).apply(b_2_i2); }; }; } }).get()))).apply(__M$Data_Function.flip); }; }
public static final Object foldr1Default = __init$foldr1Default();
    private static Object __init$foldr1Default() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Semigroup_Foldable.runFoldRight1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldMap1"))).apply(__M$Data_Semigroup_Foldable.foldRight1Semigroup))).apply(__M$Data_Semigroup_Foldable.mkFoldRight1)); return (java.util.function.Function<Object, Object>) (b_2_i2) -> { return (java.util.function.Function<Object, Object>) (a_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(a_3_i3))).apply(b_2_i2); }; }; }; }
public static final Object intercalateMap = __init$intercalateMap();
    private static Object __init$intercalateMap() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1_i1) -> { return __M$Data_Semigroup_Foldable.__direct$23(dictFoldable1_0_i0, dictSemigroup_1_i1); }; }; }
private static Object __direct$23(Object dictFoldable1_0_i0, Object dictSemigroup_1_i1) { Object semigroupJoinWith1_2_i2 = ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.semigroupJoinWith)).apply(dictSemigroup_1_i1); return (java.util.function.Function<Object, Object>) (j_3_i3) -> { return (java.util.function.Function<Object, Object>) (f_4_i4) -> { return (java.util.function.Function<Object, Object>) (foldable_5_i5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldMap1"))).apply(semigroupJoinWith1_2_i2))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Semigroup_Foldable.JoinWith))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Function.$const))).apply(f_4_i4))))).apply(foldable_5_i5))).apply(j_3_i3); }; }; }; }
public static final Object intercalate = __init$intercalate();
    private static Object __init$intercalate() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1_i1) -> { Object __local_var_2_i2 = ( ((Boolean) ((__M$Data_Semigroup_Foldable.intercalateMap == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.intercalateMap)).apply(dictFoldable1_0_i0))).apply(dictSemigroup_1_i1) : __M$Data_Semigroup_Foldable.__direct$23(dictFoldable1_0_i0, dictSemigroup_1_i1)); Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (a_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_2_i2)).apply(a_4_i4))).apply(__local_var_3_i3); }; }; }; }
public static final Object maximum = __init$maximum();
    private static Object __init$maximum() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { Object semigroupMax_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Ord_Max.semigroupMax)).apply(dictOrd_0_i0); return (java.util.function.Function<Object, Object>) (dictFoldable1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.foldMap1)).apply(dictFoldable1_2_i2))).apply(semigroupMax_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Newtype.wrap)).apply(null /* TODO: PrimUndefined */)); }; }; }
public static final Object minimum = __init$minimum();
    private static Object __init$minimum() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { Object semigroupMin_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Ord_Min.semigroupMin)).apply(dictOrd_0_i0); return (java.util.function.Function<Object, Object>) (dictFoldable1_2_i2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.foldMap1)).apply(dictFoldable1_2_i2))).apply(semigroupMin_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Newtype.wrap)).apply(null /* TODO: PrimUndefined */)); }; }; }
public static final Object traverse1_ = __init$traverse1_();
    private static Object __init$traverse1_() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictApply_1_i1) -> { return __M$Data_Semigroup_Foldable.__direct$27(dictFoldable1_0_i0, dictApply_1_i1); }; }; }
private static Object __direct$27(Object dictFoldable1_0_i0, Object dictApply_1_i1) { Object Functor0_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_1_i1).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object semigroupAct1_3_i3 = ((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.semigroupAct)).apply(dictApply_1_i1); return (java.util.function.Function<Object, Object>) (f_4_i4) -> { return (java.util.function.Function<Object, Object>) (t_5_i5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_2_i2).get("map"))).apply((java.util.function.Function<Object, Object>) (v_6_i6) -> { return __M$Data_Unit.unit; }))).apply(((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.getAct)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldMap1"))).apply(semigroupAct1_3_i3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Semigroup_Foldable.Act))).apply(f_4_i4)))).apply(t_5_i5))); }; }; }
public static final Object for1_ = __init$for1_();
    private static Object __init$for1_() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictApply_1_i1) -> { Object __local_var_2_i2 = ( ((Boolean) ((__M$Data_Semigroup_Foldable.traverse1_ == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.traverse1_)).apply(dictFoldable1_0_i0))).apply(dictApply_1_i1) : __M$Data_Semigroup_Foldable.__direct$27(dictFoldable1_0_i0, dictApply_1_i1)); return (java.util.function.Function<Object, Object>) (b_3_i3) -> { return (java.util.function.Function<Object, Object>) (a_4_i4) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__local_var_2_i2)).apply(a_4_i4))).apply(b_3_i3); }; }; }; }; }
public static final Object sequence1_ = __init$sequence1_();
    private static Object __init$sequence1_() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictApply_1_i1) -> { return ((java.util.function.Function<Object, Object>) (( ((Boolean) ((__M$Data_Semigroup_Foldable.traverse1_ == null))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Semigroup_Foldable.traverse1_)).apply(dictFoldable1_0_i0))).apply(dictApply_1_i1) : __M$Data_Semigroup_Foldable.__direct$27(dictFoldable1_0_i0, dictApply_1_i1)))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn)); }; }; }
public static final Object fold1 = __init$fold1();
    private static Object __init$fold1() { return (java.util.function.Function<Object, Object>) (dictFoldable1_0_i0) -> { return (java.util.function.Function<Object, Object>) (dictSemigroup_1_i1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable1_0_i0).get("foldMap1"))).apply(dictSemigroup_1_i1))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn)); }; }; }
}
