public class __M$Data_List_Lazy_NonEmpty {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.List.Lazy.NonEmpty"); }
    };


public static final Object uncons = __init$uncons();
    private static Object __init$uncons() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { Object v1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0$r0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value0; final Object __field1 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value1; return new __Record$68_65_61_64_O$74_61_69_6c_O(new String[]{"head", "tail"}, __field0, __field1); } }).get(); }; }
public static final Object toList = __init$toList();
    private static Object __init$toList() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { Object v1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0$r0); Object __local_var_2$r2 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value0; Object __local_var_3$r3 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value1; return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_4$r4) -> { return new __M$Data_List_Lazy_Types.Cons(__local_var_2$r2, __local_var_3$r3); }); }; }
public static final Object toUnfoldable = __init$toUnfoldable();
    private static Object __init$toUnfoldable() { return (java.util.function.Function<Object, Object>) (dictUnfoldable_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictUnfoldable_0$r0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (xs_1$r1) -> { Object __local_var_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.uncons)).apply(xs_1$r1); return ( ((Boolean) ((((Object) (__local_var_2$r2)) instanceof __M$Data_Maybe.Just))) ? new __M$Data_Maybe.Just(new __M$Data_Tuple.Tuple(((java.util.Map<String, Object>) ((__M$Data_Maybe.Just) (Object)(__local_var_2$r2)).value0).get("head"), ((java.util.Map<String, Object>) ((__M$Data_Maybe.Just) (Object)(__local_var_2$r2)).value0).get("tail"))) : __M$Data_Maybe.__singleton$Nothing.value); })))).apply(__M$Data_List_Lazy_NonEmpty.toList); }; }
public static final Object tail = __init$tail();
    private static Object __init$tail() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { return ((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0$r0))).value1; }; }
public static final Object singleton = __init$singleton();
    private static Object __init$singleton() { return (java.util.function.Function<Object, Object>) (a_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_1$r1) -> { return new __M$Data_NonEmpty.NonEmpty(a_0$r0, __M$Data_List_Lazy_Types.nil); }); }; }
public static final Object repeat = __init$repeat();
    private static Object __init$repeat() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_1$r1) -> { return new __M$Data_NonEmpty.NonEmpty(x_0$r0, ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.repeat)).apply(x_0$r0)); }); }; }
public static final Object length = __init$length();
    private static Object __init$length() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { return (((int) (1)) + ((int) (((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.length)).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0$r0))).value1)))); }; }
public static final Object last = __init$last();
    private static Object __init$last() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { Object v1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0$r0); Object __local_var_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.last)).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value1); return ( ((Boolean) ((((Object) (__local_var_2$r2)) instanceof __M$Data_Maybe.Nothing))) ? ((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value0 : ( ((Boolean) ((((Object) (__local_var_2$r2)) instanceof __M$Data_Maybe.Just))) ? ((__M$Data_Maybe.Just) (Object)(__local_var_2$r2)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }
public static final Object iterate = __init$iterate();
    private static Object __init$iterate() { return (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (x_1$r1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_2$r2) -> { return new __M$Data_NonEmpty.NonEmpty(x_1$r1, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.iterate)).apply(f_0$r0))).apply(((java.util.function.Function<Object, Object>) (f_0$r0)).apply(x_1$r1))); }); }; }; }
public static final Object init = __init$init();
    private static Object __init$init() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { { Object v1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0$r0); Object __local_var_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.init)).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value1); if ((Boolean) ((((Object) (__local_var_2$r2)) instanceof __M$Data_Maybe.Nothing))) { return __M$Data_List_Lazy_Types.nil; } else { {  if ((Boolean) ((((Object) (__local_var_2$r2)) instanceof __M$Data_Maybe.Just))) { { Object __local_var_3$r3 = ((__M$Data_Maybe.Just) (Object)(__local_var_2$r2)).value0; return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_4$r4) -> { return new __M$Data_List_Lazy_Types.Cons(((__M$Data_NonEmpty.NonEmpty) (Object)(v1_1$r1)).value0, __local_var_3$r3); }); } } else { return (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get(); } } } }  }; }
public static final Object head = __init$head();
    private static Object __init$head() { return (java.util.function.Function<Object, Object>) (v_0$r0) -> { return ((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_0$r0))).value0; }; }
public static final Object fromList = __init$fromList();
    private static Object __init$fromList() { return (java.util.function.Function<Object, Object>) (l_0$r0) -> { { Object v_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy_Types.step)).apply(l_0$r0); if ((Boolean) ((((Object) (v_1$r1)) instanceof __M$Data_List_Lazy_Types.Nil))) { return __M$Data_Maybe.__singleton$Nothing.value; } else { {  if ((Boolean) ((((Object) (v_1$r1)) instanceof __M$Data_List_Lazy_Types.Cons))) { { Object __local_var_2$r2 = ((__M$Data_List_Lazy_Types.Cons) (Object)(v_1$r1)).value0; Object __local_var_3$r3 = ((__M$Data_List_Lazy_Types.Cons) (Object)(v_1$r1)).value1; return new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v1_4$r4) -> { return new __M$Data_NonEmpty.NonEmpty(__local_var_2$r2, __local_var_3$r3); })); } } else { return (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get(); } } } }  }; }
public static final Object fromFoldable = __init$fromFoldable();
    private static Object __init$fromFoldable() { return (java.util.function.Function<Object, Object>) (dictFoldable_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_List_Lazy_NonEmpty.fromList))).apply(((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy.fromFoldable)).apply(dictFoldable_0$r0)); }; }
public static final Object cons = __init$cons();
    private static Object __init$cons() { return (java.util.function.Function<Object, Object>) (y_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v1_2$r2) -> { Object v2_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(v_1$r1); Object __local_var_4$r4 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v2_3$r3)).value0; Object __local_var_5$r5 = ((__M$Data_NonEmpty.NonEmpty) (Object)(v2_3$r3)).value1; return new __M$Data_NonEmpty.NonEmpty(y_0$r0, ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_6$r6) -> { return new __M$Data_List_Lazy_Types.Cons(__local_var_4$r4, __local_var_5$r5); })); }); }; }; }
public static final Object concatMap = __init$concatMap();
    private static Object __init$concatMap() { return (java.util.function.Function<Object, Object>) (b_0$r0) -> { return (java.util.function.Function<Object, Object>) (a_1$r1) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_List_Lazy_Types.bindNonEmptyList).get("bind"))).apply(a_1$r1))).apply(b_0$r0); }; }; }
public static final Object appendFoldable = __init$appendFoldable();
    private static Object __init$appendFoldable() { return (java.util.function.Function<Object, Object>) (dictFoldable_0$r0) -> { return (java.util.function.Function<Object, Object>) (nel_1$r1) -> { return (java.util.function.Function<Object, Object>) (ys_2$r2) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_3$r3) -> { return new __M$Data_NonEmpty.NonEmpty(((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(nel_1$r1))).value0, (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_4$r4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFoldable_0$r0).get("foldr"))).apply(__M$Data_List_Lazy_Types.cons))).apply(__M$Data_List_Lazy_Types.nil))).apply(ys_2$r2); Object __local_var_5$r5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Safe_Coerce.coerce)).apply(null /* TODO: PrimUndefined */))).apply(((__M$Data_NonEmpty.NonEmpty) (Object)(((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(nel_1$r1))).value1); return ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.defer)).apply((java.util.function.Function<Object, Object>) (v_6$r6) -> { Object __local_var_7$r7 = ((java.util.function.Function<Object, Object>) (__M$Data_Lazy.force)).apply(__local_var_5$r5); return ( ((Boolean) ((((Object) (__local_var_7$r7)) instanceof __M$Data_List_Lazy_Types.Nil))) ? ((java.util.function.Function<Object, Object>) (__M$Data_List_Lazy_Types.step)).apply(__local_var_4$r4) : ( ((Boolean) ((((Object) (__local_var_7$r7)) instanceof __M$Data_List_Lazy_Types.Cons))) ? new __M$Data_List_Lazy_Types.Cons(((__M$Data_List_Lazy_Types.Cons) (Object)(__local_var_7$r7)).value0, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) __M$Data_List_Lazy_Types.semigroupList).get("append"))).apply(((__M$Data_List_Lazy_Types.Cons) (Object)(__local_var_7$r7)).value1))).apply(__local_var_4$r4)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }); } }).get()); }); }; }; }; }
}
