public class __M$Data_Maybe {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Maybe"); }
    };


public static final class Nothing {
            
            public Nothing(){
                
            }
        }
public static final class __singleton$Nothing {
    public static final Nothing value = new Nothing();
}
public static final class Just {
            public final Object value0;
            public Just(Object value0){
                this.value0 = value0;
            }
        }
public static final Object Nothing = __init$Nothing();
    private static Object __init$Nothing() { return __M$Data_Maybe.__singleton$Nothing.value; }
public static final Object Just = __init$Just();
    private static Object __init$Just() { return (java.util.function.Function<Object, Object>) (value0_i0) -> { return new __M$Data_Maybe.Just(value0_i0); }; }
public static final Object showMaybe = __init$showMaybe();
    private static Object __init$showMaybe() { return (java.util.function.Function<Object, Object>) (dictShow_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ( ((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_Maybe.Just))) ? (((String) ((((String) ("(Just ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0_i0).get("show"))).apply(((__M$Data_Maybe.Just) (Object)(v_1_i1)).value0)))))) + ((String) (")"))) : ( ((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_Maybe.Nothing))) ? "Nothing" : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object semigroupMaybe = __init$semigroupMaybe();
    private static Object __init$semigroupMaybe() { return (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1_i1) -> { return (java.util.function.Function<Object, Object>) (v1_2_i2) -> { return ( ((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_Maybe.Nothing))) ? v1_2_i2 : ( ((Boolean) ((((Object) (v1_2_i2)) instanceof __M$Data_Maybe.Nothing))) ? v_1_i1 : ( ((Boolean) ((((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_Maybe.Just))) && ((Boolean) ((((Object) (v1_2_i2)) instanceof __M$Data_Maybe.Just)))))) ? new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemigroup_0_i0).get("append"))).apply(((__M$Data_Maybe.Just) (Object)(v_1_i1)).value0))).apply(((__M$Data_Maybe.Just) (Object)(v1_2_i2)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; return new __Record$61_70_70_65_6e_64_O(new String[]{"append"}, __field0); } }).get(); }; }
public static final Object optional = __init$optional();
    private static Object __init$optional() { return (java.util.function.Function<Object, Object>) (dictAlt_0_i0) -> { Object Functor0_1_i1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0_i0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictApplicative_2_i2) -> { return (java.util.function.Function<Object, Object>) (a_3_i3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0_i0).get("alt"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1_i1).get("map"))).apply(__M$Data_Maybe.Just))).apply(a_3_i3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_2_i2).get("pure"))).apply(__M$Data_Maybe.__singleton$Nothing.value)); }; }; }; }
public static final Object monoidMaybe = __init$monoidMaybe();
    private static Object __init$monoidMaybe() { return (java.util.function.Function<Object, Object>) (dictSemigroup_0_i0) -> { Object semigroupMaybe1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Maybe.semigroupMaybe)).apply(dictSemigroup_0_i0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Maybe.__singleton$Nothing.value; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i2) -> { return semigroupMaybe1_1_i1; }; return new __Record$53_65_6d_69_67_72_6f_75_70_30_O$6d_65_6d_70_74_79_O(new String[]{"mempty", "Semigroup0"}, __field1, __field0); } }).get(); }; }
public static final Object maybeprime = __init$maybeprime();
    private static Object __init$maybeprime() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (java.util.function.Function<Object, Object>) (v2_2_i2) -> { return ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Maybe.Nothing))) ? ((java.util.function.Function<Object, Object>) (v_0_i0)).apply(__M$Data_Unit.unit) : ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1_i1)).apply(((__M$Data_Maybe.Just) (Object)(v2_2_i2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; }; }
public static final Object maybe = __init$maybe();
    private static Object __init$maybe() { return (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return (java.util.function.Function<Object, Object>) (v2_2_i2) -> { return ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Maybe.Nothing))) ? v_0_i0 : ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1_i1)).apply(((__M$Data_Maybe.Just) (Object)(v2_2_i2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; }; }
public static final Object isNothing = __init$isNothing();
    private static Object __init$isNothing() { return (java.util.function.Function<Object, Object>) (v2_0_i0) -> { return ( ((Boolean) ((((Object) (v2_0_i0)) instanceof __M$Data_Maybe.Nothing))) ? true : ( ((Boolean) ((((Object) (v2_0_i0)) instanceof __M$Data_Maybe.Just))) ? false : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }
public static final Object isJust = __init$isJust();
    private static Object __init$isJust() { return (java.util.function.Function<Object, Object>) (v2_0_i0) -> { return ( ((Boolean) ((((Object) (v2_0_i0)) instanceof __M$Data_Maybe.Nothing))) ? false : ( ((Boolean) ((((Object) (v2_0_i0)) instanceof __M$Data_Maybe.Just))) ? true : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }
public static final Object genericMaybe = __init$genericMaybe();
    private static Object __init$genericMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_0_i0) -> { return ( ((Boolean) ((((Object) (x_0_i0)) instanceof __M$Data_Generic_Rep.Inl))) ? __M$Data_Maybe.__singleton$Nothing.value : ( ((Boolean) ((((Object) (x_0_i0)) instanceof __M$Data_Generic_Rep.Inr))) ? new __M$Data_Maybe.Just(((__M$Data_Generic_Rep.Inr) (Object)(x_0_i0)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; final Object __field1 = (java.util.function.Function<Object, Object>) (x_0_i1) -> { return ( ((Boolean) ((((Object) (x_0_i1)) instanceof __M$Data_Maybe.Nothing))) ? new __M$Data_Generic_Rep.Inl(__M$Data_Generic_Rep.__singleton$NoArguments.value) : ( ((Boolean) ((((Object) (x_0_i1)) instanceof __M$Data_Maybe.Just))) ? new __M$Data_Generic_Rep.Inr(((__M$Data_Maybe.Just) (Object)(x_0_i1)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; return new __Record$66_72_6f_6d_O$74_6f_O(new String[]{"to", "from"}, __field1, __field0); } }).get(); }
public static final Object functorMaybe = __init$functorMaybe();
    private static Object __init$functorMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Maybe.Just))) ? new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0_i0)).apply(((__M$Data_Maybe.Just) (Object)(v1_1_i1)).value0)) : __M$Data_Maybe.__singleton$Nothing.value); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }
public static final Object invariantMaybe = __init$invariantMaybe();
    private static Object __init$invariantMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Invariant.imapF)).apply(__M$Data_Maybe.functorMaybe); return new __Record$69_6d_61_70_O(new String[]{"imap"}, __field0); } }).get(); }
public static final Object fromMaybeprime = __init$fromMaybeprime();
    private static Object __init$fromMaybeprime() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Maybe.maybeprime)).apply(a_0_i0))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn)); }; }
public static final Object fromMaybe = __init$fromMaybe();
    private static Object __init$fromMaybe() { return (java.util.function.Function<Object, Object>) (a_0_i0) -> { Object __local_var_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Control_Category.identity)).apply(__M$Control_Category.categoryFn); return (java.util.function.Function<Object, Object>) (v2_2_i2) -> { return ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Maybe.Nothing))) ? a_0_i0 : ( ((Boolean) ((((Object) (v2_2_i2)) instanceof __M$Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (__local_var_1_i1)).apply(((__M$Data_Maybe.Just) (Object)(v2_2_i2)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; }
public static final Object fromJust = __init$fromJust();
    private static Object __init$fromJust() { return (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return (java.util.function.Function<Object, Object>) (v_1_i1) -> { return ( ((Boolean) ((((Object) (v_1_i1)) instanceof __M$Data_Maybe.Just))) ? ((__M$Data_Maybe.Just) (Object)(v_1_i1)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); }; }; }
public static final Object extendMaybe = __init$extendMaybe();
    private static Object __init$extendMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Maybe.Nothing))) ? __M$Data_Maybe.__singleton$Nothing.value : new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0_i0)).apply(v1_1_i1))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Maybe.functorMaybe; }; return new __Record$46_75_6e_63_74_6f_72_30_O$65_78_74_65_6e_64_O(new String[]{"extend", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object eqMaybe = __init$eqMaybe();
    private static Object __init$eqMaybe() { return (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_1_i1) -> { return (java.util.function.Function<Object, Object>) (y_2_i2) -> { return ( ((Boolean) ((((Object) (x_1_i1)) instanceof __M$Data_Maybe.Nothing))) ? (((Object) (y_2_i2)) instanceof __M$Data_Maybe.Nothing) : (((Boolean) ((((Object) (x_1_i1)) instanceof __M$Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((((Object) (y_2_i2)) instanceof __M$Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq_0_i0).get("eq"))).apply(((__M$Data_Maybe.Just) (Object)(x_1_i1)).value0))).apply(((__M$Data_Maybe.Just) (Object)(y_2_i2)).value0)))))))); }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); }; }
public static final Object ordMaybe = __init$ordMaybe();
    private static Object __init$ordMaybe() { return (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { Object eqMaybe1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Maybe.eqMaybe)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (x_2_i2) -> { return (java.util.function.Function<Object, Object>) (y_3_i3) -> { return ( ((Boolean) ((((Object) (x_2_i2)) instanceof __M$Data_Maybe.Nothing))) ? ( ((Boolean) ((((Object) (y_3_i3)) instanceof __M$Data_Maybe.Nothing))) ? __M$Data_Ordering.__singleton$EQ.value : __M$Data_Ordering.__singleton$LT.value) : ( ((Boolean) ((((Object) (y_3_i3)) instanceof __M$Data_Maybe.Nothing))) ? __M$Data_Ordering.__singleton$GT.value : ( ((Boolean) ((((Boolean) ((((Object) (x_2_i2)) instanceof __M$Data_Maybe.Just))) && ((Boolean) ((((Object) (y_3_i3)) instanceof __M$Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_0_i0).get("compare"))).apply(((__M$Data_Maybe.Just) (Object)(x_2_i2)).value0))).apply(((__M$Data_Maybe.Just) (Object)(y_3_i3)).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i4) -> { return eqMaybe1_1_i1; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; }
public static final Object eq1Maybe = __init$eq1Maybe();
    private static Object __init$eq1Maybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Maybe.eqMaybe)).apply(dictEq_0_i0)); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get(); }
public static final Object ord1Maybe = __init$ord1Maybe();
    private static Object __init$ord1Maybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (__M$Data_Maybe.ordMaybe)).apply(dictOrd_0_i0)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> { return __M$Data_Maybe.eq1Maybe; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get(); }
public static final Object boundedMaybe = __init$boundedMaybe();
    private static Object __init$boundedMaybe() { return (java.util.function.Function<Object, Object>) (dictBounded_0_i0) -> { Object ordMaybe1_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Maybe.ordMaybe)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictBounded_0_i0).get("Ord0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = new __M$Data_Maybe.Just(((java.util.Map<String, Object>) dictBounded_0_i0).get("top")); final Object __field1 = __M$Data_Maybe.__singleton$Nothing.value; final Object __field2 = (java.util.function.Function<Object, Object>) (_dollar___unused_2_i2) -> { return ordMaybe1_1_i1; }; return new __Record$4f_72_64_30_O$62_6f_74_74_6f_6d_O$74_6f_70_O(new String[]{"top", "bottom", "Ord0"}, __field2, __field1, __field0); } }).get(); }; }
public static final Object applyMaybe = __init$applyMaybe();
    private static Object __init$applyMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Maybe.Just))) ? ( ((Boolean) ((((Object) (v1_1_i1)) instanceof __M$Data_Maybe.Just))) ? new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((__M$Data_Maybe.Just) (Object)(v_0_i0)).value0)).apply(((__M$Data_Maybe.Just) (Object)(v1_1_i1)).value0)) : __M$Data_Maybe.__singleton$Nothing.value) : ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Maybe.Nothing))) ? __M$Data_Maybe.__singleton$Nothing.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Maybe.functorMaybe; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object bindMaybe = __init$bindMaybe();
    private static Object __init$bindMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1_i1)).apply(((__M$Data_Maybe.Just) (Object)(v_0_i0)).value0) : ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Maybe.Nothing))) ? __M$Data_Maybe.__singleton$Nothing.value : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Maybe.applyMaybe; }; return new __Record$41_70_70_6c_79_30_O$62_69_6e_64_O(new String[]{"bind", "Apply0"}, __field1, __field0); } }).get(); }
public static final Object semiringMaybe = __init$semiringMaybe();
    private static Object __init$semiringMaybe() { return (java.util.function.Function<Object, Object>) (dictSemiring_0_i0) -> { Object mul_1_i1 = ((java.util.function.Function<Object, Object>) (__M$Data_Semiring.mul)).apply(dictSemiring_0_i0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Maybe.__singleton$Nothing.value; final Object __field1 = new __M$Data_Maybe.Just(((java.util.Map<String, Object>) dictSemiring_0_i0).get("one")); final Object __field2 = (java.util.function.Function<Object, Object>) (v_2_i2) -> { return (java.util.function.Function<Object, Object>) (v1_3_i3) -> { return ( ((Boolean) ((((Object) (v_2_i2)) instanceof __M$Data_Maybe.Nothing))) ? v1_3_i3 : ( ((Boolean) ((((Object) (v1_3_i3)) instanceof __M$Data_Maybe.Nothing))) ? v_2_i2 : ( ((Boolean) ((((Boolean) ((((Object) (v_2_i2)) instanceof __M$Data_Maybe.Just))) && ((Boolean) ((((Object) (v1_3_i3)) instanceof __M$Data_Maybe.Just)))))) ? new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictSemiring_0_i0).get("add"))).apply(((__M$Data_Maybe.Just) (Object)(v_2_i2)).value0))).apply(((__M$Data_Maybe.Just) (Object)(v1_3_i3)).value0)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()))); }; }; final Object __field3 = (java.util.function.Function<Object, Object>) (x_2_i4) -> { return (java.util.function.Function<Object, Object>) (y_3_i5) -> { return ( ((Boolean) ((((Object) (x_2_i4)) instanceof __M$Data_Maybe.Just))) ? ( ((Boolean) ((((Object) (y_3_i5)) instanceof __M$Data_Maybe.Just))) ? new __M$Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (mul_1_i1)).apply(((__M$Data_Maybe.Just) (Object)(x_2_i4)).value0))).apply(((__M$Data_Maybe.Just) (Object)(y_3_i5)).value0)) : __M$Data_Maybe.__singleton$Nothing.value) : __M$Data_Maybe.__singleton$Nothing.value); }; }; return new __Record$61_64_64_O$6d_75_6c_O$6f_6e_65_O$7a_65_72_6f_O(new String[]{"zero", "one", "add", "mul"}, __field2, __field3, __field1, __field0); } }).get(); }; }
public static final Object applicativeMaybe = __init$applicativeMaybe();
    private static Object __init$applicativeMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Maybe.Just; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Maybe.applyMaybe; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); }
public static final Object monadMaybe = __init$monadMaybe();
    private static Object __init$monadMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Maybe.applicativeMaybe; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> { return __M$Data_Maybe.bindMaybe; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$42_69_6e_64_31_O(new String[]{"Applicative0", "Bind1"}, __field0, __field1); } }).get(); }
public static final Object altMaybe = __init$altMaybe();
    private static Object __init$altMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_0_i0) -> { return (java.util.function.Function<Object, Object>) (v1_1_i1) -> { return ( ((Boolean) ((((Object) (v_0_i0)) instanceof __M$Data_Maybe.Nothing))) ? v1_1_i1 : v_0_i0); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i2) -> { return __M$Data_Maybe.functorMaybe; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_6c_74_O(new String[]{"alt", "Functor0"}, __field1, __field0); } }).get(); }
public static final Object plusMaybe = __init$plusMaybe();
    private static Object __init$plusMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Maybe.__singleton$Nothing.value; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Maybe.altMaybe; }; return new __Record$41_6c_74_30_O$65_6d_70_74_79_O(new String[]{"empty", "Alt0"}, __field1, __field0); } }).get(); }
public static final Object alternativeMaybe = __init$alternativeMaybe();
    private static Object __init$alternativeMaybe() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i0) -> { return __M$Data_Maybe.applicativeMaybe; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0_i1) -> { return __M$Data_Maybe.plusMaybe; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$50_6c_75_73_31_O(new String[]{"Applicative0", "Plus1"}, __field0, __field1); } }).get(); }
}
