public class __M$Data_Functor_Compose {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Data.Functor.Compose"); }
    };


public static final Object Compose = __init$Compose();
    private static Object __init$Compose() { return (java.util.function.Function<Object, Object>) (x_0$r0) -> { return x_0$r0; }; }
public static final Object showCompose = __init$showCompose();
    private static Object __init$showCompose() { return (java.util.function.Function<Object, Object>) (dictShow_0$r0) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_1$r1) -> { return (((String) ((((String) ("(Compose ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictShow_0$r0).get("show"))).apply(v_1$r1)))))) + ((String) (")"))); }; return new __Record$73_68_6f_77_O(new String[]{"show"}, __field0); } }).get(); }; }
public static final Object newtypeCompose = __init$newtypeCompose();
    private static Object __init$newtypeCompose() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return null /* TODO: PrimUndefined */; }; return new __Record$43_6f_65_72_63_69_62_6c_65_30_O(new String[]{"Coercible0"}, __field0); } }).get(); }
public static final Object functorCompose = __init$functorCompose();
    private static Object __init$functorCompose() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictFunctor1_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (v_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor1_1$r1).get("map"))).apply(f_2$r2)))).apply(v_3$r3); }; }; return new __Record$6d_61_70_O(new String[]{"map"}, __field0); } }).get(); }; }; }
public static final Object eqCompose = __init$eqCompose();
    private static Object __init$eqCompose() { return (java.util.function.Function<Object, Object>) (dictEq1_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictEq11_1$r1) -> { return (java.util.function.Function<Object, Object>) (dictEq_2$r2) -> { return __M$Data_Functor_Compose.__direct$4(dictEq1_0$r0, dictEq11_1$r1, dictEq_2$r2); }; }; }; }
private static Object __direct$4(Object dictEq1_0$r0, Object dictEq11_1$r1, Object dictEq_2$r2) { Object eqApp1_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Functor_App.eqApp)).apply(dictEq11_1$r1))).apply(dictEq_2$r2); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_4$r4) -> { return (java.util.function.Function<Object, Object>) (v1_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictEq1_0$r0).get("eq1"))).apply(eqApp1_3$r3))).apply(v_4$r4))).apply(v1_5$r5); }; }; return new __Record$65_71_O(new String[]{"eq"}, __field0); } }).get(); }
public static final Object ordCompose = __init$ordCompose();
    private static Object __init$ordCompose() { return (java.util.function.Function<Object, Object>) (dictOrd1_0$r0) -> { Object eqCompose1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.eqCompose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_0$r0).get("Eq10"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictOrd11_2$r2) -> { Object ordApp_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_App.ordApp)).apply(dictOrd11_2$r2); Object eqCompose2_4$r4 = ((java.util.function.Function<Object, Object>) (eqCompose1_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd11_2$r2).get("Eq10"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictOrd_5$r5) -> { Object ordApp1_6$r6 = ((java.util.function.Function<Object, Object>) (ordApp_3$r3)).apply(dictOrd_5$r5); Object eqCompose3_7$r7 = ((java.util.function.Function<Object, Object>) (eqCompose2_4$r4)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd_5$r5).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_8$r8) -> { return (java.util.function.Function<Object, Object>) (v1_9$r9) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_0$r0).get("compare1"))).apply(ordApp1_6$r6))).apply(v_8$r8))).apply(v1_9$r9); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_8$r10) -> { return eqCompose3_7$r7; }; return new __Record$45_71_30_O$63_6f_6d_70_61_72_65_O(new String[]{"compare", "Eq0"}, __field1, __field0); } }).get(); }; }; }; }
public static final Object eq1Compose = __init$eq1Compose();
    private static Object __init$eq1Compose() { return (java.util.function.Function<Object, Object>) (dictEq1_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictEq11_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictEq_2$r2) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Eq.eq)).apply(__M$Data_Functor_Compose.__direct$4(dictEq1_0$r0, dictEq11_1$r1, dictEq_2$r2)); }; return new __Record$65_71_31_O(new String[]{"eq1"}, __field0); } }).get(); }; }; }
public static final Object ord1Compose = __init$ord1Compose();
    private static Object __init$ord1Compose() { return (java.util.function.Function<Object, Object>) (dictOrd1_0$r0) -> { Object ordCompose1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.ordCompose)).apply(dictOrd1_0$r0); Object eq1Compose1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.eq1Compose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd1_0$r0).get("Eq10"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictOrd11_3$r3) -> { Object ordCompose2_4$r4 = ((java.util.function.Function<Object, Object>) (ordCompose1_1$r1)).apply(dictOrd11_3$r3); Object eq1Compose2_5$r5 = ((java.util.function.Function<Object, Object>) (eq1Compose1_2$r2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictOrd11_3$r3).get("Eq10"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (dictOrd_6$r6) -> { return ((java.util.function.Function<Object, Object>) (__M$Data_Ord.compare)).apply(((java.util.function.Function<Object, Object>) (ordCompose2_4$r4)).apply(dictOrd_6$r6)); }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_6$r7) -> { return eq1Compose2_5$r5; }; return new __Record$45_71_31_30_O$63_6f_6d_70_61_72_65_31_O(new String[]{"compare1", "Eq10"}, __field1, __field0); } }).get(); }; }; }
public static final Object bihoistCompose = __init$bihoistCompose();
    private static Object __init$bihoistCompose() { return (java.util.function.Function<Object, Object>) (dictFunctor_0$r0) -> { return (java.util.function.Function<Object, Object>) (natF_1$r1) -> { return (java.util.function.Function<Object, Object>) (natG_2$r2) -> { return (java.util.function.Function<Object, Object>) (v_3$r3) -> { return ((java.util.function.Function<Object, Object>) (natF_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictFunctor_0$r0).get("map"))).apply(natG_2$r2))).apply(v_3$r3)); }; }; }; }; }
public static final Object applyCompose = __init$applyCompose();
    private static Object __init$applyCompose() { return (java.util.function.Function<Object, Object>) (dictApply_0$r0) -> { Object Functor0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object functorCompose1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.functorCompose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictApply1_3$r3) -> { Object apply_4$r4 = ((java.util.function.Function<Object, Object>) (__M$Control_Apply.apply)).apply(dictApply1_3$r3); Object functorCompose2_5$r5 = ((java.util.function.Function<Object, Object>) (functorCompose1_2$r2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply1_3$r3).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_6$r6) -> { return (java.util.function.Function<Object, Object>) (v1_7$r7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApply_0$r0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_1$r1).get("map"))).apply(apply_4$r4))).apply(v_6$r6)))).apply(v1_7$r7); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_6$r8) -> { return functorCompose2_5$r5; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_70_70_6c_79_O(new String[]{"apply", "Functor0"}, __field1, __field0); } }).get(); }; }; }
public static final Object applicativeCompose = __init$applicativeCompose();
    private static Object __init$applicativeCompose() { return (java.util.function.Function<Object, Object>) (dictApplicative_0$r0) -> { Object pure_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Applicative.pure)).apply(dictApplicative_0$r0); Object applyCompose1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.applyCompose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_0$r0).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictApplicative1_3$r3) -> { Object applyCompose2_4$r4 = ((java.util.function.Function<Object, Object>) (applyCompose1_2$r2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative1_3$r3).get("Apply0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Data_Functor_Compose.Compose))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(pure_1$r1))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Applicative.pure)).apply(dictApplicative1_3$r3))); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_5$r5) -> { return applyCompose2_4$r4; }; return new __Record$41_70_70_6c_79_30_O$70_75_72_65_O(new String[]{"pure", "Apply0"}, __field1, __field0); } }).get(); }; }; }
public static final Object altCompose = __init$altCompose();
    private static Object __init$altCompose() { return (java.util.function.Function<Object, Object>) (dictAlt_0$r0) -> { Object functorCompose1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.functorCompose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0$r0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictFunctor_2$r2) -> { Object functorCompose2_3$r3 = ((java.util.function.Function<Object, Object>) (functorCompose1_1$r1)).apply(dictFunctor_2$r2); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_4$r4) -> { return (java.util.function.Function<Object, Object>) (v1_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlt_0$r0).get("alt"))).apply(v_4$r4))).apply(v1_5$r5); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4$r6) -> { return functorCompose2_3$r3; }; return new __Record$46_75_6e_63_74_6f_72_30_O$61_6c_74_O(new String[]{"alt", "Functor0"}, __field1, __field0); } }).get(); }; }; }
public static final Object plusCompose = __init$plusCompose();
    private static Object __init$plusCompose() { return (java.util.function.Function<Object, Object>) (dictPlus_0$r0) -> { Object empty_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Plus.empty)).apply(dictPlus_0$r0); Object altCompose1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.altCompose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictPlus_0$r0).get("Alt0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictFunctor_3$r3) -> { Object altCompose2_4$r4 = ((java.util.function.Function<Object, Object>) (altCompose1_2$r2)).apply(dictFunctor_3$r3); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = empty_1$r1; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_5$r5) -> { return altCompose2_4$r4; }; return new __Record$41_6c_74_30_O$65_6d_70_74_79_O(new String[]{"empty", "Alt0"}, __field1, __field0); } }).get(); }; }; }
public static final Object alternativeCompose = __init$alternativeCompose();
    private static Object __init$alternativeCompose() { return (java.util.function.Function<Object, Object>) (dictAlternative_0$r0) -> { Object applicativeCompose1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.applicativeCompose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlternative_0$r0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)); Object plusCompose1_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Data_Functor_Compose.plusCompose)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlternative_0$r0).get("Plus1"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictApplicative_3$r3) -> { Object applicativeCompose2_4$r4 = ((java.util.function.Function<Object, Object>) (applicativeCompose1_1$r1)).apply(dictApplicative_3$r3); Object plusCompose2_5$r5 = ((java.util.function.Function<Object, Object>) (plusCompose1_2$r2)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictApplicative_3$r3).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (_dollar___unused_6$r6) -> { return applicativeCompose2_4$r4; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_6$r7) -> { return plusCompose2_5$r5; }; return new __Record$41_70_70_6c_69_63_61_74_69_76_65_30_O$50_6c_75_73_31_O(new String[]{"Applicative0", "Plus1"}, __field0, __field1); } }).get(); }; }; }
}
