public class __M$Control_Comonad_Env_Class {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Comonad.Env.Class"); }
    };


public static final Object local = __init$local();
    private static Object __init$local() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("local"); }; }
public static final Object comonadAskTuple = __init$comonadAskTuple();
    private static Object __init$comonadAskTuple() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = __M$Data_Tuple.fst; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r0) -> { return __M$Data_Tuple.comonadTuple; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$61_73_6b_O(new String[]{"ask", "Comonad0"}, __field1, __field0); } }).get(); }
public static final Object comonadEnvTuple = __init$comonadEnvTuple();
    private static Object __init$comonadEnvTuple() { return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_0$r0) -> { return (java.util.function.Function<Object, Object>) (v_1$r1) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_0$r0)).apply(((__M$Data_Tuple.Tuple) (Object)(v_1$r1)).value0), ((__M$Data_Tuple.Tuple) (Object)(v_1$r1)).value1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_0$r2) -> { return __M$Control_Comonad_Env_Class.comonadAskTuple; }; return new __Record$43_6f_6d_6f_6e_61_64_41_73_6b_30_O$6c_6f_63_61_6c_O(new String[]{"local", "ComonadAsk0"}, __field1, __field0); } }).get(); }
public static final Object comonadAskEnvT = __init$comonadAskEnvT();
    private static Object __init$comonadAskEnvT() { return (java.util.function.Function<Object, Object>) (dictComonad_0$r0) -> { Object comonadEnvT_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Env_Trans.comonadEnvT)).apply(dictComonad_0$r0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (v_2$r2) -> { return ((__M$Data_Tuple.Tuple) (Object)(v_2$r2)).value0; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r3) -> { return comonadEnvT_1$r1; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$61_73_6b_O(new String[]{"ask", "Comonad0"}, __field1, __field0); } }).get(); }; }
public static final Object comonadEnvEnvT = __init$comonadEnvEnvT();
    private static Object __init$comonadEnvEnvT() { return (java.util.function.Function<Object, Object>) (dictComonad_0$r0) -> { Object comonadAskEnvT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Env_Class.comonadAskEnvT)).apply(dictComonad_0$r0); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (v_3$r3) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_2$r2)).apply(((__M$Data_Tuple.Tuple) (Object)(v_3$r3)).value0), ((__M$Data_Tuple.Tuple) (Object)(v_3$r3)).value1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r4) -> { return comonadAskEnvT1_1$r1; }; return new __Record$43_6f_6d_6f_6e_61_64_41_73_6b_30_O$6c_6f_63_61_6c_O(new String[]{"local", "ComonadAsk0"}, __field1, __field0); } }).get(); }; }
public static final Object ask = __init$ask();
    private static Object __init$ask() { return (java.util.function.Function<Object, Object>) (dict_0$r0) -> { return ((java.util.Map<String, Object>) dict_0$r0).get("ask"); }; }
public static final Object asks = __init$asks();
    private static Object __init$asks() { return (java.util.function.Function<Object, Object>) (dictComonadAsk_0$r0) -> { return (java.util.function.Function<Object, Object>) (f_1$r1) -> { return (java.util.function.Function<Object, Object>) (x_2$r2) -> { return ((java.util.function.Function<Object, Object>) (f_1$r1)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadAsk_0$r0).get("ask"))).apply(x_2$r2)); }; }; }; }
public static final Object comonadAskStoreT = __init$comonadAskStoreT();
    private static Object __init$comonadAskStoreT() { return (java.util.function.Function<Object, Object>) (dictComonadAsk_0$r0) -> { Object Comonad0_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadAsk_0$r0).get("Comonad0"))).apply(null /* TODO: PrimUndefined */); Object comonadStoreT_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Store_Trans.comonadStoreT)).apply(Comonad0_1$r1); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Env_Class.ask)).apply(dictComonadAsk_0$r0)))).apply((new java.util.function.Supplier<Object>() { public Object get() { Object Functor0_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Comonad0_1$r1).get("Extend0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (v_4$r4) -> { Object __local_var_5$r5 = ((__M$Data_Tuple.Tuple) (Object)(v_4$r4)).value1; return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Functor0_3$r3).get("map"))).apply((java.util.function.Function<Object, Object>) (v1_6$r6) -> { return ((java.util.function.Function<Object, Object>) (v1_6$r6)).apply(__local_var_5$r5); }))).apply(((__M$Data_Tuple.Tuple) (Object)(v_4$r4)).value0); }; } }).get()); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_3$r7) -> { return comonadStoreT_2$r2; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$61_73_6b_O(new String[]{"ask", "Comonad0"}, __field1, __field0); } }).get(); }; }
public static final Object comonadEnvStoreT = __init$comonadEnvStoreT();
    private static Object __init$comonadEnvStoreT() { return (java.util.function.Function<Object, Object>) (dictComonadEnv_0$r0) -> { Object comonadAskStoreT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Env_Class.comonadAskStoreT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadEnv_0$r0).get("ComonadAsk0"))).apply(null /* TODO: PrimUndefined */)); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_2$r2) -> { return (java.util.function.Function<Object, Object>) (v_3$r3) -> { return new __M$Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadEnv_0$r0).get("local"))).apply(f_2$r2))).apply(((__M$Data_Tuple.Tuple) (Object)(v_3$r3)).value0), ((__M$Data_Tuple.Tuple) (Object)(v_3$r3)).value1); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_2$r4) -> { return comonadAskStoreT1_1$r1; }; return new __Record$43_6f_6d_6f_6e_61_64_41_73_6b_30_O$6c_6f_63_61_6c_O(new String[]{"local", "ComonadAsk0"}, __field1, __field0); } }).get(); }; }
public static final Object comonadAskTracedT = __init$comonadAskTracedT();
    private static Object __init$comonadAskTracedT() { return (java.util.function.Function<Object, Object>) (dictComonadAsk_0$r0) -> { Object ask1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Env_Class.ask)).apply(dictComonadAsk_0$r0); Object Comonad0_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadAsk_0$r0).get("Comonad0"))).apply(null /* TODO: PrimUndefined */); Object comonadTracedT_3$r3 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Trans.comonadTracedT)).apply(Comonad0_2$r2); return (java.util.function.Function<Object, Object>) (dictMonoid_4$r4) -> { Object comonadTracedT1_5$r5 = ((java.util.function.Function<Object, Object>) (comonadTracedT_3$r3)).apply(dictMonoid_4$r4); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(ask1_1$r1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Trans_Class.lower)).apply(((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Traced_Trans.comonadTransTracedT)).apply(dictMonoid_4$r4)))).apply(Comonad0_2$r2)); final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_6$r6) -> { return comonadTracedT1_5$r5; }; return new __Record$43_6f_6d_6f_6e_61_64_30_O$61_73_6b_O(new String[]{"ask", "Comonad0"}, __field1, __field0); } }).get(); }; }; }
public static final Object comonadEnvTracedT = __init$comonadEnvTracedT();
    private static Object __init$comonadEnvTracedT() { return (java.util.function.Function<Object, Object>) (dictComonadEnv_0$r0) -> { Object comonadAskTracedT1_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Comonad_Env_Class.comonadAskTracedT)).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadEnv_0$r0).get("ComonadAsk0"))).apply(null /* TODO: PrimUndefined */)); return (java.util.function.Function<Object, Object>) (dictMonoid_2$r2) -> { Object comonadAskTracedT2_3$r3 = ((java.util.function.Function<Object, Object>) (comonadAskTracedT1_1$r1)).apply(dictMonoid_2$r2); return (new java.util.function.Supplier<Object>() { public Object get() { final Object __field0 = (java.util.function.Function<Object, Object>) (f_4$r4) -> { return (java.util.function.Function<Object, Object>) (v_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictComonadEnv_0$r0).get("local"))).apply(f_4$r4))).apply(v_5$r5); }; }; final Object __field1 = (java.util.function.Function<Object, Object>) (_dollar___unused_4$r6) -> { return comonadAskTracedT2_3$r3; }; return new __Record$43_6f_6d_6f_6e_61_64_41_73_6b_30_O$6c_6f_63_61_6c_O(new String[]{"local", "ComonadAsk0"}, __field1, __field0); } }).get(); }; }; }
}
